jg/49/Control-Menu-Display
selsa-inube/linpar pull request #101
Opened 2023-02-15 20:35 UTC by novadeveloper14

2023-02-15 22:13 UTC, CristianRojas-47 approved these changes
Se cumple con los requerimientos solicitados.

2023-02-16 02:05 UTC, wfercanas requested changes

2023-02-16 02:05 UTC, wfercanas commented on src/components/layout/AppPage/styles.js
> +    & nav div p:first-child {
Uy, esta regla y la siguiente son un atentado contra el pobre que haya desarrollado el `<Menu />`, se le están metiendo con los estilos del Menu.

Mentiras, entiendo que aquí cambia la tipografía. Dos cosas sobre eso:
1. Si alguien tiene que ser responsable de algo así es el propio <Menu />, <AppPage /> sólo se debe preocupar por el layout.
2. Vamos a crear un custom hook que se llamará useMediaQuery, que permitirá evaluar la pantalla y según el resultado pasarle a un componente una prop u otra. Por ejemplo, en el componente <Text /> del menú para unos tamaños podemos pasar un token como "titleLarge" y para otros tamaños de pantalla "titleSmall". Así logramos el responsive.
3. Por ahora, dejemos el texto como sea que esté, sin responsive. Lo mismo el padding de abajo.

2023-02-16 02:13 UTC, novadeveloper14 commented on src/components/layout/AppPage/styles.js
> +      border-right: 0px;
sin esa propiedad aparecia un overflow-x ya que el border-right es dependiente de el menu y por defecto tenia un `border-right: 1px solid ${colors.ref.palette.neutral.n40};` por lo que al ponerle 100% al nav este se sobrepasaba

2023-02-16 02:16 UTC, wfercanas commented on src/components/layout/AppPage/styles.js
> +      border-right: 0px;
Mmm, eso pasa entonces porque es content-box y no border-box. Es preferible pasarlo a border-box que luego estar contando pixeles.
Aparte de eso, es un tema de estilos del Menú, habría que arreglarlo allá y no en AppPage

2023-02-17 16:58 UTC, CristianRojas-47 approved these changes
Cumple con los requerimientos solicitados y la creación del portal es correcta.

2023-02-17 21:22 UTC, wfercanas requested changes

2023-02-17 21:22 UTC, wfercanas commented on src/components/Header/styles.js
> +const StyledIcon = styled.div`
Hagamos que los íconos de hamburguesa y la X de cerrar tentan `cursor: pointer`

2023-02-17 21:22 UTC, wfercanas commented on src/components/navigation/Menu/index.jsx
> +        {menu ? (
Aquí en lugar de usar ternarias y retornar null al final, puede hacer `menu && <StyledIcon> ... </StyledIcon/>`

2023-02-20 14:28 UTC, wfercanas approved these changes

2023-02-20 14:28 UTC, merged