ap/53/create app menu component
selsa-inube/linpar pull request #104
Opened 2023-02-17 22:31 UTC by ANGIECATHERINEP

2023-02-18 06:47 UTC, novadeveloper14 requested changes
Realizar los cambios.

`Recomendaciones: ` intentar hacer la maquetación del componente lo más cercano posible a lo que está en el mockup, teniendo en cuenta los colores, tamaños de texto, separaciones entre componentes, etc.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/index.jsx
> +          <ul>
se que el componente Breadcrumbs es solo readonly pero intentemos hacer algo que se asemeje mejor a el mockup, podemos en ves de usar un `<ul>` importar el componente text `import { Text } from "../../data/Text";` y darle como prop el "typoToken" con "Label/large" el cual es el que esta en el mockup.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +const StyledBreadcrumbs = styled.div`
podemos darle color al texto importando los colores y 
dandole `color:${colors.ref.palette.neutral.n900};` para que se asemeje a el mockup.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/AppMenu.stories.js
> +const story = {
teniendo en cuenta que el componente AppMenu es un conjunto de muchos otros componentes, podemos darle a la historia un parametro.

```
parameters: {
    layout: "fullscreen",
  },
```

para que se elimine el padding por defecto que trae storybook. puedes ver mas informacion sobre esta caracteristica en : https://storybook.js.org/docs/react/configure/story-layout

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/index.jsx
> +      <Stack>
el uso de el componente stack es innecesario si no se le va a pasar ninguna prop.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  padding: 0 32px;
StyledBreadcrumbs debe tener un padding en el eje " X " de 65px y en el eje " Y " de 32px recomiendo usar `padding: 32px 65px;` y eliminar el margin.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  padding: 0 32px;
StyledTitle debe tener un padding en el eje " X " de 65px y en el eje " Y " esta pasando algo.
ya que el componente PageTitle por defecto tiene un `margin: 40px 0 32px;` por lo que se esta alejando mas de lo que deberia de el StyledBreadcrumbs recomiendo darle un `margin 0;` usando el operador `& div {...}` atraves de su componente padre (StyledTitle) y hacer que este sea el encargado de su posicionamiento.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  max-width: 1400px;
Este max-width es innecesario.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +const StyledCards = styled.div`
Reemplazemos por un `styled.ul`.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  margin: 20px auto;
StyledCards debe estar separado de StyledTitle por 48px como dice en los mockups.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  justify-content: center;
Este parametro debe ser eliminado para que por defecto sea `flex-start` y vaya 
acorde a los mockups.

2023-02-18 06:47 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +const StyledCards = styled.div`
Para lo que es el apilamiento puede adecuarlo como esta en `<Home/>`  en `pages/home/style.js` usando los media queries.

**otra opcion:** yo estuve pensando en usar mejor 

`grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));`

para que se apilen las cards automaticamente sin media queries y usar el operador 

```
& div {
    margin: auto;
  }
```

para hacer que la card se centre en base a su contenedor pero deberias de preguntarle a @wfercanas  para ver cual es mejor opcion.

2023-02-20 15:52 UTC, ANGIECATHERINEP commented on src/components/layout/AppMenu/styles.js
> +const StyledCards = styled.div`
no lo coloque con media queries porque estuve revisando el mockup de la parte de tablet y movil y observe que cambia el diseño, ya no utiliza cards si no una lista

2023-02-20 15:52 UTC, ANGIECATHERINEP commented on src/components/layout/AppMenu/styles.js
> +  padding: 0 32px;
lo había realizado de esa manera, porque pensé que quedaba el breadcrumbs muy abajo,  de todas maneras hice el cambio

2023-02-20 15:52 UTC, ANGIECATHERINEP commented on src/components/layout/AppMenu/styles.js
> +const StyledBreadcrumbs = styled.div`
hice muy básico el breadcreumbs, ya que esto es algo temporal mientras se añade el componente, por esto no le coloque colores ni ningún otro estilo

2023-02-20 17:04 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  justify-content: flex-start;
Este parametro es innecesario, por eso habia dicho que era mejor eliminar directamente el `justify-content` ya que por defecto viene con `flex-start`.

2023-02-20 17:13 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  max-width: 1400px;
el apilamiento de las cards no se esta realizando, ya que este parametro esta limitando el contenedor. para solucionar esto puedes cambiarlo por `width: 100%;` igualmente para que cada card se centre al momento que se apile puedes usar :

```
& div {
    margin: auto;
  }
```

2023-02-20 17:23 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  padding: 0px 32px;
el contenedor de las cards debe estar tener un padding de 65px en el eje " X " al igual que los demas componentes.

2023-02-20 17:28 UTC, novadeveloper14 commented on src/components/layout/AppMenu/styles.js
> +  margin: 48px auto;
al ponerle margin auto en el eje " X " le esta permitiendo a el contenedor agregar un margin con el espacio restante y de esta forma haciendo que se centre (por ejemplo cuando cambies `max-width: 1400px;` por `width: 100%;`)
lo cual no es lo que estamos buscando ademas que se le van a sumar a los 32px que ya tiene por padding. mejor cambiemoslo por `margin: 48px 0px;`.

2023-02-20 20:34 UTC, novadeveloper14 reviewed
Todos los cambios requeridos fueron realizados y se logro algo mas semejante a lo que se presenta en los mockups.

2023-02-21 03:12 UTC, wfercanas requested changes

2023-02-21 03:12 UTC, wfercanas commented on src/components/layout/AppMenu/styles.js
> +  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
Esta forma de aplicar los estilos hace que el espacio entre tarjeta y tarjeta sea variable según el ancho de la pantalla. Precisamente por esa razón tuve que hacer manejar la grilla con varios media-query en `<Home />`, de tal forma que las tarjetas permanecieran juntas.

Tristemente llegué a esta solución porque aunque esto funcionaría en principio bien:
```js
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-start;
```

Para ciertos tamaños de pantalla quedan unos espacios blancos a la derecha donde sólo cabe el 99% o el 90% o el 85% de la tarjeta y como se usa `wrap`, ese espacio blanco queda ahí recargado a la derecha y no se ve bien.

Si ves otra manera de usar flex pero garantizar que el contenedor queda centrado como si tuviera `margin: 0 auto`, sería lo máximoooo. Si no, usemos la solución que está en `<Home />`

2023-02-21 03:12 UTC, wfercanas commented on src/mocks/apps/privileges.mock.js
> +    url: "/users",
Estas opciones como son internas de privileges, deberían tener la ruta como **"privileges/users"**

2023-02-21 03:12 UTC, wfercanas commented on src/components/layout/AppMenu/AppMenu.stories.js
> +Privileges.args = {
Es preferible que estos args los escribas tú y no que uses los mocks. Esto porque esos archivos deberán eventualmente desaparecer por los consumos adecuados del backend y no por ello deberían dejar de funcionar las historias.

2023-02-21 20:02 UTC, wfercanas requested changes

2023-02-21 20:02 UTC, wfercanas commented on src/components/layout/AppMenu/styles.js
> +const StyledTitle = styled.div`
Asegúrate de que entre los breacrumbs y el title hay 32px y no 16px

2023-02-21 20:53 UTC, wfercanas approved these changes

2023-02-21 20:53 UTC, merged