feat(routes): intercept errors when redirected to non-defined routes
selsa-inube/linpar pull request #106
Opened 2023-02-20 16:10 UTC by CristianRojas-47

2023-02-20 17:34 UTC, ANGIECATHERINEP approved these changes
el requerimiento solicitado fue realizado correctamente

2023-02-21 02:42 UTC, wfercanas requested changes

2023-02-21 02:42 UTC, wfercanas commented on src/App.js
> +        errorElement={
Bien. Reemplacemos este jsx por `<ErrorPage />` y en la siguiente tarea ya dejamos todo como debería ser.
El componente está en `components/layout/ErrorPage`

2023-02-21 15:36 UTC, wfercanas approved these changes

2023-02-21 15:36 UTC, merged