ap/58/Link-appLogo-Header-component
selsa-inube/linpar pull request #108
Opened 2023-02-20 22:14 UTC by ANGIECATHERINEP

2023-02-20 22:51 UTC, CristianRojas-47 approved these changes
El requerimiento solicitado se desarrolló correctamente

2023-02-21 02:26 UTC, wfercanas requested changes

2023-02-21 02:26 UTC, wfercanas commented on src/components/Header/Header.stories.js
>  import { Header } from "../Header";
Crea ahora una carpeta llamada **stories/**. Dentro puedes colocar este archivo y crear otro para crear el Controller.

De hecho, el Controller lo puedes renombrar como HeaderController y crearlo en HeaderController.jsx dentro de **stories/**

2023-02-21 02:26 UTC, wfercanas commented on src/components/Header/interface.jsx
> +        <StyledcontentImg to="/">
No dejemos hardcodeada la dirección. Pasemos una prop que sea `appLogoRedirect`. Esa prop puede tener como valor por defecto **"/"**

2023-02-21 15:47 UTC, wfercanas approved these changes

2023-02-21 15:48 UTC, merged