feat(privilegesOptions): create component privilegesOptions, modify r…
selsa-inube/linpar pull request #111
Opened 2023-02-22 15:09 UTC by ANGIECATHERINEP

…oute and appMenu styles

2023-02-22 16:42 UTC, CristianRojas-47 requested changes
1. En el mock de privileges modificar las url eliminado el privileges que antecede a cada ruta, esto debido a que la ruta actualmente se muestra **"privileges/options/privileges/users"** y con el cambio se vería "privileges/options/users".
2. Esto no corresponde a un error sino a una observación, ¿es posible cambiar las medidas del grid-template-columns?, ya que actualmente se encuentra en "repeat(4, 250px)" a "repeat(5, 200px)" para que no se vean tan grandes estas tarjetas y definir desde allí las media-query para la cantidad a visualizar por línea.
![repeat(5-200px)](https://user-images.githubusercontent.com/93727887/220696070-7951b8f5-3b39-44a1-9b62-5480c4d49a06.jpg)
![repeat(4-250px)](https://user-images.githubusercontent.com/93727887/220696073-7bedf346-e559-427d-8eb4-e8874a1ce3c5.jpg)

2023-02-22 16:42 UTC, CristianRojas-47 commented on src/components/layout/AppMenu/styles.js
El elemento por defecto recibe un padding-inline-start de 40 px, recomiendo agregar un padding: 0 para que elemento quede centrado.

2023-02-23 19:40 UTC, wfercanas requested changes

2023-02-23 19:40 UTC, wfercanas commented on src/components/layout/AppMenu/styles.js
> +  grid-template-columns: repeat(4, 250px);
Creo que todavía puedes arrancar inclusive desde 6 columnas y que cuando vayas bajando, permitas que la primera tarjeta llegue al borde izquierdo alineandose con PageTitle y ahí metes el media query para reducir las columnas.

2023-02-23 19:40 UTC, wfercanas commented on src/components/layout/AppMenu/styles.js
>      grid-template-columns: repeat(3, 250px);
Todos estos 250px los puedes cambiar por auto, así dejas que el ancho sea el que se defina en la card y no en la grilla.

2023-02-23 19:40 UTC, wfercanas commented on src/mocks/apps/privileges.mock.js
> +    url: "users",
Las rutas a las que se navega desde aquí no están anidadas dentro de /options sino dentro de /privileges. Habría que dejar las rutas entonces como estaban.

2023-02-23 19:40 UTC, wfercanas commented on src/pages/privileges/index.jsx
> +    if (location.pathname === "/privileges") {
Funciona para `/privileges` pero deberíamos hacer que también funcione para `/privileges/`

2023-02-24 14:40 UTC, wfercanas commented on src/mocks/apps/privileges.mock.js
> +    url: "users",
Creo que no te funciona bien porque antes de privileges hay que colocar `/`. Quedaría entonces algo como `/privileges/users`.
Si no pones el primer `/` el router entiende que es una opción anidada de `/options`.

2023-02-24 14:41 UTC, wfercanas commented on src/components/layout/AppMenu/styles.js
> +  grid-template-columns: repeat(4, 250px);
Te falta el media query de pasar a 1 columna

2023-02-24 16:22 UTC, wfercanas approved these changes

2023-02-24 16:23 UTC, merged