jg/69/Extend-Button-Component
selsa-inube/linpar pull request #112
Opened 2023-02-22 17:28 UTC by novadeveloper14

2023-02-22 21:13 UTC, ANGIECATHERINEP requested changes

2023-02-22 21:13 UTC, ANGIECATHERINEP commented on src/components/inputs/Button/styles.js
>    color: ${colors.ref.palette.neutral.n0};
la medida del padding según el mockup es de 4px 12px

2023-02-22 22:38 UTC, ANGIECATHERINEP approved these changes
los cambios fueron realizados correctamente

2023-02-23 21:13 UTC, wfercanas requested changes

2023-02-23 21:13 UTC, wfercanas commented on src/components/inputs/Button/styles.js
>    font-family: ${typography.sys.typescale.bodyMedium.font};
Si en index.jsx está usando un `<Text />` como children, ¿por qué aquí necesita definir a mano las propiedades tipográficas?

2023-02-23 21:13 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +      appearance={appearance}
Está recibiendo la props appearance y se la está pasando al StyledButton, pero no está haciendo nada con ella en los estilos.

2023-02-23 21:13 UTC, wfercanas commented on src/components/inputs/Button/styles.js
>    font-size: ${typography.sys.typescale.bodyMedium.size};
Más abajo, en los estilos de `:disabled` usemos tokens de sistema (sys.text para el color y sys.actions para el background).

2023-02-23 21:13 UTC, wfercanas commented on src/pages/login/outlets/Clients/interface.jsx
>          <Button
Usemos la forma convencional de pasar la prop children: `<Button>Continuar</Button>`

2023-02-23 21:13 UTC, wfercanas commented on src/components/layout/ErrorPage/index.jsx
> +          <Button children="Exit" iconBefore={<MdChevronLeft size={18} />} />
Usemos la forma convencional de pasar la prop children: `<Button>Exit</Button>`

2023-02-24 16:18 UTC, wfercanas commented on src/components/inputs/Button/styles.js
>    font-family: ${typography.sys.typescale.bodyMedium.font};
No hace falta que dentro de `<Button />` defina estilos tipográficos si al final va a usar `<Text />` con su respectivo `typoToken` para eso.

2023-02-24 20:41 UTC, wfercanas approved these changes

2023-02-24 20:42 UTC, merged