Cr/67/create tabs component
selsa-inube/linpar pull request #114
Opened 2023-02-23 13:41 UTC by CristianRojas-47

2023-02-23 16:32 UTC, novadeveloper14 requested changes
La estructuración de el componente es correcta, realizar los cambios solicitados de los estilos.

2023-02-23 16:32 UTC, novadeveloper14 commented on src/components/navigation/Tab/styles.js
> +    props.isActive ? `4px solid ${colors.sys.actions.primary}` : `none`};
aca en ves de usar un operador ternario con `none` el cual el parametro `border-bottom` ya tiene establecido por defecto podemos usar el operador `&&` (and) y hacer que el border-bottom solo se cree cuando el tab esta activo y no definirlo como none desde un principio.

```
border-bottom: ${(props) => props.isActive && `4px solid ${colors.sys.actions.primary}`};

```

2023-02-23 16:32 UTC, novadeveloper14 commented on src/components/navigation/Tab/styles.js
> +  margin-right: 24px;
en ves de realizar la separacion con el margin, el componente padre `StyledTabsContainer `
el cual ya tiene `display: flex;` podemos darle `gap: 24px;` para que sea este el que realize el espaciado
entre los `<li>` hijos.

2023-02-23 16:32 UTC, novadeveloper14 commented on src/components/navigation/Tab/styles.js
> +  list-style-type: none;
esta propiedad aca funciona pero es mejor que el encargado de quitarle los estilos a el listado sea
el padre asi que mejor llevemosla a` StyledTabsContainer` el cual es el `<ul>` y pongamosle:
`
list-style: none;`

2023-02-23 16:32 UTC, novadeveloper14 commented on src/components/navigation/Tab/styles.js
> +  padding-bottom: 4px;
el `padding-bottom` que tiene el tab cuando no esta activo es de **8px** y cuando esta activo es de **4px** 
y los otros **4px** los ocupa el `border-buttom` por lo que se deberia ajustar la condicion en este parametro.
```

  padding-bottom: ${(props) => (props.isActive ? `4px` : `8px`)};

```

2023-02-23 16:32 UTC, novadeveloper14 commented on src/components/navigation/Tab/styles.js
> +const StyledTab = styled.li`
cada tab debe tener un padding-top de 10px.

2023-02-23 16:32 UTC, novadeveloper14 commented on src/components/navigation/Tabs/Tabs.stories.js
> +const story = {
Me parece bien que en storybook se pueda registrar en actions el momento en el que se cambia de pestaña 
atraves de el handleClick.

2023-02-24 00:38 UTC, novadeveloper14 reviewed
Los cambios se implementaron correctamente.

2023-02-24 20:34 UTC, wfercanas requested changes

2023-02-24 20:34 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +  const { titles } = props;
Cambiemos la prop "titles" por "tabs", que sea entonces un array que contiene objetos, donde cada objeto es una tab.
```js
const tabs = [
  {
    id: "privileges-users",
    content: "users",
  }, 
  // ...
]
```

2023-02-24 20:34 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +  const { titles } = props;
Aparte de la prop `titles`, hagamos que también le lleguen estas props:
1. `selected`: trae el id de la tab que va seleccionada.
2. `handleTabChange`: es una función que permite modificar la tab seleccionada.

Este cambio tiene un impacto importante:
1. Quien maneja el estado ya no es `<Tabs />` sino su padre, que seguramente será un `<Outlet />`.
2. Ese `<Outlet />` va a retornar las `<Tabs />` y debajo va a retornar el contenido de la `<Tab />` seleccionada.
3. Cuando se utiliza la función `handleTabChange`, se cambia el estado `selected`.
4. Ese cambio en `selected` impacta a `<Tabs />` porque ahora debe prender otra pestaña y también afecta al `<Outlet />` porque el jsx a retornar debajo de las Tabs será otro.

**En conclusión, las Tabs se vuelven un componente controlado por el padre y ese padre se encarga entonces del estado, del setter del estado y de modificar su return según el valor que tenga el estado.**

2023-02-24 20:34 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +  const handleClick = (tabIndex) => {
Esta función ya no sería necesaria.

2023-02-24 20:34 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +        {titles.map((title, id) => (
Usemos el `id` que viene dentro de la prop `tabs` y no los índices del array.

2023-02-24 20:34 UTC, wfercanas commented on src/components/navigation/Tabs/Tabs.stories.js
> +import { Tabs } from "../Tabs";
El cambio pedido en las props de `<Tabs />` implicarán que tengamos que crear un componente `<TabsController /> ` dentro de **stories/**
Ese componente sería el que tendría el estado y el que retornaría a `<Tabs />`. En la práctica ese <TabsController /> será el componente que importe y use a `<Tabs />`

2023-02-27 21:57 UTC, novadeveloper14 requested changes
**Ademas de los cambios solicitados realizar los siguientes cambios adicionales:**

- Eliminar el archivo **styles.js** adentro de **TabsController/** el cual esta vacio y no interrumpe el funcionamiento de el compononte.

- Cambiar el nombre de la carpeta **TabsController/** a **stories/** ya que este mismo es solo un componente que esta usando la storie simulando que es el componente padre de `<Tabs />`

- mover esta carpeta **stories/ (ahora)** adentro de el componente tabs para que no quede al mismo nivel de los demas componentes de navegacion.

2023-02-27 21:57 UTC, novadeveloper14 commented on src/components/navigation/Tabs/index.jsx
> +  useEffect(() => {
Este `useEffect` no es necesario ya que por defecto el `selected` ya viene de el componente padre de `<tabs/>` inicializado como 0.

2023-02-27 21:57 UTC, novadeveloper14 commented on src/components/navigation/Tabs/index.jsx
> +  const handleClick = (tabId) => {
esta funcion no es necesaria ya que el que esta haciendo que `setActiveTab` cambie el estado de `selected` es la funcion `handleTabChange` que le esta llegando por props a `<tabs/>`.

2023-02-27 21:57 UTC, novadeveloper14 commented on src/components/navigation/Tabs/index.jsx
> +            handleClick={handleClick}
Teniendo en cuenta los anteriores comentarios aca lo que tendriamos que ponerle a el `handleClick` es la funcion `handleTabChange` de esta forma estariamos haciendo que el encargado del estado, del setter del estado y de modificar su return según el valor que tenga el estado sea el padre de `<tabs/>` en el contexto que se utilize.

2023-02-27 21:57 UTC, novadeveloper14 commented on src/components/navigation/Tabs/index.jsx
> +            isActive={id === activeTab}
Igualmente aca en ves de darle `activeTab` simplemente tendriamos que darle `selected` ya que es la prop que se esta asignando y modificando en el componente padre.

2023-03-02 21:22 UTC, wfercanas approved these changes

2023-03-02 21:22 UTC, merged