jg/70/Make-Active-MenuLink-any-URL
selsa-inube/linpar pull request #118
Opened 2023-02-28 16:56 UTC by novadeveloper14

2023-02-28 21:34 UTC, ANGIECATHERINEP approved these changes
El cambio requerido fue realizado y funciona correctamente

2023-03-02 21:34 UTC, wfercanas requested changes
Funciona correctamente en desktop, pero entonces tenemos 2 problemas a resolver:
1. Cuando estamos en tablet o mobile y abrimos el menú a pantalla completa, la idea es que ahí sí no aparezca prendido el `<MenuLink />`.
2. Si el usuario hace click en el `<MenuLink />` que está activo, no hay redirección porque el usuario ya está ahí, pero el menú se queda pegado. Debería cerrarse.

2023-03-03 17:58 UTC, wfercanas requested changes

2023-03-03 17:58 UTC, wfercanas commented on src/components/navigation/MenuLink/styles.js
> +    props.selected && !props.menu
Si evitamos que `<MenuLink />` tenga acceso al estado y la prop `isSelected` ya viene como true o false, no sería necesario tener estos condicionales en los estilos.

2023-03-06 20:26 UTC, wfercanas requested changes

2023-03-06 20:26 UTC, wfercanas commented on src/components/navigation/MenuLink/index.jsx
> +      selected={isSelected}
Mantengamos el `isSelected` también para el styled-component

2023-03-06 20:33 UTC, novadeveloper14 commented on src/components/navigation/MenuLink/index.jsx
> +      selected={isSelected}
de esa manera me estaba presentando un error de consola el cual era:

`Warning: React does not recognize the `isSelected` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isselected` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

2023-03-07 14:25 UTC, wfercanas requested changes
En stories hace falta:
1. Cambiar las args `selected` por `isSelected`
2. Dejar el title de story como "components/navigation/MenuLink"

2023-03-07 14:38 UTC, wfercanas approved these changes
En stories hace falta:
1. Cambiar las args `selected` por `isSelected`
2. Dejar el title de story como "components/navigation/MenuLink"

2023-03-07 14:38 UTC, merged