feat(storybook): storybook deployment with gitHub action
selsa-inube/linpar pull request #119
Opened 2023-02-28 20:31 UTC by CristianRojas-47

2023-03-01 00:31 UTC, novadeveloper14 requested changes
El Deploy de storybook se realizo correctamente, realizar el cambio para evitar el warning de la story.

2023-03-01 00:31 UTC, novadeveloper14 commented on src/components/navigation/Menu/stories/Menu.stories.js
> -export const Layout = withLayout(Template.bind({}));
se que esta story esta generando error, pero si se va a comentar la export de la story tambien se tiene que comentar la funcion donde se esta implementando el layout y los imports que este mismo utiliza, para que en consola no genere esta warning:

```
undefined undefined
[eslint]
 src\components\navigation\Menu\stories\Menu.stories.js
  Line 26:7:  'withLayout' is assigned a value but never used  no-unused-vars
```

2023-03-01 16:57 UTC, novadeveloper14 reviewed
El Deploy se realizó correctamente.

2023-03-02 21:48 UTC, wfercanas requested changes
Además del comentario en el código, hay que hacer 2 ajustes:
1. Agregar en el .gitignore el archivo build-storybook.log
2. Como estamos usando npm y no yarn, todas las instalaciones hay que hacerlas usando npm. Borremos el archivo yarn.lock, use npm install luego de borrar el yarn.lock y garantice que todo sigue funcionando.

2023-03-02 21:48 UTC, wfercanas commented on package.json
> +    "chromatic": "npx chromatic --project-token=56993debfe11"
Esta forma de hacerlo funciona cuando hay que hacerlo a mano, así dejamos el project token en el package.json. Como usamos GitHub Actions para automatizar y ya guardamos ese token como secret en el repositorio, no hace falta registrarlo aquí.

De hecho, en general no deberíamos publicar tokens.

Entonces, según veo hizo 2 commits. Habría que hacer un git reset 2 commits atrás, borrar el project-token en el package.json y probar que si se hace el commit y el push sin ese token ahí sigue funcionando el workflow.

2023-03-03 16:45 UTC, wfercanas approved these changes

2023-03-03 16:45 UTC, merged