feat(table): create style the table component according to the mockup…
selsa-inube/linpar pull request #120
Opened 2023-03-01 20:53 UTC by ANGIECATHERINEP

…s and the story

2023-03-02 18:32 UTC, novadeveloper14 commented on src/components/data/table/styles.js
> +    width: 30px;
Ya tiene un width de 80px pero se esta sumando el padding que tiene arriba `(padding: 12px 16px;)` por lo que tendriamos que eliminar este padding que tiene en el eje X para que sea realmente de 80px, se tendria que modificar el padding por: `(padding: 12px 0px;)`

2023-03-02 18:41 UTC, novadeveloper14 commented on src/components/data/table/styles.js
> +  & svg {
ademas de estos cambios podemos agregarle a todos los iconos el siguiente parametro para poder indicar que es un elemento clickable:
```

  & svg {
    cursor: pointer;
  }
```

2023-03-03 13:03 UTC, novadeveloper14 requested changes

2023-03-03 20:48 UTC, wfercanas requested changes

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/Table.stories.js
> +    titleName: "Code",
Deja todos los títulos en minúscula: "code". El empezar por mayúscula arreglalo cuando estés pintando la tabla. Te puede servir usar `String.charAt(0)` y `.toUpperCase()`

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/index.jsx
> +      <Pagination
Controla que la paginación sólo aparezca cuando hay 11 registros o más. Con 10 o menos no vale la pena.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/index.jsx
> +import { Pagination } from "./pagination";
Cambia el nombre de la carpeta a Table (mayus).

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/interface.jsx
> +          <StyledTableTr>
Puedes abreviar para no escribir tanto Table en los styled-components. Usa `StyledTHead`, `StyledTd`, con eso el código no queda tan largo.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/interface.jsx
> +          {entries.map((itemEntrie, i) => (
1. Puedes llamarlo: `entry`, en singular.
2. En los mockups estamos usando el mismo usuario muchas veces por facilidad, pero en realidad aquí tienen que mostrarse usuarios diferentes. Inventate unos usuarios nuevos y asigna un id único a cada uno. Con ese `id` puedes manejar la prop `key` y no usar el `index`.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/interface.jsx
> +            {titles.map((item, index) => (
Cada `title` tiene un atributo `id`, usa ese atributo y no el index para la key.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/interface.jsx
> +            {actions.map((item, index) => (
Puedes usar el `actionName` como `key` o mejor aún, agregar un `id` para cada action en el objeto y usar ese `id` en lugar del `index`.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/interface.jsx
> +              {actions.map((itemAction, indexAction) => (
Usa el `id` de la action, no el index.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/pagination/index.jsx
> +import {
Cambia el nombre de la carpeta a Pagination (mayus)

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/pagination/index.jsx
> +      <button onClick={handleStartPage}>
Utiliza `StyledButton`s

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/pagination/index.jsx
> +      <button onClick={handlePrevPage}>
Habla con Leonardo a ver si a estos botones de paginación hay que agregarles algún efecto `:hover`, yo creería que sí.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/pagination/styles.js
> +    width: 49px;
Los botones deberían tener el mismo tamaño. Los espacios a izquierda y derecha deberías lograrlos con un container que agrupe a los buttons y use margins y paddings para eso.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/pagination/styles.js
> +  }
Si los botones son de igual tamaño, no necesitas alinearlos a izquierda o derecha.

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/styles.js
> +`;
Este componente te sobra y puedes dejar la sola tabla con `box-sizing: border-box`

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/styles.js
> +  table-layout: initial;
Creo que esta tabla es más de `table-layout: auto`

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/styles.js
> +  &:nth-last-of-type(-n + 3) {
En este ejemplo hay 3 columnas de acciones, pero podría haber 2, 1, ninguna, 4, etc...
Entonces te sugiero que crees un `StyledThAction` y un `StyledThTitle` para separar los estilos y dentro del return del table usar el que corresponde según si haces `titles.map` o `actions.map`

2023-03-03 20:48 UTC, wfercanas commented on src/components/data/table/styles.js
> +    color: ${colors.ref.palette.red.r300};
Ahora que veo esto, creo que en el objeto actions, aparte de actionName y tal, hay que colocar otro atributo `type` y cuyos valores sean "primary", "remove", "success", etc.. (alineado con los colors.sys.actions).
De esa manera aquí sabríamos qué color aplicarle según el type cuando exista hover.

2023-03-03 20:48 UTC, wfercanas commented on src/mocks/apps/dataTable.mock.js
> +const title = [
Cambialo por titles (plural)

2023-03-03 20:48 UTC, wfercanas commented on src/mocks/apps/dataTable.mock.js
> +const entrie = [
Cambialo por entries (plural)

2023-03-07 17:15 UTC, wfercanas requested changes

2023-03-07 17:15 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +            {actions.map((itemAction) => (
Cuando haces el map de `entries` y colocas la `key`, lo que estas haciendo es darle una key a cada fila de la tabla. Ahora, como cada fila tiene unas actions al final, hay que ser capaz de separar las actions de la fila 1 de las actions de la fila 2.
Por esta razón, aquí no es suficiente con usar `action.id` como `key`, porque entonces todas las filas tendrían actions con las mismas `keys`. Te va a salir un error en consola.

**Conclusión**: al anidar el map de actions dentro del map de entries, vas a tener que concatenar la key de cada entry con la key de la action para obtener una combinación única.

2023-03-09 01:01 UTC, ANGIECATHERINEP commented on src/components/data/Table/interface.jsx
> +              <Text typoToken="bodySmall">{entry.position}</Text>
Para realizar el cambio en el cuerpo de la tabla hice una función que itera los entries, ordena cada valor del atributo de estos y lo ubica según el id de los titles, retornando un arreglo bidimensional, por esta razón no me fue posible colocar como key en cada fila el id si no coloque el index.

2023-03-09 14:54 UTC, wfercanas requested changes

2023-03-09 14:54 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  function IterateList() {
Entiendo la intención de esta función y al final lo que obtienes es un array lleno de arrays, donde cada uno de los array internos es un registro que ya tiene los valores que van en la tabla (incluyendo un null si es que para esa columna no hay datos).

Sin embargo, creo que esta implementación queda un poco oscura y hay que leer detalladamente esta función y luego en TableUI el efecto dentro de los maps para terminar de entender.

Considero que sería mejor que:
1. `Table` le pase a `TableUI` los entries tal cual (es decir, un array con objetos, donde cada objeto va a ser eventualmente una fila de la tabla).
2. `TableUI` haga un map de las entries, luego, para cada iteración de entries, efectivamente como lo tienes, hay que crear una fila (StyledTr).
3. Dentro de cada fila, también es necesario otro map, porque hay que ir llenando las columnas de la tabla. **Aquí es donde está el cambio**. Como lo que necesitamos es llenar las columnas, vamos a ir columna a columna, así que el map no es sobre `entry` (que es el objeto de cada iteración), sino sobre `titles`.
4. Para cada title, hay que obtener entry[title] e insertar un StyledTd.
5. Si entry[title] retorna undefined, pues igual hay que insertar el StyledTd pero con el valor null.

De esta manera:
1. En index no hay que crear una nueva estructura de datos (array de arrays).
2. Solamente hacemos una anidación de maps (map de columnas dentro de un map de filas). En este punto tenemos 2 anidaciones, la de la transformación de la estructura de datos y la de la tabla. Creo que aumenta la complejidad del código y no se justifica.
3. La anidación que nos queda es más intuitiva, porque estamos primero recorriendo las filas (entries) y para cada entry estamos extrayendo el valor de cada columna (entry[title]).

2023-03-10 03:28 UTC, wfercanas requested changes

2023-03-10 03:28 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +            {titles.map((entryValue) =>
Así queda mejor. Sin embargo, usa `title` en lugar de `entryValue` porque es un map sobre `titles`. Si no más abajo parece que `entryValue` es parte de `entry` y nada que ver.

2023-03-13 19:49 UTC, wfercanas requested changes

2023-03-13 19:49 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  function pagination() {
Cambiemos el nombre de la función por una acción. Podría ser algo así como `getPageEntries`.

2023-03-13 19:49 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  function startPage() {
Cambiemos el nombre de la función por una acción. Puede ser `goToFirstPage`

2023-03-13 19:49 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  function endPage() {
`goToEndPage()`

2023-03-13 19:49 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +    const records = Math.ceil(entries.length / pageLength);
Esta variable más que `records` es `totalPages`. De hecho, si a este Math.ceil() se le resta el -1 aquí directamente, tendrías `lastPageIndex`.

La parte que está algo confusa de leer es que teniendo `lastPageIndex` (por ejemplo, igual a 3), tomas ese valor y lo multiplicas por la longitud de cada página (ej, 10). Para el ejemplo, tendrías 30 y defines la currentPage como 30, que ya es una exageración.

O es así como lo escribo o está funcionando diferente y conviene refactorizar para que sea más fácil de leer.

2023-03-15 14:45 UTC, wfercanas requested changes

2023-03-15 14:45 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  const [entriesIndex, setEntriesIndex] = useState(0);
Dos cosas a cambiar aquí:
1. Este estado no es necesario, de hecho puede hacer más dificil de debuggear el código en un futuro porque hay que garantizar que esté sincronizado con el estado `currentPage`. Realmente este es un efecto secundario de la selección de página y puede tratarse como una variable común y corriente.
2. El nombre `entriesIndex` es confuso porque entries está en plural y un índice aplica sólo para una unidad. Aquí estás realmente obteniendo el primer registro de la página, asi que conviene renombrar a algo como `firstEntryInPage`.

**Nota**: puedes ver una explicación más detallada del primer punto aquí: https://beta.reactjs.org/learn/managing-state#choosing-the-state-structure

2023-03-15 14:45 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +          valueDataEnd={numRecordsEnd()}
Veo que en la práctica estas necesitando el estado `entriesIndex` sólo para el desde-hasta de la paginación.

Realmente no hace falta crear un estado y funciones para obtener esos datos. Con el número de la página (`currentPage`) y pageLength puedes deducir esa información dentro de `<Pagination />`

2023-03-15 14:45 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  const [entriesIndex, setEntriesIndex] = useState(0);
Ya revisé más abajo para qué estas usando entriesIndex y creo que sobra del todo su existencia en el código. Revisa el comentario que está en el return del index.jsx sobre este punto

2023-03-15 14:45 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +  }
Estas dos últimas funciones sobran aquí.

2023-03-15 14:45 UTC, wfercanas commented on src/components/data/Table/Pagination/index.jsx
> +          {valueDataFirst} - {valueDataEnd} of {totalRecords}
Estos valores los puede calcular `<Pagination />` por sí mismo con sólo tener la página actual y el total de registros.

2023-03-16 03:37 UTC, wfercanas requested changes

2023-03-16 03:37 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +          valueDataEnd={LastEntryInPage}
Cambiemos los nombres de estas dos props. Usemos los mismos nombres que las variables (firstEntryInPage y lastEntryInPage)

2023-03-21 23:02 UTC, wfercanas requested changes

2023-03-21 23:02 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +          valueExists = true;
Si encuentras un atributo que cumple, no es necesario buscar los demás atributos porque igual tienes que mostrar el registro. Así que aparte del valueExists puedes hacer un break para que el ciclo no siga.

2023-03-21 23:02 UTC, wfercanas commented on src/components/data/Table/index.jsx
> +      return valueExists;
De hecho, podrías no usar la variable `valueExists`. Puedes hacer un return true dentro del for y fuera del for un return false.
Si la ejecución sale del for y llega al return false es porque por dentro del for nunca encontró un caso que ameritara el return true.

(De paso te ahorras el break que propuse en el otro comentario).

2023-03-28 20:11 UTC, wfercanas requested changes

2023-03-28 20:11 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +const sizeScreens = [
Este objeto sería útil si es la tabla la que autónomamente define cuántas columnas mostrar dados unos tamaños de pantalla. Sin embargo, esto puede no ser lo más conveniente pues dependiendo de los datos a mostrar, para un tamaño de pantalla puedo querer mostrar 1, 2, ...o 5 columnas.

Entonces: la tabla no va a hacer una definición de pantallas con media queries relacionados a esos tamaños (es decir, no vamos a crear este objeto), sino que la tabla aparte de recibir los titles, deberá recibir otra prop que se llame breakpoints. Esa prop es array de objetos, donde cada objeto tiene por llaves el breakpoint (ej: "(min-width: 1000px)" y totalColumns (ej: 4).

2023-03-30 14:44 UTC, wfercanas requested changes

2023-03-30 14:44 UTC, wfercanas commented on src-table.zip
Por qué agregaste este .zip? Creo que hay que borrarlo. De hecho, habría que hacer un git reset para deshacer el commit donde lo guardaste y volver a hacer el commit sin este archivo, si no este .zip queda en la historia del proyecto.

2023-04-11 19:30 UTC, wfercanas requested changes

2023-04-11 19:30 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +    handleUpdateState(mediaQueryLists);
En el hook que recibimos del design-system, el propósito de ejecutar la función handleChange() aquí dentro del effect es hacer la primera verificación del estado para saber si definitivamente ese query único sigue en false como se definió en el initialState o si hay que cambiarlo a true.

En nuestro caso, necesitamos ejecutar una función similar para determinar ya no para un sólo query sino para todos los queries, si estos deberían seguir en false o si algunos de ellos deberían estar en true.

**Por lo tanto**: aquí debería haber una única función ejecutada que se encargue de chequear todos los queries en mediaQueryList y una vez obtenidos todos los resultados, actualizar el estado. Sugiero que esa función ya no se llame `handleChange` sino que se llame `checkAllQueries`.
Así, podemos quitar el handleChange() llamado directamente dentro del effect y dejarlo sólo para ser enlazado con el evento "change" de los `eventListeners`

2023-04-12 14:46 UTC, wfercanas requested changes

2023-04-12 14:46 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +    const lists = queries.map((breakpoint) => window.matchMedia(breakpoint));
Aquí lo que yo quería decir era que dejáramos la variable como `mediaQueryList`, porque es sólo una lista (no como estaba antes que decía `mediaQueryLists` en plural.

2023-04-14 23:25 UTC, wfercanas requested changes

2023-04-14 23:25 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +function totalColumns(titles, breakPoints, media) {
Renombremos como `totalTitleColumns` para saber que hace referencia sólo a las columnas de titles.

2023-04-14 23:25 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +  return ColumnTitles.slice(0, showColBreakpoint(breakPoints, media));
Aquí la lógica está algo densa y estamos combinando un par de conceptos quizá erróneamente.

Sugiero que:
1. Primero calcules cuántas columnas debemos pintar usando `media`, esto antes de hacer cualquier trabajo con los titles.
2. Una vez sepas cuántas columnas van, puedes hacer una copia de titles y trabajar con ella para obtener la lista de titles que sí van.
3. Una cosa es quitar/poner columnas y otra cosa es ordenar columnas. Yo creo que quien arme el día de mañana el objeto titles, lo arma en el orden en que quiere ver sus columnas y nosotros no deberíamos contradecirlo. Es decir, nosotros no deberíamos reordenar la lista de titles.
4. Para lo único que nos debería servir el parámetro `responsiveOrder` es para saber cuál columna sí va y cuál no va según la cantidad de columnas que deduzcamos usando `media`. De hecho, deberíamos cambiarle el nombre de `responsiveOrder` por `priority`.

2023-04-14 23:25 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +function mediaQueryAct(media) {
1. Renombremos por la función por `findCurrentMediaQuery` y la variable como `currentMediaQuery`.
2. Intenta refactorizar el `for` por un `array.lastIndexOf`. La idea es que al leer el código sea rápido identificar que estas buscando el último índice que tiene valor true.

2023-04-14 23:25 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +function showColBreakpoint(breakPoints, media) {
No estoy seguro de que necesites esta función. Abajo tienes una función que se llama `totalColums`, pero quien realmente logra encontrar el valor es esta función.

No estoy seguro además porque si con la función `findCurrentMediaQuery` ya tienes el valor del `mediaQuery` que aplica --ej: (max-width: 500px)--, no necesitas recorrer todo el objeto `breakPoints`, sino que puedes evaluarlo como `breakPoints[findCurrentMediaQuery()]`.

Intenta refactorizar y que la función totalColumns, realmente sea capaz de hallar por sí misma la cantidad total de columnas.

2023-04-20 14:47 UTC, wfercanas requested changes

2023-04-20 14:47 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +          {totalTitleColumns(titles, breakPoints, media).map((title) => (
totalTitleColumns vuelves y lo usas más abajo para renderizar el body. Para no repetir 2 veces la ejecución de la misma función con los mismos parámetros, puedes ejecutar la función por fuera del return 1 vez y usar el resultado 2 veces dentro del return

2023-04-20 14:47 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +  if (numColumns >= 4) return titles.slice(0, numColumns);
En lugar de colocar un "4" hardcodeado, usemos `titles.length`. No siempre serán 4 columnas.

2023-04-20 14:47 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +  if (numColumns >= 4) return titles.slice(0, numColumns);
Si se cumple la condición de `numColumns >= titles.length`, no hace falta que hagas una operación `.slice()` sobre titles. Al ser numColumns mayor que el length, te va a devolver titles completo.

2023-04-20 14:47 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +  const numColRemove = columnTitles.length - numColumns;
Esta comparación con el `length` ya la estás haciendo implícitamente en totalTitleColumns, sólo que allá pusiste el 4 directo y no el length.

Te sugiero que dejes en `totalTitleColumns` la comparación para saber si retornas titles completo.

2023-04-20 14:47 UTC, wfercanas commented on src/components/data/Table/interface.jsx
> +  columnTitles.sort((a, b) => a.priority - b.priority);
Me parece que esta parte hacia abajo está más compleja de lo necesario. Por ejemplo:
1. Digamos que numColumns es 2.
2. Según acordamos, priority tiene que arrancar en 0 e ir progresando de 1 en 1.
3. Entonces, máximo vas a incluir las columnas con `priority = numColumns - 1` (es decir, para dos columnas usas priority 0 y 1).
4. Así que puedes hacer un filter de titles (no necesitas copiar [...titles] en columnTitles) y extraer sólo los titles que cumplan con el priority válido.
5. Ese array es el que puede devolver priorityColumns

2023-04-20 19:21 UTC, wfercanas requested changes
La historia de la tabla no funciona correctamente en el responsive

2023-04-21 16:25 UTC, wfercanas approved these changes

2023-04-21 16:27 UTC, merged