jg/87/Refactor-Input-Component
selsa-inube/linpar pull request #122
Opened 2023-03-03 23:22 UTC by novadeveloper14

2023-03-06 14:32 UTC, CristianRojas-47 approved these changes
La actividad cumple con los requerimientos solicitados.

2023-03-06 20:42 UTC, wfercanas requested changes

2023-03-06 20:42 UTC, wfercanas commented on src/components/inputs/Input/styles.js
> +    props.iconAfter ? "1fr auto" : props.iconBefore ? "auto 1fr" : "auto"};
No anidemos estas ternarias, mejor crear una función por fuera para retornar el valor correcto según el caso.

2023-03-06 20:42 UTC, wfercanas commented on src/components/inputs/Input/styles.js
> +    ${(props) =>
No anidemos ternarias

2023-03-06 20:42 UTC, wfercanas commented on src/components/inputs/Input/styles.js
> +  &:disabled {
Faltaría una historia para el disabled  o que por lo menos esté en los args de las historias existentes para poder probar.

2023-03-06 20:42 UTC, wfercanas commented on src/components/inputs/Input/styles.js
> +    aling-content: center;
Está mal escrito, es `align`.
Ahora, si es flex, quizá sea `align-items` y no `align-context`

2023-03-06 22:14 UTC, wfercanas requested changes

2023-03-06 22:14 UTC, wfercanas commented on src/components/inputs/Input/styles.js
> +function getGridTemplateColumns(props) {
En esta función estamos obligando casi a que un Input tenga sólo o iconBefore o iconAfter, pero no los dos.
Realmente no deberían ser excluyentes, por lo que hay que construir la función para contemplar ese escenario.

Nota: Si por dentro estamos aplicando el uso de `return`, sobre usar `else if`, puede ser un if tras otro, cada uno con su `return`.

2023-03-06 22:14 UTC, wfercanas commented on src/components/inputs/Input/styles.js
> +  return `${borderWidth} solid ${borderColor}`;
Es preferible desacoplar la `propiedad` border y usar `border-width`, `border-style` y `border-color`. Cada propiedad con su propia forma de deducir el valor que corresponde.

2023-03-07 14:31 UTC, wfercanas approved these changes

2023-03-07 14:32 UTC, merged