feat(sectionMessage): creation sectionMessage component
selsa-inube/linpar pull request #123
Opened 2023-03-06 19:07 UTC by CristianRojas-47

2023-03-06 20:41 UTC, ANGIECATHERINEP approved these changes
los cambios requeridos fueron realizados y funciona correctamente

2023-03-06 22:28 UTC, wfercanas requested changes

2023-03-06 22:28 UTC, wfercanas commented on src/components/feedback/SectionMessage/index.jsx
> +  const { icon, title, description, aspect } = props;
En el diseño del componente acordamos usar una prop `state`, no `aspect`. De hecho conviene hablar con Leonardo porque en figma está como type.
Creo que Leonardo está estandarizando estas variantes como `appearance`. Acuerden algo ajustemos el código y el figma.

2023-03-06 22:28 UTC, wfercanas commented on src/components/feedback/SectionMessage/index.jsx
> +      <StyledText>
Este componente es un contenedor y no un texto, por lo que no debería llamarse `StyledText`

2023-03-06 22:28 UTC, wfercanas commented on src/components/feedback/SectionMessage/index.jsx
> +        <StyledTitle>
Este componente es un contenedor y no un título, por lo que no debería llamarse `StyledTitle`. Además está asumiendo la tarea de definir un flex y para eso tenemos el componente `<Stack />`

2023-03-07 20:04 UTC, wfercanas approved these changes

2023-03-07 20:04 UTC, merged