feat(usersPage): create users page without table component
selsa-inube/linpar pull request #127
Opened 2023-03-10 23:17 UTC by CristianRojas-47

2023-03-13 16:05 UTC, novadeveloper14 requested changes
El desarrollo de el componente es correcto y acorde a el diseño, realizar el cambio mencionado.

2023-03-13 16:05 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/styles.js
> +  display: flex;
Podemos dejar solo el padding, para controlar este gap podemos simplemente implementar todo el componente entero en un stack y darle de spacing={48}

2023-03-13 20:38 UTC, novadeveloper14 reviewed
El desarrollo de le componente es correcto y cumple con los requerimientos.

2023-03-14 01:39 UTC, wfercanas requested changes

2023-03-14 01:39 UTC, wfercanas commented on src/pages/privileges/outlets/users/index.jsx
> +          <StyledInputsContainer>
Esto podría ser un `<Stack />`

2023-03-17 04:04 UTC, novadeveloper14 reviewed
Las modificaciones del componente fueron realizadas correctamente y cumplen los requerimientos de la RFC.

2023-03-17 15:27 UTC, wfercanas requested changes

2023-03-17 15:27 UTC, wfercanas commented on src/pages/privileges/outlets/users/styles.js
Cuando pasamos al rango de los 300px en el dispositivo, el ícono de `...` se aplasta y comprime contra el input.

Hay que buscar la manera de que el input ceda espacio para que el ícono no pierda su tamaño.

2023-03-17 17:49 UTC, wfercanas approved these changes

2023-03-17 17:50 UTC, merged