jg/95/create-page-form-to-invite-users
selsa-inube/linpar pull request #128
Opened 2023-03-13 15:40 UTC by novadeveloper14

2023-03-13 20:08 UTC, CristianRojas-47 requested changes
El desarrollo de la actividad es correcto, solo se debe ajustar la información que recibe el componente <SectionMessage/>, ya que esta información es obtenida a través de un mock de datos correspondiente a los posibles mensajes.

2023-03-13 20:08 UTC, CristianRojas-47 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +        />
Esta información la traería desde un mock de datos que se debía crear.

2023-03-13 22:31 UTC, CristianRojas-47 approved these changes
El desarrollo es correcto y cumple con los requerimientos.

2023-03-14 02:12 UTC, wfercanas requested changes

2023-03-14 22:04 UTC, CristianRojas-47 approved these changes
El desarrollo es correcto, cumple con los requerimientos solicitados.

2023-03-15 02:37 UTC, wfercanas requested changes

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +      [key]: { value: value, valid: validity },
No es necesario pasarle al setter del state una función que retorne un objeto cuando podría pasarle el objeto directamente. Especialmente porque la función no hace ninguna transformación.

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +    const loadingTimeout = 2500;
Saquemos estas constantes de aquí. Como las estamos usando a modo de simular un timeout, son apenas de maquillaje. Dejamos el handleSubmit un poco más limpio (ya que esta función al final sí va a quedar).

Puede dejar estas variables en mayus: SHOW_MESSAGE_TIMEOUT. Así es más fácil diferenciar luego que son parámetros constantes.

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +          description={
El `<SectionMessage />` se supone que quedó definido para que vía description le pasemos solo el string que hay que pintar, nada de JSX.
Si no aparece el mensaje como en los mockups, es problema del `<SectionMessage />` y en otra tarea habrá que hacer el ajuste, pero no debemos forzar el arreglo desde aquí.

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +                ></Input>
Los input se pueden dejar autocerrados: `<Input />`

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +                <Input
A estos input les hace falta la prop `name`. Veo que no la pusimos en el componente `<Input />`. Hay que hacer ese arreglo aquí como un fix.
Cuando un form hace submit, los valores se envían como pareja name=value. Sin name, nos falta la mitad de la tarea.

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +                      !e.target.validity.valid
No es necesario armar un handleInputChange con el evento así de descompuesto en el JSX. Se le puede pasar el evento tal cual al handler y que la función se encargue de extraer de él los valores que necesite.
En el caso del string "inputId", eso se resuelve agregando la prop "name" en `<Input />`, de esa manera se sabe de qué input se está hablando en un onChange usando `event.target.name`

2023-03-15 02:37 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +              <Stack>
Estos `Stack` que envuelven sólo un `Input` no deberían estar aquí. Se supone que el componente viene con todo y Label añadido, luego es el Input el que debería garantizar que ambas cosas vienen bien juntas.

El formulario no debería tener que ajustar el layout interno del componente.

2023-03-15 19:27 UTC, CristianRojas-47 requested changes
Se deben revisar los estilos de los componentes para la medida de mobile.

2023-03-15 19:27 UTC, CristianRojas-47 commented on src/pages/privileges/outlets/users/invite/styles.js
> +`;
El padding es de 16px en todos los lados.

2023-03-15 19:27 UTC, CristianRojas-47 commented on src/pages/privileges/outlets/users/invite/styles.js
Las medidas de los componentes en mobile cambian, por ejemplo el title de PageTitle pasa de titleLarge a TitleMedium. Verificar todos los estilos de los componentes, ya que algunas de sus medidas cambian como en ejemplo anterior.

2023-03-15 21:00 UTC, CristianRojas-47 approved these changes
El desarrollo es correcto, cumple con los requerimientos solicitados.

2023-03-16 04:20 UTC, wfercanas requested changes

2023-03-16 04:20 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +    setSubmitted(event);
Realmente el handleClick del submit button no le está pasando el event a handleClickSubmit, sino que le está pasando true siempre.
Aparte de eso, no sólo se está disparando el evento onClick del button, sino también el evento onSubmit del form. Entonces, más bien agregue el setSubmitted(true) cuando empieza el handleSubmit y se ahorra:
1. Poner una función en el handleClick del submit button
2. Crear una función handleClickSubmit sólo para esto
3. Evitar la confusión de creer que al handleClickSubmit se le está pasando el evento, cuando realmente se le pasa un true

2023-03-16 04:20 UTC, wfercanas commented on src/mocks/apps/messagesCards.mock.js
> +const messageInvitationSent = [
En lugar de tener un array con objetos por dentro, es mejor tener un objeto con objetos dentro.

Esto porque si yo quiero acceder al mensaje de éxito puedo buscar en messageInvitationSent[success] y no tengo que saber y hard-codear luego que la respuesta de éxito está en messageInvitationSent[0] o en un futuro que el mensaje de error para cuando ocurre la situación X está en messageInvitationSent[7].

Entonces, quedaría algo como:
```js
const messageInvitationSent = {
  success: {
    id: 1,
    // ...
  },
  failed: {
    //...
  }
}
```

2023-03-16 04:20 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +  function renderMessages() {
Con el refactor de **messageInvitationSent**, esta función debería ser refactorizada también para que no gire en torno a unos índices sino al tipo de mensaje que hay que escribir.

2023-03-16 04:20 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/styles.js
> +const StyledMessage = styled.div`
Estos estilos debería tenerlos el `<SectionMessage />`, si no los tiene hay que arreglarlos allá, no aquí.
Puede hacer el fix en esta PR.

2023-03-16 22:36 UTC, CristianRojas-47 approved these changes
Los cambios solicitados se realizaron, cumple con los requerimientos planteados.

2023-03-17 22:27 UTC, wfercanas approved these changes

2023-03-17 22:28 UTC, merged