jg/123/button-replacement-for-design-system
selsa-inube/linpar pull request #139
Opened 2023-03-27 17:15 UTC by novadeveloper14

…nent

2023-03-28 14:37 UTC, CristianRojas-47 approved these changes
La actividad cumple los requerimientos solicitados.

2023-03-28 20:30 UTC, wfercanas requested changes

2023-03-28 20:30 UTC, wfercanas commented on src/components/layout/ErrorPage/styles.js
> +
No deberíamos tener que modificar el ancho del botón. Si este toma todo el ancho del div aún cuando no le estamos pasando la prop `isFullWidth = true` entonces hay que hablar con @cmarin001 y ver si se agrega un issue en el design-system.

2023-03-28 20:30 UTC, wfercanas commented on src/pages/login/outlets/Clients/interface.jsx
> +          handleClick={handleSubmit}
Aquí no hay que pasarle un handleSubmit al button, porque entonces la función se puede estar disparando doble, tanto con el evento onSubmit como con el onClick.

Si estamos haciendo esto creo que es porque el handleClick está required. Este es un buen escenario para discutir con @cmarin001 . Creo que entonces no debería ser required.

2023-03-28 20:30 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +              handleClick={handleSubmit}
Lo mismo que en el caso anterior, no amarremos el click con el submit, podemos estar ejecutando x2 el handleSubmit.

2023-03-28 20:30 UTC, wfercanas commented on src/components/layout/ErrorPage/index.jsx
> +import { Button } from "@inube/design-system/dist/components/inputs/Button";
En todos los casos deberíamos hacer sólo "@inube/design-system" sin más. Si no funciona hay que socializarlo con @cmarin001 .

**Nota: dado un problema que tuvimos con la exportación de componentes, esto debería funcionar normal desde la v0.7.0 de la librería**

2023-04-13 20:54 UTC, Sebas3245 approved these changes

2023-04-13 22:19 UTC, wfercanas approved these changes

2023-04-13 22:28 UTC, merged