feat(spinner-designSystem): delete spinner component and use the spin…
selsa-inube/linpar pull request #142
Opened 2023-03-28 19:36 UTC by CristianRojas-47

…ner from design system

2023-03-28 20:11 UTC, ANGIECATHERINEP approved these changes
los requerimientos fueron realizados correctamente

2023-03-30 03:42 UTC, wfercanas requested changes

2023-03-30 03:42 UTC, wfercanas commented on src/pages/login/outlets/CheckingCredentials/interface.jsx
> +        <Spinner size="large" appearance="blue" isTransparent={false} />
A partir de la versión 0.9.0 del design-system, ya no son requeridas las props que tienen valor por default

Una vez instale esa versión en main, actualice esta rama, haga npm install y use el <Spinner /> sin tener que pasar las props que aquí le eran obligatorias aunque fueran las default.

2023-03-30 03:42 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +            ></Button>
Dejó el botón sin children

2023-03-31 02:47 UTC, merged