jg/142/mockup-Assisted-Component
selsa-inube/linpar pull request #147
Opened 2023-04-04 15:12 UTC by novadeveloper14

2023-04-04 20:37 UTC, ANGIECATHERINEP requested changes

2023-04-04 20:37 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/styles.js
> +    & button {
puedes utilizar el useMediaQuery de la librería design-system

2023-04-04 20:37 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/StepIndicator/styles.js
> +  }
se debería usar el color token  sys.status.inProgress ,  según lo especificado en el requerimiento

2023-04-04 20:37 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/StepIndicator/index.jsx
> +      return "light";
Pienso que puedes colocar if  en vez de else if, como lo hiciste por ejemplo en las funciones de los estilos de este componente

2023-04-04 20:37 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/index.jsx
> +    <Stack direction="column" gap="8px" alignItems="center">
deberías separar el código en los archivos index e interface

2023-04-04 20:37 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/StepIndicator/styles.js
> +};
se debería usar el color token sys.status.pending cuando es false, según lo especificado en el requerimiento

2023-04-05 16:22 UTC, ANGIECATHERINEP approved these changes
los cambios fueron realizados correctamente

2023-04-11 15:39 UTC, Sebas3245 requested changes
Hay que hacer cambios con respecto a propiedades que pueden no ser necesarias al tener otras propiedades las cuales nos proveen los datos necesarios, tambien verificar las propiedades que se presentan en el storybook porque algunas no coinciden con las del componente

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepBar/stories/StepBar.stories.js
> +  stepName: "Text",
El nombre del paso no se necesita en StepBar

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepIndicator/index.jsx
> +    isFirstStep,
Con la propiedad del paso actual podemos obtener este dato

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepIndicator/index.jsx
> +    isLastStep,
Con la propiedad isVerification podemos obtener este dato

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepIndicator/index.jsx
> +    id,
El paso actual es el mismo id, por lo tanto id no seria necesario

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/index.jsx
> +  const isFirstStep = steps[0].id;
Teniendo en cuenta los comentarios anteriores esta variable no seria necesaria

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/index.jsx
> +  const isLastStep = steps[steps.length - 1].id;
Teniendo en cuenta los comentarios anteriores esta variable no seria necesaria

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.jsx
> +    isFirstStep,
Teniendo en cuenta los comentarios anteriores esta propiedad no seria necesaria

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.jsx
> +    isLastStep,
Teniendo en cuenta los comentarios anteriores esta propiedad no seria necesaria

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/stories/Assisted.stories.js
> +Default.args = {
Revisar que las propiedades si sean las mismas que en el index

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepIndicator/stories/StepIndicator.stories.js
> +isVerification.args = {
Revisar que las propiedades si sean las mismas que en el index

2023-04-11 15:39 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepBar/stories/StepBar.stories.js
> +isActive.args = {
Revisar que las propiedades si sean las mismas que en el index

2023-04-14 16:27 UTC, novadeveloper14 commented on src/components/feedback/Assisted/StepIndicator/index.jsx
> +    id,
El stepActual desde la interface de assisted llega como un valor booleano que determina si ese paso es el que actualmente está seleccionado a través de los botones, no es el ID como tal.

2023-04-14 17:27 UTC, novadeveloper14 commented on src/components/feedback/Assisted/index.jsx
> +  const isFirstStep = steps[0].id;
Teniendo en cuenta que el stepActual está llegando como un valor booleano, no podemos determinar el primer paso dentro del componente stepIndicator si no llega desde la prop isFirstStep. Este no es el caso con isVerification, ya que este es un valor booleano que ya desde la interface de Assisted nos dice si es el último paso o no. Por eso mismo, creo que solo es necesaria la eliminación de isLastStep dentro de stepIndicator.

2023-04-14 17:34 UTC, novadeveloper14 commented on src/components/feedback/Assisted/index.jsx
> +  const isLastStep = steps[steps.length - 1].id;
En interface, isVerification utiliza esta constante para determinar el último paso, por lo que es necesario almacenarlo y pasarlo como prop.

2023-04-14 19:11 UTC, Sebas3245 commented on src/components/feedback/Assisted/index.jsx
> +  const isFirstStep = steps[0].id;
Entonces en este caso si se va a dejar la propiedad ID con esta debería poderse validar si es igual a 1 y con eso ya tendríamos el primer paso, para poder eliminar la propiedad isFirstStep y así no renderizar el componente nuevamente con un dato que podemos obtener de otra propiedad

2023-04-17 13:37 UTC, novadeveloper14 commented on src/components/feedback/Assisted/index.jsx
> +  const isFirstStep = steps[0].id;
Creo que es más conveniente utilizar isFirstStep en lugar de buscar el id = 1 directamente en el array de pasos (steps), ya que esto asegura que estemos trabajando con el paso correcto que queremos modificar al acceder directamente a la posición 0 del array. buscando el id = 1 se corre el riesgo de que el primer paso no tenga necesariamente el ID deseado, y por lo tanto, no se apliquen los cambios a ese paso en particular.

Además, si hay varios pasos con el mismo ID, al buscar directamente en el array, se modificarán todos los pasos con ese ID, lo cual puede ser problemático. Al utilizar isFirstStep, podemos garantizar que estamos trabajando con el paso correcto que queremos modificar. que opinas?

2023-04-18 13:22 UTC, Sebas3245 approved these changes

2023-04-19 00:14 UTC, wfercanas requested changes

2023-04-19 00:14 UTC, wfercanas commented on src/components/feedback/Assisted/StepIndicator/index.jsx
> +            {renderStepNumber()}
Aunque aquí dice que hace `renderStepNumber`, no hace solamente eso, también valida si tiene que pintar el ícono check en lugar del número.

Aquí prefiero que separemos ambas cosas:
1. Puede crear un componente que no se exporte de este archivo y que sea sólo para crear el paso de verificación.
2. Dentro del return del StepIndicator, puede usar una ternaria en lugar de ejecutar sólo la función `renderStepNumber()`
3. Como estaríamos creando un componente aparte, habría que pasarle props para controlar sus estilos. Se vería algo así:

```js
<Text>
  {isVerification ? <VerificationStep /> : StepNumber}
</Text>
```

2023-04-26 15:02 UTC, wfercanas requested changes

2023-04-27 21:44 UTC, wfercanas requested changes

2023-04-27 21:44 UTC, wfercanas commented on src/components/feedback/Assisted/StepBar/index.jsx
> +      ></StyledStep>
Se puede autocerrar

2023-04-27 21:44 UTC, wfercanas commented on src/components/feedback/Assisted/StepBar/stories/StepBar.stories.js
> +const withLayout = (Template) => (args) =>
Esta dinámica de embeber el template dentro de otro componente creo que es compleja. Puede usar un decorator para envolver las historias con un container y ese container puede ser un `<Stack />`, no necesita crear un styles.js dentro de stories/

2023-04-27 21:44 UTC, wfercanas commented on src/components/feedback/Assisted/StepBar/stories/styles.js
Este componente no debería ser necesario, para eso está el `<Stack />`

2023-04-27 21:44 UTC, wfercanas commented on src/components/feedback/Assisted/stories/Assisted.stories.js
Creemos las historias en español y con textos que tengan parecido a la realidad. Puede usarse el que está en los mockups

2023-04-27 21:44 UTC, wfercanas commented on src/components/feedback/Assisted/interface.jsx
> +  return (
El cambio entre un Assisted mobile y uno Desktop es muy fuerte, los componentes que se usan son distintos y se salva poco entre una versión y otra a nivel gráfico.
Por lo tanto, aquí es preferible usar dos return que funcionen según si estamos el rango de pantalla que aplique.

```js
if (isAssistedResponsive) {
  return (
    //...
  )
}

return (
  //...
)

2023-05-02 15:58 UTC, wfercanas requested changes

2023-05-03 04:29 UTC, wfercanas approved these changes

2023-05-03 04:29 UTC, merged