jg/149/Update-SectionMessage-Component
selsa-inube/linpar pull request #151
Opened 2023-04-12 07:33 UTC by novadeveloper14

2023-04-12 15:37 UTC, ANGIECATHERINEP requested changes
aparte hace falta el story del componente <ProgressBar/>

2023-04-12 15:37 UTC, ANGIECATHERINEP commented on src/components/feedback/SectionMessage/stories/SectionMessage.stories.js
> +whitFullText.args = {
al ver este story en mobile no se observa la descripción del mensaje

![Captura](https://user-images.githubusercontent.com/88405711/231508790-23738dc7-99a7-4637-bd38-74d7005521c8.PNG)

2023-04-12 16:51 UTC, ANGIECATHERINEP approved these changes
los cambios se realizaron correctamente

2023-04-12 19:54 UTC, wfercanas requested changes

2023-04-12 19:54 UTC, wfercanas commented on src/components/feedback/SectionMessage/index.jsx
> +  const [isHidden, setIsHidden] = useState(false);
Este componente debe de ser llamado por una página en caso de que ésta requiera mostrar alguna información al usuario. Eso implica que el renderizado del SectionMessage es un renderizado condicional a la situación o momento en el que se quiera mostrar esa información.

El hecho de que sea condicional implica que el estado que controla si se muestra o no un `<SectionMessage />` debe de ser conocido por el padre que renderiza el componente. 

Por lo tanto:
1. No es suficiente con que ese estado que controla este hecho esté dentro del SectionMessage, hay que elevarlo hasta el padre.
2. Es probable que el padre deba hacer un renderizado condicional del tipo `{showMessage && <SectionMessage />}`, por lo que usar display:hidden o block no tiene mucho sentido práctico. Quien controla el display en este ejemplo es showMessage, que es conocido por el padre.
3. Quizá lo que sí necesite SectionMessage es recibir una función que permita actualizar el valor de showMessage de true a false.

2023-04-12 19:54 UTC, wfercanas commented on src/components/feedback/SectionMessage/interface.jsx
> +      <StyledMessage>
Este `StyledMessage` se puede cambiar por un `Stack`

2023-04-12 19:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +        duration={messageType === "success" ? 5 : undefined}
Para todos los casos deje los 10s

2023-04-14 22:45 UTC, wfercanas requested changes

2023-04-14 22:45 UTC, wfercanas commented on src/components/feedback/SectionMessage/index.jsx
> +    handleHideSectionMessage,
Renombremos esta función como `closeSectionMessage` de tal forma que sea claro que implica cerrar el componente y no sólo que se esconde.

2023-04-14 22:45 UTC, wfercanas commented on src/components/feedback/ProgressBar/index.jsx
> +    />
Un componente que utilice este `<ProgressBar />`, puede estar interesado en que se le avise cuando la animación termina. En el caso del `<SectionMessage />`, este componente podría estar interesado en saber cuándo termina la animación para autocerrarse.

Para lograr algo así, este `<ProgressBar />` podría recibir una función cualquiera y ejecutarla cuando la animación termina, de esa manera el padre consigue ejecutar cualquier acción deseada en ese instante.

Más en concreto, `<ProgressBar />` puede tener una prop adicional que se llame `handleAnimationEnd`, donde recibe cualquier función. Luego, podemos agregar un evento al `<StyledProgressBar />`, el evento `onAnimationEnd` y a ese evento relacionarle la función que recibimos por props.

**Tendríamos entonces que**:
1. `<SectionMessage />` le pasa la función `closeSectionMessage` a `<ProgressBar />` usando la prop `handleAnimationEnd`.
2. `<ProgressBar />` recibe esa prop y la usa creando el evento `onAnimationEnd={handleAnimationEnd}`

2023-04-14 22:45 UTC, wfercanas commented on src/components/feedback/SectionMessage/styles.js
> +const StyledSectionMessage = styled.div`
En mobile, la tarjeta se está pegando al borde derecho de la pantalla.

2023-04-14 22:45 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +  const [started, setStarted] = useState(false);
No hace falta crear estados para controla el pause e inicio de la animación. Ya dejé otro comentario para gestionar el manejo de la animación.
Al final del día, este componente decide cuándo prende el `SectionMessage` y al pasarle la función `closeSectionMessage` al componente por props, le entrega la posibilidad de que éste gestione cómo y cuándo se cierra.

En la práctica hay 2 formas de obtener ese cierre: o el usuario usa el botón X, o la animación termina. El uno es un evento `onclick` y el otro es un evento `onAnimationEnd`.

A Invite no le importa nada de lo anterior. Tampoco tiene por qué administrar, controlar o anticipar lo que sucede puertas para adentro del `SectionMessage`. La página cumple con pasarle la función que actualiza el estado y ya.

2023-04-14 22:49 UTC, wfercanas requested changes
Hay 2 errores en la consola.

2023-04-18 16:32 UTC, wfercanas requested changes

2023-04-18 16:32 UTC, wfercanas commented on src/components/layout/AppPage/styles.js
> -  overflow-y: scroll;
Por ahora digamos que está bien hacer este cambio. Sin embargo, revise el media query de invite/styles.js, ahí tiene un height de 120vh, lo que hace que la altura del formulario sea innecesariamente grande.

No creo que valga la pena hacer ese media query para el `height`.

2023-04-18 16:32 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
1. Si llena el formulario bien, para que no quede inválido, se abre el SectionMessage verde.
2. Cuando se abre ese message, uno puede cerrar el message con la X.
3. Unos segundos después, de la nada, se abre un nuevo message verde.

2023-04-18 16:32 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +  const SHOW_MESSAGE_TIMEOUT = 10000;
Dado que ya definimos un default de 10s en el ProgressBar, aquí podemos quitar este parámetro y quitarlo también de las props.

2023-04-20 16:19 UTC, wfercanas approved these changes

2023-04-20 16:20 UTC, merged