jg/181/Develop-DecisionModal-Component
selsa-inube/linpar pull request #153
Opened 2023-04-21 20:15 UTC by novadeveloper14

2023-04-25 20:59 UTC, ANGIECATHERINEP requested changes

2023-04-25 20:59 UTC, ANGIECATHERINEP commented on src/components/feedback/DecisionModal/styles.js
> +  width: 487px;
según lo hablado con Leonardo el modal debería tener max-width: 500px y min-width:400px cuando esta en desktop y tablet. y max-width: 328px , min-width: 300px  y margin de 16px cuando esta en mobile

2023-04-26 17:54 UTC, ANGIECATHERINEP approved these changes
los cambios fueron realizados y funciona correctamente

2023-05-02 15:01 UTC, wfercanas requested changes

2023-05-02 15:01 UTC, wfercanas commented on src/pages/privileges/outlets/users/index.jsx
> +        createPortal(renderModal(), document.getElementById("decision"))}
Todavía no hagamos esta implementación, por ahora sólo necesitamos tener el componente desarrollado. En otro task inyectamos el componente en esta página.

2023-05-03 04:25 UTC, wfercanas requested changes
Hay conflictos en el PR. Como le sugerí más temprano, mejor haber hecho el pull de main y luego los ajustes que hacían falta.

Como los ajustes son en outlets/users no debería haber problema con traer lo de main y arreglar el pedazo del ícono de los tres puntos.

2023-05-03 14:39 UTC, wfercanas approved these changes

2023-05-03 14:39 UTC, merged