jg/192/replace-tabs-from-design-system
selsa-inube/linpar pull request #154
Opened 2023-04-24 19:23 UTC by novadeveloper14

2023-04-24 23:50 UTC, ANGIECATHERINEP approved these changes
los cambios requeridos fueron realizados correctamente

2023-04-25 02:59 UTC, wfercanas requested changes

2023-04-25 02:59 UTC, wfercanas commented on src/mocks/apps/privilegesUsers.mock.js
> +    label: "users",
Como aquí se pide el label literal, está quedando con minúscula en la pantalla.

2023-04-25 14:57 UTC, wfercanas approved these changes

2023-04-25 14:58 UTC, merged