jg/189/insert-Table-on-users
selsa-inube/linpar pull request #157
Opened 2023-04-25 17:51 UTC by novadeveloper14

2023-04-25 21:30 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-04-26 03:12 UTC, wfercanas requested changes

2023-04-26 03:12 UTC, wfercanas commented on src/pages/privileges/outlets/users/index.jsx
> +          ></Table>
La tabla se puede autocerrar

2023-04-26 03:12 UTC, wfercanas commented on src/pages/privileges/outlets/users/index.jsx
`<Table />` está exportando dos componentes dentro de un React.Fragment. Esto causa que al insertar ambos componentes en el layout, les está aplicando el gap con el cual se está armando la interfaz de users/

Consecuencia: el componente de paginación está quedando muy abajo de la tabla. Hay que arreglar el componente `<Table />`

2023-04-26 13:55 UTC, wfercanas approved these changes

2023-04-26 13:55 UTC, merged