Ap/187/replace input by text field
selsa-inube/linpar pull request #158
Opened 2023-04-26 17:44 UTC by ANGIECATHERINEP

2023-04-27 19:26 UTC, novadeveloper14 requested changes
Realizar los cambios

2023-04-28 22:01 UTC, wfercanas requested changes

2023-05-02 14:00 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +      handleBlurPhone={handleBlurPhone}
La prop de InviteUI debería ser igual `runValidations={runValidations}`, el `handleBlur` aparece ya es a nivel de `TextField`

2023-05-02 14:03 UTC, wfercanas requested changes

2023-05-02 14:03 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/index.jsx
> +  const runValidations = (event) => {
Deja esta función más arriba, junto a validations, para que se más fácil de leer en secuencia el código.

2023-05-03 04:08 UTC, wfercanas approved these changes

2023-05-03 04:08 UTC, merged