Ap/195/separate mocks from config files
selsa-inube/linpar pull request #164
Opened 2023-05-03 16:34 UTC by ANGIECATHERINEP

2023-05-03 17:35 UTC, Sebas3245 approved these changes

2023-05-04 04:35 UTC, wfercanas requested changes

2023-05-04 04:35 UTC, wfercanas commented on src/components/Header/interface.jsx
> +import { mockAppsConfig } from "../../pages/home/config/apps.config";
Creo que o usamos la palabra mock o usamos la palabra config, pero no las dos porque entonces no se sabe cuál es el alcance del objeto.
En este caso, veo que es apps.config.js el archivo,, así que el objeto que se exporta no debería empezar por mock.

En ese objeto de hecho, seguramente está la lista de apps que están desarrolladas dentro de linpar, así que quizá hasta el nombre del objeto exportado debería ser más diciente de su contenido.

2023-05-04 04:35 UTC, wfercanas commented on src/components/feedback/DecisionModal/config/decisionModalMessages.config.js
> +const mockUsersDecisionModalOptionsConfig = {
Aquí lo mismo, estamos usando tanto `mock` como `config`. 

Ahora, el componente como tal lo pueden usar muchas páginas o componentes, por lo que **cada** página/componente debe definir la configuración que indique cómo es que va a invocar al `<DecisionModal />`. Es decir, el modal ya cumple con exponer unas props para que quien quiera lo utilice, así que cuáles props van en cada caso ya se vuelve un problema del padre que lo invoca.

**Conclusión**: no debe de haber un config dentro del componente, estos config son problema del padre que necesite invocar al modal.

2023-05-04 04:35 UTC, wfercanas commented on src/components/feedback/SectionMessage/config/sectionMessage.config.js
Aquí aplica la misma lógica del comentario sobre el `<DecisionModal />`. Es el padre el que tiene que saber qué props le va a pasar en este caso al `<SectionMessage />`. Esta configuración no va aquí.

2023-05-04 04:35 UTC, wfercanas commented on src/components/feedback/DecisionModal/config/decisionModalMessages.config.js
> +const mockUsersDecisionModalOptionsConfig = {
**Nota**: el día de mañana esta carpeta la vamos a borrar y la vamos a reemplazar por lo que venga en el design-system. No vamos a poder guardar config nuestra dentro del design-system.

2023-05-06 22:29 UTC, wfercanas requested changes

2023-05-06 22:29 UTC, wfercanas commented on src/components/feedback/DecisionModal/stories/config/decisionModalMessages.config.js
En las historias no hace falta crear un /config... como es una historia, ya sabemos que los datos que se muestran ahí son ficticios, por lo que este objeto se puede crear dentro del archivo stories.js

2023-05-06 22:29 UTC, wfercanas commented on src/mocks/apps/dataTable.mock.js
1. Este archivo tiene un contenido claro como mock, pero está almacenado directamente dentro de **/apps**, habría que crear una carpeta **/privileges** y ahí sí guardar el archivo.
2. También conviene cambiar el nombre, porque dataTable no me dice nada sobre la información que hay adentro. Algo más cercano sería **users.mock.js**

2023-05-06 22:29 UTC, wfercanas commented on src/pages/privileges/outlets/config/privileges.config.js
Este archivo muestra el segundo nivel de navegación de la app **/privileges**, por lo que habría que alojarlo dentro de **/privileges/outlets/options**. Ahí se encuentra el index.js para ese menú.

2023-05-06 22:29 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/dataTable.config.js
Este archivo tiene un contenido con un alcance claro, pero creo que habría que cambiar el título del archivo. Algo así como **usersTable.config.js**. Luego vamos a tener que crear **invitationsTable.config.js**

2023-05-06 22:29 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/privilegesUsers.config.js
Yo le cambiaría el nombre a este archivo por **usersTabs.config.js**

2023-05-06 22:29 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/dataTable.config.js
> +const titlesConfig = [
Los nombres de estas variables también deberían quedar con alguna relación a la tabla a la que pertenecen. Esto porque en una página se puede estar cargando más de una tabla y no podemos importar 2 variables con el mismo nombre ("titlesConfig") para dos tablas diferentes.

2023-05-09 14:51 UTC, wfercanas requested changes

2023-05-09 14:51 UTC, wfercanas commented on src/pages/privileges/outlets/users/invite/interface.jsx
> +      usersInvitationsConfig[messageType];
Aquí se está llamando a messageType dentro de usersInvitationsConfig, pero esa variable no existe allá. Como consecuencia, cuando se envía el formulario de **/invite** se rompe la app.

2023-05-09 16:45 UTC, merged