feat(usersPage): add invitation table for users
selsa-inube/linpar pull request #165
Opened 2023-05-03 19:34 UTC by Sebas3245

The table of invitations is added to the users page with the condition that it must appear in its respective tag, also configuration parameters for this table and simulated data are added.

2023-05-03 21:51 UTC, CristianRojas-47 requested changes
Verificar que los Id de los objetos del array "invitationEntriesDataMock" no sean iguales para que el funcionamiento de la tabla sea el correcto.

2023-05-03 21:58 UTC, CristianRojas-47 approved these changes
Cumple con los requerimientos solicitados.

2023-05-04 04:24 UTC, wfercanas requested changes

2023-05-04 04:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/dataTableInvitations.config.js
> +import { BsArrow90DegRight, BsClipboardCheck } from "react-icons/bs";
Usemos íconos de material design solamente "react-icons/md"

2023-05-04 04:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/dataTableInvitations.config.js
> +const invitationBreakpointsConfig = [
Ajustemos los media queries para evitar que se creen 3 renglones en una casilla. Intentaría que no hubiera tampoco 2 renglones, pero bueno, si no se puede por lo menos que sean máximo 2.

2023-05-04 04:24 UTC, wfercanas commented on src/mocks/apps/privileges/clientsInvitations.mock.js
> +    mail: "LGARZON",
Ajustar esto a formato de correo electrónico

2023-05-04 04:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/index.jsx
>    const [isSelected, setIsSelected] = useState(mockPrivilegeUserTabs[0].id);
Este state debería cambiar cuando se apruebe el PR de la separación de config files y mock files. El estado inicial de las tabs es una decisión de configuración, no de mock.

2023-05-09 15:06 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/index.jsx
> +        {isSelected === mockPrivilegeUserTabs[0].id && (
Aca se cambio el switch debido a que necesitamos desmontar totalmente el contenido de cada tab y para esto en React requerimos hacerlo directamente desde el jsx con el operador "&&" y teniendo esto en cuenta, tanto el switch, condicionales y mapas de objetos almacenan la referencia del componente en memoria y no desmontan el componente.

2023-05-09 16:18 UTC, CristianRojas-47 approved these changes
El requerimiento fue realizado correctamente.

2023-05-10 16:52 UTC, wfercanas requested changes

2023-05-10 17:01 UTC, wfercanas requested changes

2023-05-10 17:01 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/dataTableInvitations.config.jsx
Cambiemos en nombre de este archivo a `invitationsTable.config.jsx`

2023-05-10 17:32 UTC, wfercanas approved these changes

2023-05-10 17:32 UTC, merged