Ap/201/mock activation deactivation of user
selsa-inube/linpar pull request #168
Opened 2023-05-09 02:52 UTC by ANGIECATHERINEP

2023-05-09 16:13 UTC, CristianRojas-47 requested changes
Hace falta la implementación del portal en el cual se desplegará el decisionModal.

2023-05-10 14:23 UTC, CristianRojas-47 approved these changes
El requerimiento fue realizado correctamente.

2023-05-10 17:28 UTC, wfercanas requested changes

2023-05-10 17:28 UTC, wfercanas commented on src/pages/privileges/outlets/users/ActivateUserConfig/index.jsx
> +  const [actUsermodal, setActUserModal] = useState(false);
Usemos el nombre largo y con camelCase: `showActivateUserModal`

2023-05-10 17:28 UTC, wfercanas commented on src/pages/privileges/outlets/users/ActivateUserConfig/index.jsx
> +function ActivateUserConfig(props) {
Este componente de react está complejo por dentro, hay lógica, un par de returns de JSX y una función envuelta en un react fragment (<>function xxx()</>).

Te sugiero que:
1. Crees en index.jsx el componente lógico `<ActivateUser>`, el que define los estados que hagan falta y hace return de otro componente que definamos en interface.jsx como `<ActivateUserUI />`.
2. En interface.jsx tenemos entonces el formulario con el switch y el `createPortal(<ActivateUserModal />, decision)`.
3. En ese interface.jsx, por fuera de `<ActivateUserUI />`, crea otro componente llamado `<ActivateUserModal />`, que reciba por props lo que necesite el modal.

2023-05-11 21:03 UTC, wfercanas requested changes

2023-05-11 21:03 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/usersTable.config.jsx
> +    content: (entry) => <ActivateUser entry={entry} id={entry.id} />,
Si aquí paso toda el objeto entry al hacer `entry={entry}`, no pasemos otra prop para pasar un subconjunto de los datos de entry (`id={entry.id}`).

Si pasamos `entry` completo, ya el componente debería obtener todos los datos que necesite de él por su cuenta.

**NOTA**: Además, aquí no deberíamos hablar de entry (lenguaje que habla la tabla), lo que nosotros sabemos que nos va a llegar por aquí es un user, entonces nombremos el parámetro como `user`.

2023-05-15 22:08 UTC, wfercanas requested changes

2023-05-15 22:08 UTC, wfercanas commented on src/pages/privileges/outlets/users/ActivateUser/interface.jsx
> +          ActivateUserModal(active, user, handleCloseModal, onActionConfirm)}
Estas pasando onActionConfirm al modal, para que cuando allá le den click al botón de activar/desactivar ésta se ejecute. Sin embargo, esa misma función se la estas pasando al onSubmit del form.

Por lo tanto, lo que está ocurriendo es más que el modal dispara la función y no el form.

Te sugiero que:
1. Uses un useRef() para seleccionar el form.
2. Con la referencia guardada, puedes ejecutar el submit como `() => ref.current.submit()`
3. Esta arrow funcion la puedes guardar en el handleClick del modal.

Con lo anterior, sí estarías disparando el onActionConfirm del onSubmit.


---
Nota: revisa esta documentación sobre [useRef](https://es.react.dev/reference/react/useRef#manipulating-the-dom-with-a-ref).

2023-05-15 22:09 UTC, wfercanas commented on src/pages/privileges/outlets/users/ActivateUser/interface.jsx
> +      {ActivateUserModal(
Esta función sigue dentro del form

2023-05-19 15:23 UTC, CristianRojas-47 approved these changes
El requerimiento fue realizado correctamente.

2023-05-25 21:41 UTC, wfercanas requested changes

2023-05-25 21:41 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/activateUser.config.jsx
> +const activateUserConfig = {
Renombra por `activateUserModal`

2023-05-25 21:41 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +    </>
Revisa el PR de @Sebas3245 para borrar una invitación. En esta parte del fuente, se controla el estado de `message.show` para determinar si se pinta o no el SectionMessage y se pasan unas props.

2023-05-25 21:41 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +        <ActivateUser user={user} handleActivateUser={handleActivateUser} />
Realicemos la conexión directamente aquí: `handleActivateUser={() => handleActivateUser(user)}`

2023-05-26 16:11 UTC, CristianRojas-47 requested changes
El planteamiento realizado es incorrecto, ya que no se contempla que algunos usuarios, en su inicialización, se encuentren activos. Se recomienda agregar un nuevo atributo llamado "active" a los objetos en el mock de donde se traen los datos de los usuarios. Este atributo debe ser definido por valores booleanos, de manera que al inicializar se comprenda que algunos usuarios se encuentran activos e inactivos.

Se debe eliminar el useState de "users/ActivateUser/index.jsx" y manejar el valor traído del mock desde el useState de "users/tabs/users/index.jsx". Además, se debe añadir el setUsers a este último.

2023-05-26 16:11 UTC, CristianRojas-47 commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +    return !active;
La devolución del valor definido como "!active" se está produciendo tarde. Debería realizarse antes, ya que se está pintando el "messageCard" y posteriormente se está pasando la devolución de este valor.

2023-05-30 19:11 UTC, CristianRojas-47 approved these changes
Los ajustes realizados son correctos.

2023-05-31 15:17 UTC, wfercanas approved these changes

2023-05-31 15:17 UTC, merged