jg/218/mock-delete-linix-user
selsa-inube/linpar pull request #171
Opened 2023-05-10 22:20 UTC by novadeveloper14

2023-05-12 20:37 UTC, ANGIECATHERINEP requested changes

2023-05-12 20:37 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/DeleteUser/interface.jsx
> +        <MdOutlineDelete cursor="pointer" onClick={handleShowModal} />
el atributo curso deberia estar en el archivo styles

2023-05-12 20:37 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/DeleteUser/interface.jsx
> +      {showMessage && DeleteUserMessages(user, closeMessage)}
No se visualiza el sectionMessage

2023-05-12 21:14 UTC, ANGIECATHERINEP requested changes

2023-05-12 21:14 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/DeleteUser/config/deleteUser.config.jsx
deberías colocar este archivo en la carpeta config del componente user

2023-05-15 15:09 UTC, ANGIECATHERINEP requested changes

2023-05-15 15:09 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/config/deleteUser.config.jsx
> +    description: ({ username }) =>
Revisando los mockups en la descripción del modal debería ir el code del usuario y no el username

2023-05-15 15:09 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/config/deleteUser.config.jsx
> +    description: `Hemos eliminado con éxito al usuario.`,
En la descripción del section message debria ir el code del usuario, según mockups

2023-05-19 13:20 UTC, ANGIECATHERINEP requested changes

2023-05-19 13:20 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/tabs/users/DeleteUser/interface.jsx
> +      <form>
Deberías eliminar la etiqueta form

2023-05-19 13:20 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +      content: (entry) => (
Deberias cambiar la palabra entry por user

2023-05-25 21:24 UTC, wfercanas requested changes

2023-05-25 21:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/deleteUser.config.jsx
> +const decisionModalConfig = {
Renombremos como `deleteUserModal`

2023-05-25 21:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/deleteUser.config.jsx
> +const sectionMessageConfig = {
Renombremos como `deleteUserMessages`

2023-05-25 21:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/DeleteUser/index.jsx
> +    ></DeleteUserUI>
Se puede autocerrar

2023-05-25 21:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +        <DeleteUser user={user} handleDeleteUser={handleDeleteUser} />
handleDeleteUser debe borrar directamente el user que también le estamos pasando por props. Aquí estamos delegando en `<DeleteUser>` que una una cosa con la otra.
Mejor pasemos `handleDeleteUser={() => deleteUser(user)}` para hacer esta conexión desde aquí.

2023-05-25 21:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +  const handleDeleteUser = (user) => {
Renombremos como `deleteUser()`

2023-05-25 21:24 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/DeleteUser/index.jsx
> +  };
Esta función puede estar sobrando. Ya en la configuración de la action hicimos la conexión entre la función y el user, por lo que podemos pasarle directamente el handleDeleteUser a `<DeleteUserUI>`

2023-05-26 14:53 UTC, wfercanas approved these changes

2023-05-26 14:54 UTC, merged