feat(resendInvitation): create resendInvitation component
selsa-inube/linpar pull request #173
Opened 2023-05-12 17:56 UTC by ANGIECATHERINEP

2023-05-12 21:27 UTC, CristianRojas-47 approved these changes
El requerimiento fue realizado correctamente.

2023-05-16 15:54 UTC, wfercanas requested changes

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/ResendInvitation/index.jsx
Mueve la carpeta ResendInvitation/ a users/tabs/ResendInvitation

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/resendInvitationUser.config.jsx
> +const resendInvitationUserConfig = {
Renombremos por `resendInvitationModal`

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/resendInvitationUser.config.jsx
> +const messageResendInvUserConfig = {
Renombremos por `resendInvitationMessages`

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/invitationsTable.config.jsx
>  const invitationActionsConfig = [
Renombremos por `invitationsTableActions`.

De paso abajo renombremos por `invitationsTableTitles` e `invitationsTableBreakpoints`

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/ResendInvitation/index.jsx
> +  const handleToggleModal = () => {
Renombremos por `toggleModal`

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/ResendInvitation/index.jsx
> +  const handleToggleMessage = () => {
Renombremos por `toggleSectionMessage`

2023-05-16 15:54 UTC, wfercanas commented on src/components/feedback/DecisionModal/index.jsx
> +  const handleButtonClick = () => {
Renombremos por `handleConfirmationClick`

2023-05-16 15:54 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/resendInvitationUser.config.jsx
> +  invitation: {
Si este objeto lo llamamos `resendInvitationModal`, no vamos a tener más llaves dentro del objeto que la llave "invitation", lo cual sería algo innecesario.

Podemos pasar directamente el objeto que ahora mismo tiene `invitation` sin crear esta llave.

2023-05-23 13:37 UTC, CristianRojas-47 approved these changes
El desarrollo es correcto de acuerdo a lo indicado en la reunión.

2023-05-25 17:26 UTC, wfercanas requested changes

2023-05-25 17:26 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +      content: (user) => (
Aquí debería venir `invitation` en lugar de `user`, no? La invitation es el entry que está usando la tabla cuando ejecute esta función.

2023-05-25 17:26 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +          handleResendInvitation={handleResendInvitation}
Aquí podemos pasarle de una vez la invitación a la función y no esperar que dentro de `<ResendInvitation>` le pasemos esa información por props. Quedaría `handleResendInvitation={() => handleResendInvitation(invitation)}`

2023-05-25 17:26 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +  const [invitations, setInvitations] = useState(invitationEntriesDataMock);
Como no vas a modificar el estado, puedes hacer sólo `[invitations] = useState()`

2023-05-25 17:26 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +  const handleResendInvitation = (invitation) => {
Me dan ganas de renombrar esta función como `resendInvitation`. Si te parece bien, realiza el cambio.

2023-05-25 20:32 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +  const handleResendInvitation = (invitation) => {
No renombre la función porque quedaría muy parecido al que tiene el componente <ResendInvitation />

2023-05-25 20:48 UTC, wfercanas approved these changes

2023-05-25 20:49 UTC, merged