Sl/222/mock delete invitation
selsa-inube/linpar pull request #174
Opened 2023-05-12 22:18 UTC by Sebas3245

Components and functionalities have been added to achieve the removal of an invitation within the actions of the invitation table.

2023-05-12 23:22 UTC, novadeveloper14 requested changes
Realizar los cambios

2023-05-12 23:22 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +    <SectionMessage
Falta hacer aparecer el SectionMessage para despues que se elimina una invitacion

2023-05-12 23:22 UTC, novadeveloper14 commented on src/mocks/apps/privileges/invitations.mock.jsx
> +  appearance: "remove",
el color del botón del Modal sigue siendo azul (por defecto).  hay que hacer que sea rojo para ir acorde a los diseños

2023-05-12 23:22 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +        <DecisionModal
Podemos hacer algo parecido a lo que se hizo con el SectionMessage, creando un componente externo y pasándole las props

2023-05-12 23:22 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +export default function DeleteInvitationUI(props) {
dejemos la forma típica de exportación de componentes que hemos estado usando  `export { DeleteInvitationUI };`

2023-05-12 23:56 UTC, novadeveloper14 requested changes

2023-05-12 23:56 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +      {showModal && (
Todo componente que no sea parte integral del formulario, es mejor que esté por fuera. Puedes usar un fragment y por dentro colocar tanto el form como la evaluación sobre si se pinta o no el Modal o el SectionMessage.

2023-05-13 00:44 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +    <SectionMessage
El SectionMessage esta apareciendo, en la funcion handleRemoveInvitation de DeleteInvitation usa el toggleMessage

2023-05-13 00:47 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +        <DecisionModal
El SectionMesageUI se creo con el fin de poder separar las declaraciones props similares del DecisionModal al estar ya separadas no creo que sea tan necesario separar tambien el DecisionModal, tambien teniendo en cuenta que la interfaz no crecera mas ya que ese seria todo el alcance en cuanto a interfaz para ese DeleteInvitation

2023-05-14 00:31 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/interface.jsx
> +    <SectionMessage
entiendo que el SectionMessage se está ejecutando en la funcion handleRemoveInvitation pero al momento que la fila se elimina, se elimina tambien el componente DeleteInvitation por lo que el sectionMessage no se muestra después que el Modal deja de aparecer en pantalla y se elimina la fila 

![image](https://github.com/selsa-inube/linpar/assets/87447257/5fe41b98-10a9-4aee-9798-1cdae41871c1)

2023-05-16 17:09 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/deleteInvitation/index.jsx
> +      new Event("submit", { cancelable: true, bubbles: true })
Se realizo de esta manera disparando una instancia de evento debido a que el comportamiento de ref.current.submit() no era el esperado, siendo más específicos no llamaba a la función asignada en el onSubmit, esto se debe a que a partir de React 17 hay que añadir propiedades cancelable y bubbles al evento
[Changes to Event Delegation](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation)
Una guía sobre la función de estas propiedades seria la siguiente:
[dispatch events](https://javascript.info/dispatch-events)

2023-05-19 22:21 UTC, novadeveloper14 approved these changes
los cambios fueron realizados acorde al design y cumple con todos los requerimientos.

2023-05-25 17:09 UTC, wfercanas requested changes

2023-05-25 17:09 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +        <DeleteInvitation invitation={entry} handleDelete={handleDelete} />
La función handleDelete recibe como parámetro una invitación. Esa invitación no la recibe aquí, sino que dentro de DeleteInvitation hay que pasársela usando la prop invitation que se está recibiendo también.

Como aquí la relación es directa entre la función y esa invitación(1:1), podríamos hacer explícita la relación pasando la prop handleDelete ya con el amarre hecho: `handleDelete={() => handleDelete(invitation)}`

2023-05-25 17:09 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +  const handleDelete = (invitation) => {
Me dan ganas de renombrar esta función como `deleteInvitation`, si está de acuerdo haga el cambio.

2023-05-25 17:09 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/interface.jsx
> +      </form>
Refactoricemos para no usar el `form`, ya con lo que fuimos resolviendo en la última sesión se notó que eso agrega una complejidad que para este caso parece innecesaria. Cuando el usuario haga click en el botón de Delete, ya tenemos la función handleDelete donde vamos a incluir el fetch al backend, entonces no hace falta ahora sumarle un handleSubmit a eso o meter el preventDefault de forma algo forzada.

Lo anterior implica también revisar el uso de useRef y el disparador de un evento "submit".

2023-05-25 17:16 UTC, wfercanas requested changes

2023-05-25 17:16 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/invitationsTable.config.jsx
> +const deleteInvitationUserDecisionConfig = {
Renombremos como `deleteInvitationModal`

2023-05-25 17:16 UTC, wfercanas commented on src/pages/privileges/outlets/users/config/invitationsTable.config.jsx
> +const deleteInvitationUserMessageConfig = {
Renombremos como `deleteInvitationMessages`

2023-05-25 20:42 UTC, wfercanas requested changes

2023-05-25 20:42 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/index.jsx
> +  };
El evento lo estamos recibiendo pero no estamos haciendo nada con él. Podríamos prescindir de la función handleRemoveInvitation por ahora y pasar directamente a `DeleteInvitationUI` la función `handleDelete`

2023-05-26 14:47 UTC, wfercanas approved these changes

2023-05-26 14:47 UTC, merged