feat(pathAliases): migrate the imports defined for src and mocks
selsa-inube/linpar pull request #181
Opened 2023-05-24 22:42 UTC by CristianRojas-47

2023-05-25 15:21 UTC, novadeveloper14 approved these changes
la implementación fue realizada correctamente.

2023-05-26 19:52 UTC, wfercanas requested changes

2023-05-26 19:52 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +import { Table } from "@src/components/data/Table";
Este dejemoslo como estaba, porque luego hay otro alias para @components.

2023-05-26 19:52 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/users/index.jsx
> +import { Table } from "@src/components/data/Table";
Este también dejemoslo como estaba para luego usar @components

2023-05-26 20:41 UTC, wfercanas approved these changes

2023-05-26 20:42 UTC, merged