jg/254/access complete invitation assisted
selsa-inube/linpar pull request #182
Opened 2023-05-25 02:10 UTC by novadeveloper14

2023-05-25 16:50 UTC, ANGIECATHERINEP requested changes

2023-05-25 16:50 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/config/invitationsTable.config.jsx
> +    content: (entry) => <CompleteInvitation user={entry} />,
se podría cambiar la palabra entry por user

2023-05-25 16:50 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/tabs/invitations/complete-invitation/styles.js
> +      props.status == "Sent"
se debería colocar la igualdad estricta (===)

2023-05-25 16:50 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/tabs/invitations/complete-invitation/styles.js
> +    cursor: ${(props) => (props.status == "Sent" ? "not-allowed" : "pointer")};
se debería colocar la igualdad estricta (===)

2023-05-25 16:50 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/complete-register/index.jsx
> +    Identificación: foundEntry?.userID || "",
este tipo de validación permite que el id que viene del routes (en la url )  se modifique 
![image](https://github.com/selsa-inube/linpar/assets/88405711/5eeb21fc-12be-4221-b5d8-68c2bedec1af)

Tengo la duda si debe realizar de esta manera

2023-05-26 19:45 UTC, wfercanas requested changes

2023-05-26 19:45 UTC, wfercanas commented on src/components/feedback/Assisted/index.jsx
Sería bueno que el Assisted tuviera por ahí un max-width. Mi pantalla es de aprox 2000px y queda ya muy desparramado el componente.

2023-05-26 19:45 UTC, wfercanas commented on src/pages/privileges/outlets/users/complete-register/index.jsx
> +    (invitation) => invitation.id == id
Reemplazar por una comparación estricta `===`

2023-05-26 19:45 UTC, wfercanas commented on src/routes/privileges.jsx
> +          path="users/complete-register/:id"
Cambiemos `:id` por `:invitation-id`

2023-05-26 19:45 UTC, wfercanas commented on src/routes/privileges.jsx
> +          element={<CompleteRegister />}
Cambiemos el componente por `CompleteInvitation` pues justo estamos en la tabla de invitaciones.

2023-05-26 19:45 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/index.jsx
> +      content: (invitation) => <CompleteInvitation invitation={invitation} />,
Este `CompleteInvitation`, cambiémoslo por `CompleteInvitationLink`

2023-05-26 19:45 UTC, wfercanas commented on src/pages/privileges/outlets/users/complete-register/index.jsx
> +  const foundEntry = invitationEntriesDataMock.find(
Cambiemos foundEntry por `invitation`. No importa que se parezca a lo que está dentro del callback.
En un futuro aquí lo que haremos será consumir un endpoint para consultar invitaciones por id y el backend nos devolverá sólo la invitación que pedimos.

2023-05-26 19:45 UTC, wfercanas commented on src/pages/privileges/outlets/users/complete-register/index.jsx
> +  const smallScreen = useMediaQuery("(max-width: 580px)");
Esta es una variable que funciona para armar layouts, por lo que no la necesita en la lógica del index y más bien la puede crear directamente en interface.

2023-05-26 19:45 UTC, wfercanas commented on src/pages/privileges/outlets/users/complete-register/interface.jsx
> +          <Stack justifyContent="space-between" alignItems="center" gap="49px">
Los dos componentes hijos de este stack en algunos breakpoints están quedando como muy pegados, no se ven tan bien. Ya al final queda bien cuando terminamos en mobile, pero en el intermedio hay layouts extraños.

Es probable que aquí le convenga usar `useMediaQueries` y con múltiples breakpoints a veces muestre la SubjectCard completa y a veces sólo el pin. La idea es que el PageTitle no se vuelva una cosa muy vertical, sino que el título sea a 1 renglón y la descripción máximo a 2.

2023-05-29 17:09 UTC, wfercanas requested changes
1. Tiene 2 conflictos en la rama. Actualice con lo último de main.
2. Cuando se abre el InfoModal del SubjectCard, hay un error con el readOnly. Revise y evalúe si hay que hablar con design-system para crear una issue

2023-05-29 21:01 UTC, wfercanas requested changes

2023-05-29 21:01 UTC, wfercanas commented on src/pages/privileges/outlets/users/tabs/invitations/complete-invitation-link/index.jsx
Dentro de tabs/invitations/ la carpeta debería ser `CompleteInvitationLink` ya que estamos hablando de un componente de React.

2023-05-30 14:49 UTC, wfercanas requested changes

2023-05-30 14:49 UTC, wfercanas commented on src/routes/privileges.jsx
> +          path="users/complete-register/:invitation_id"
Dejemos el path como 'complete-invitation', para que coincida con el componente y con la carpeta del directorio /users

2023-05-30 21:25 UTC, wfercanas approved these changes

2023-05-30 21:26 UTC, merged