Cr/232/general information form
selsa-inube/linpar pull request #183
Opened 2023-05-26 02:22 UTC by CristianRojas-47

2023-05-26 17:05 UTC, novadeveloper14 requested changes

2023-05-26 17:05 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +function GeneralInformationForm() {
aca no esta la prop de la funcion handleChange la cual le pasa las valores a el padre de el componente  GeneralInformationForm, al referirme al padre me refiero a el padre de GeneralInformationForm no de GeneralInformationFormUI revisar el diseño.

2023-05-30 14:23 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +        {allowSubmit && (
cuando al formulario se le están pasando datos **"WhitData"** y uno modifica un input se activan los botones. pero si uno vuelve a poner el mismo value que había antes de la modificación los botones ya no se ponen otraves isDisabled.

2023-05-31 22:48 UTC, novadeveloper14 approved these changes
El desarrollo cumple con los requerimientos.

2023-06-01 16:24 UTC, wfercanas requested changes
Reorganicemos usando de una vez Formik, implementando el hook useFormik, no los componentes <Formik /> y demás que usan por debajo react context.

2023-06-01 16:24 UTC, wfercanas commented on src/components/forms/FormContainer/index.jsx
Por ahora no hagamos esta extracción, dejemos la definición del formulario dentro de la carpeta forms del módulo de users/

2023-06-01 16:24 UTC, wfercanas commented on src/mocks/apps/privileges/GeneralInformationForm.mock.jsx
Es preferible extender el mock de `users.mock.jsx`. Este formulario se abre al intentar editar un usuario existente en esa lista de usuarios y es probable que el backend nos los devuelva en la primer consulta.

2023-06-05 15:28 UTC, novadeveloper14 requested changes

2023-06-05 23:16 UTC, Sebas3245 requested changes
Realizar los cambios, sería bueno revisar el pr de Angie ya que contiene varios de los ajustes solicitados en esta revisión:

[feat(invite): use Formik to control the invite user form](https://github.com/selsa-inube/linpar/pull/197)

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +              type="text"
Pongamos type="button"

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +  function stateValue(formik, attribute) {
Al llamar esta función siempre se recibe el mismo objeto formik que llega por props, por ende, no es necesario que la función lo reciba si ya puede acceder

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +  function renderMessages() {
Esto es un componente de React porque retorna JSX. Es mejor definirlo por fuera del componente si realmente es necesario que esta lógica este dentro de una función.

[nesting-and-organizing-components](https://react.dev/learn/your-first-component#nesting-and-organizing-components)
[different-components-at-the-same-position-reset-state](https://react.dev/learn/preserving-and-resetting-state#different-components-at-the-same-position-reset-state)

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +    validationSchema: Yup.object({
No es estricto que este objeto de Yup este dentro del componente, por ende por fuera del componente podemos crear una constante validationSchema y ahí colocar todas estas validaciones de yup y aquí solo llamarla: "validationSchema,"

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +          formik.handleSubmit();
No es necesario llamar aca a formik.handleSubmir(); ya que solo se esta ingresando a la condicion si hay errores, creo que podriamos poner un else y en este integrar a "formik.handleSubmir();"

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +    props.handleChange(submittedValues);
Quitar el "props."

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +    event.preventDefault();
Quitemos este preventDefault() y en su lugar en el interface.jsx hagamos que el boton de enviar sea type="button" y que este sea el que en su propiedad handleClick llame a handleSubmit en lugar de que el form lo haga.

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +        setLoading(true);
todo este contenido desde el setLoading(true) hasta la ultma linea del timeout podria estar dentro de la propiedad "onSubmit" que se puede añadir al objeto de useFormik

2023-06-05 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +  const LOADING_TIMEOUT = 1000;
Saquemos esta constante del componente es decir arriba de la declaración de GeneralInformationForm()

2023-06-06 16:07 UTC, Sebas3245 requested changes
Realizar el ajuste para que función el blur en los inputs según lo hablado en la reunión

2023-06-06 16:07 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +    .matches(/^[0-9]{10}$/, "Este campo debe tener un número de teléfono")
Agreguemos las validaciones mencionadas en la reunión

2023-06-06 16:07 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +          return;
Creo que este return no es necesario.

2023-06-06 16:07 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +              appearance={"confirm"}
Las propiedades con valor de tipo string mejor pasarlas sin los corchetes

2023-06-06 16:07 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +              isLoading={loading}
Hay que revisar porque cuando hago la prueba de "Guardar" en el storybook, no aparece el spinner en el button que representa el "loading"

2023-06-08 00:21 UTC, Sebas3245 requested changes

2023-06-08 00:21 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +        formik.handleSubmit();
Falta quitar el "else" y dejar solo el formik.handleSubmit(); debajo del if

2023-06-08 00:21 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
> +  const enableButtons =
Mejor cambiemos el nombre de la constante a disabledButtons ya que estaríamos haciendo lo contrario en la comparación

2023-06-08 00:21 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +  if (showMessage) {
Esta parte también aprovechemos y la refactorizamos evitando anidar ifs, podríamos refactorizar toda la asignación del messageType de la siguiente manera:

```javascript
    if (!showMessage) {
      return null;
    }

    let messageType = "success";

    if (formInvalid) {
      messageType = "failed";
    } 
```

2023-06-08 00:22 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
> +              appearance={"confirm"}
Aún falta este cambio

2023-06-08 14:23 UTC, Sebas3245 approved these changes

2023-06-08 14:28 UTC, novadeveloper14 approved these changes

2023-06-08 14:29 UTC, merged