jg/273/insert-subjectcard-in-edit-user-process
selsa-inube/linpar pull request #185
Opened 2023-05-26 15:38 UTC by novadeveloper14

insert <Subject Card /> component in edit user interface

2023-05-26 22:36 UTC, Sebas3245 requested changes

2023-05-26 22:36 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  function getUserInformation() {
Esta función podemos ubicarla debajo del estado de "isSelected", es decir para conservar el orden de tener las declaraciones de propiedades de estados arriba y las funciones abajo para que sea más legible a la hora de leer el código

2023-05-26 22:36 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +    const foundEntry = userEntriesDataMock.find((user) => user.id == id);
Esta variable "foundEntry" la podemos cambiar a foundUser, ya que dentro de este componente el contexto esta enteramente ligado al usuario

2023-05-26 22:36 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +      Codigo: foundEntry?.code || "",
Estas tres primeras propiedades "Name", "Identification" y "Codigo" cambiemoslas para que esten en camelCase, que su primer letra sea en minuscula, asi como la de "rol"

2023-05-26 22:36 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +    const subjectCardData = {
cambiemos esta constante a userCardData, a la final el contexto de que es la data de la subjectCard es algo que se transmite al agregarselo a la propiedad "subejjctData" del componente SubjectCard y en la UI lo recibe como user.

2023-05-26 22:38 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +    const foundEntry = userEntriesDataMock.find((user) => user.id == id);
Reemplazar la condición por una comparación estricta "==="

2023-05-29 13:29 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  const userID = parseInt(id);
Creeria que esta constante "userId" puede estar dentro de la funcion getUserInformation(), esto con el fin de tener una sola renderizacion para este dato cuando la funcion se renderice y no tener dos o mas (debido a que a la final ese userId parece que solo se usara dentro de esa funcion)

2023-05-29 14:13 UTC, Sebas3245 approved these changes

2023-05-29 16:52 UTC, wfercanas requested changes

2023-05-29 16:52 UTC, wfercanas commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +import { userEntriesDataMock } from "../../../../../mocks/apps/privileges/users.mock";
Hacer pull de main y cambiar este import por @mocks

2023-05-29 16:52 UTC, wfercanas commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +      rol: user?.position || "",
Este optional chaining directamente sobre `user` es repetitivo y realmente está validando que el objeto exista y no tanto que una propiedad de un objeto exista (que es más el espíritu del uso de esta feature).

Creo que aquí convendría hacer algunos cambios:
1. `getUserInformation()` se debería encargar de obtener el usuario, nada más, retornando el objeto `user`.
2. Si el return de `getUserInformation()` es `undefined`, podríamos evaluar si en lugar de retornar `<EditUserUI />`, retornamos otra cosa (User not found). Podemos poner el sólo texto y yo paso a diseño para que hagan en figma esa pantalla.
3. Si user existe, podemos pasar el user directamente a `<EditUser />`, sin extraer de él nada. Esa sería una tarea ya de la interface que extrae lo que necesite para pintar.

2023-05-29 16:52 UTC, wfercanas commented on src/pages/privileges/outlets/users/edit-user/index.jsx
>    const [isSelected, setIsSelected] = useState(
`isSelected` es diciente del lado de una tab, pues dentro de esa tab tiene sentido preguntarse si la tab está seleccionada o no.
En el contexto del padre, decir isSelected es confuso porque ya no es un boolean sobre sí mismo (como en el caso anterior) sino es una referencia a cuál de todas las tabs está selected.

Preferiría cambiar este estado por `selectedTab` o `selectedTabId`

2023-05-29 20:39 UTC, wfercanas requested changes

2023-05-29 20:39 UTC, wfercanas commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  if (!getUserInformation()) {
Es preferible que ejecute esta función y guarde el resultado en una variable antes de entrar a estas evaluaciones.
Esto porque aquí llama la función y abajo en el otro return vuelve y la llama.

Como esta función luego hará el fetch al backend por el user, estaría haciendo 2 fetch sin necesidad.

2023-05-29 20:39 UTC, wfercanas commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +import { userEntriesDataMock } from "../../../../../mocks/apps/privileges/users.mock";
Esto falta

2023-05-29 21:07 UTC, wfercanas requested changes

2023-05-29 21:07 UTC, wfercanas commented on src/pages/privileges/outlets/users/edit-user/index.jsx
Arreglemos la historia de este componente, le pasa lo mismo que a invitations y en la historia aparece User not found en lugar del layout.

2023-05-30 14:39 UTC, wfercanas approved these changes

2023-05-30 14:39 UTC, merged