sl/256/menu mobile invite user
selsa-inube/linpar pull request #189
Opened 2023-05-29 15:25 UTC by Sebas3245

Create Menu and MenuLink components and add option for mobile invite user

2023-05-30 14:08 UTC, novadeveloper14 requested changes

2023-05-30 14:08 UTC, novadeveloper14 commented on src/components/navigation/Menu/styles.js
> +import { colors } from "../../../styles/colors";
si el alias de **@styles** ya esta en main usémoslo sino dejémoslo así

2023-05-30 14:08 UTC, novadeveloper14 commented on src/components/navigation/MenuLink/index.jsx
> +import { Text } from "../../data/Text";
usemos el Text de `@inube/design-system`

2023-05-30 14:08 UTC, novadeveloper14 commented on src/components/navigation/MenuLink/stories/MenuLink.stories.jsx
> +import { menuInvitationLinks } from "../../../../pages/privileges/outlets/users/config/menuInvitation.config";
usemos el alias **@pages**

2023-05-30 15:00 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/interface.jsx
> +              <StyledOptionsContainer>
este contenedor esta quedando con una altura de 28px por lo que el icono no esta quedando completamente centrado

![image](https://github.com/selsa-inube/linpar/assets/87447257/4df3bea3-5eec-4f8e-997f-0dd36bd9cdf6)

2023-05-30 15:06 UTC, novadeveloper14 commented on src/components/navigation/MenuLink/index.jsx
> +        <Text typoToken="bodySmall">{label}</Text>
`typoToken` no es una prop valida para el componente `<Text />` de **@inube/design-system** creo que se referia a `typo`

2023-05-30 15:28 UTC, novadeveloper14 approved these changes
El desarrollo cumple con los requerimientos.

2023-05-31 17:09 UTC, wfercanas requested changes

2023-05-31 17:09 UTC, wfercanas commented on src/components/navigation/Menu/styles.js
> +  position: absolute;
Aquí estamos obligando a que el padre que necesite el menú, deba crear un componente relative encima para que el absolute de este Menú se organice. Hacer eso en todos los sitios donde vayamos a poner un menú suena algo aburrido (aparte de que hay que acordarse).

Quizá podamos hacer que el StyledMenu sea en sí un container relative de width 0 y que por dentro esté otro container que use el position absolute.

2023-05-31 17:09 UTC, wfercanas commented on src/components/navigation/MenuLink/styles.js
> +const StyledLink = styled(Link)`
Hay algunos detalles del menú que no coinciden con la estética del mockup. A primera vista parece que el ícono no tiene el color correcto, el tamaño del ícono debería ser de 16px y la sombra del menú tampoco es equivalente.

2023-05-31 17:09 UTC, wfercanas commented on src/components/navigation/Menu/index.jsx
Sería bueno que el componente recibiera el setter del estado que prende o apaga el menú, con eso:
1. Podemos usar un useRef para seleccionar el menú.
2. Luego del renderizado creemos un useEffect donde le peguemos un event listener al document para el evento click.
3. Ese evento click dispara un handler que evalúa si el event.target le incluye al menú (para eso el useRef)
4. Si el click es por fuera del useRef, podemos apagar el menú.

La intención es que el menú no se quede pegado cuando se abre, que no dependa de que le vuelvan a hacer click a los 3 punticos para que se cierre.

2023-05-31 21:11 UTC, Sebas3245 commented on src/components/navigation/Menu/index.jsx
> +  const { links } = props;
close #195

2023-06-01 03:50 UTC, wfercanas commented on src/components/navigation/Menu/index.jsx
> +  const { links } = props;
Creo que necesitamos ambos componentes `<MenuLink />` y `<MenuOption />`, eso obliga a que la prop venga en una estructura de datos tal donde si es un link pase el path y si el una opción venga el handleClick.

2023-06-01 15:25 UTC, wfercanas commented on src/components/navigation/Menu/index.jsx
> +  const renderMenuItems = () => {
Esto es un componente de React porque retorna JSX. No lo defina dentro de otro componente de React. si realmente lo necesita, defínalo por fuera.

Ver estas secciones en la documentación de React:
[Nesting and organizing components](https://react.dev/learn/your-first-component#nesting-and-organizing-components)
[Different components at the same position reset state](https://react.dev/learn/preserving-and-resetting-state#different-components-at-the-same-position-reset-state)

2023-06-01 15:29 UTC, wfercanas commented on src/components/navigation/MenuOption/styles.js
> +import { Link } from "react-router-dom";
Este componente se importa y no se usa

2023-06-01 15:30 UTC, wfercanas commented on src/components/navigation/MenuLink/styles.js
Revise con Leonardo porque yo creo que estos Links u Options, deberían tener un comportamiento hover.

2023-06-02 01:16 UTC, merged