feat(invite): use Formik to control the invite user form
selsa-inube/linpar pull request #197
Opened 2023-05-31 22:21 UTC by ANGIECATHERINEP

2023-06-02 13:48 UTC, novadeveloper14 requested changes

2023-06-02 13:48 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +        .test("id", "El número de identificación ya existe", function (value) {
por el momento no hagamos este tipo de validación

2023-06-05 14:55 UTC, novadeveloper14 requested changes

2023-06-05 14:55 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +import { invitationEntriesDataMock } from "@mocks/apps/privileges/invitations.mock";
esta importación no esta siendo utilizada.

2023-06-05 21:01 UTC, Sebas3245 requested changes

2023-06-06 14:49 UTC, Sebas3245 requested changes
Realizar tambien los ajustes comentados en la reunión con respecto a las validaciones del formulario

2023-06-06 14:49 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +        return;
Creo que este return no es necesario

2023-06-06 22:41 UTC, Sebas3245 requested changes

2023-06-06 22:41 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +      /^[0-9]{5,15}$/,
Como en esta expresión regular también está validando la longitud no llega a mostrar el siguiente error que es el del min y el max, probemos dejar que este regex solo sea de validar que lo que se escriba sean números

2023-06-06 22:41 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +    .matches(/^\d{10}$/, "Este campo debe tener un número de teléfono válido")
Esta expresión regular esta validando que la longitud sea de 10 y la siguiente igual, pasa como con el caso anterior, mejor que esta expresión sea solo de validar que sean números

2023-06-06 22:41 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/index.jsx
> +    .required("Este campo debe contener un número de teléfono"),
Me parece que todos estos textos de la validación "required" deberíamos cambiarlos para que digan algo como "Este campo no puede estar vacío" para que sea un poco más diciente y no lo confundamos con la primera validación

2023-06-08 00:06 UTC, Sebas3245 requested changes

2023-06-08 00:06 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/interface.jsx
>    function renderMessages() {
Esta funcion no estaba dentro del desarrollo, sin embargo ya que estamos ajustando el archivo aprovechemos y ya que esto es un componente de React porque retorna JSX. Es mejor definirlo por fuera del componente si realmente es necesario que esta lógica este dentro de una función.

[nesting-and-organizing-components](https://react.dev/learn/your-first-component#nesting-and-organizing-components)
[different-components-at-the-same-position-reset-state](https://react.dev/learn/preserving-and-resetting-state#different-components-at-the-same-position-reset-state)

2023-06-08 00:06 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/interface.jsx
>      if (showMessage) {
Esta parte también aprovechemos y la refactorizamos evitando anidar ifs, podríamos refactorizar toda la asignación del messageType de la siguiente manera:

```javascript
    if (!showMessage) {
      return null;
    }

    let messageType = "success";

    if (formInvalid) {
      messageType = "failed";
    } 
```

2023-06-08 14:16 UTC, Sebas3245 approved these changes

2023-06-08 14:27 UTC, novadeveloper14 approved these changes

2023-06-08 14:29 UTC, merged