feat(aidBudget): develop the aid budget unit form
selsa-inube/linpar pull request #203
Opened 2023-06-05 17:34 UTC by CristianRojas-47

2023-06-05 20:03 UTC, ANGIECATHERINEP approved these changes
El requerimiento fue realizado correctamente

2023-06-05 21:51 UTC, Sebas3245 requested changes

2023-06-05 21:51 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.jsx
> +    handleSubmit(aidBudgets);
Analizando un poco esta parte propongo agregar un timeout de 1500 para poner en false el isLoading con el fin de simular la experiencia de usuario

2023-06-06 15:27 UTC, Sebas3245 approved these changes

2023-06-06 15:30 UTC, Sebas3245 approved these changes

2023-06-06 15:30 UTC, merged