jg/321/create-empty-state-screen-user-not-found
selsa-inube/linpar pull request #204
Opened 2023-06-05 18:02 UTC by novadeveloper14

2023-06-05 21:45 UTC, CristianRojas-47 requested changes
El desarrollo del requerimiento es correcto, hace falta el despliegue del UserNotFound en la historia localizada en "src/pages/privileges/outlets/users/edit-user/EditUser.stories.jsx"

2023-06-06 13:50 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-06-06 16:52 UTC, Sebas3245 requested changes

2023-06-06 16:52 UTC, Sebas3245 commented on src/components/layout/ItemNotFound/index.jsx
> +          <Text typo={smallScreen ? "titleSmall" : "titleLarge"}>{title}</Text>
Hay que revisar este texto porque en pantallas menores a 300px se está alineando a la izquierda y debería estar centrado

2023-06-06 16:52 UTC, Sebas3245 commented on src/components/layout/ItemNotFound/index.jsx
> +            {description}
La descripción aparece con un color diferente al de los mockups de Figma, revisar si existe otro token que se ajuste

2023-06-06 16:52 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/interface.jsx
> +  if (user) {
Mejor eliminemos esta condición y declaremos userCardData en una constante que en su valor tenga un operador ternario "? :" en el cual el "else" sea null, con esto le damos un alcance más amplio y asegura que siempre esté disponible en todo el componente, incluso si "user" no existe.

```javascript
const userCardData = user
    ? {
        nombre: user.username,
        identificación: user.userID,
        codigo: user.code,
        rol: user.position,
      }
    : null;
```

2023-06-06 20:01 UTC, merged