feat(payrollsForm): develop the payroll form
selsa-inube/linpar pull request #205
Opened 2023-06-05 19:53 UTC by ANGIECATHERINEP

2023-06-05 23:59 UTC, novadeveloper14 approved these changes
La implementación de el formulario se realizo correctamente.

2023-06-06 12:30 UTC, Sebas3245 requested changes

2023-06-06 12:30 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/PayrollsForm.stories.jsx
> +const handleSubmit = (newAidPayrolls) => {
Creo que el termino "aid" no va ahi

2023-06-06 12:30 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.jsx
> +      title="Seleccione los detalles de nómina que desea asignar"
Cambiemos "detalles de nomina" por "conceptos de nomina"

2023-06-06 14:21 UTC, Sebas3245 approved these changes

2023-06-06 15:35 UTC, merged