feat(completeInvitation): add aid budget units form
selsa-inube/linpar pull request #223
Opened 2023-06-13 20:42 UTC by ANGIECATHERINEP

2023-06-13 21:03 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-06-13 21:25 UTC, Sebas3245 requested changes

2023-06-13 21:25 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/interface.jsx
> +                currentAidBudgets={invitationData.aidBudgets.entries}
debido a que en el config aparece como "aidBudgetUnits" y en el invitation esta como "aidBugets", no se está seteando correctamente el valor en el estado, habría que cambiar para ponerlo "aidBudgetUnits" tambien en el estado y así mismo verificar en donde este diferente, como en el current del form, al hacer este cambio, verificar que se esté seteando correctamente el estado con un console.log en el componente.

2023-06-13 21:25 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/interface.jsx
> +                withSubmitButtons={true}
Creo que todos estos forms van sin botones según los mockups de Figma

2023-06-14 12:40 UTC, Sebas3245 requested changes

2023-06-14 12:40 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.jsx
> +  const handleChangeAidBudgets = (aidBudgetsUnits) => {
creo que el plural correcto es "aidBudgetUnits"

2023-06-14 14:12 UTC, merged