jg/354/replace-nav-from-design-system
selsa-inube/linpar pull request #238
Opened 2023-06-16 14:43 UTC by novadeveloper14

2023-06-16 21:56 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto, no sé si una buena opción de la redirección que hace el Logout sea al index.

2023-06-16 22:11 UTC, Sebas3245 requested changes

2023-06-16 22:11 UTC, Sebas3245 commented on src/components/Header/interface.jsx
> +            <Nav navigation={navigationConfig} logoutPath="/logout" />
dejemos el logout con ="/"

2023-06-19 22:33 UTC, Sebas3245 requested changes

2023-06-19 22:33 UTC, Sebas3245 commented on src/pages/home/config/apps.config.jsx
> +          label: "contabilidad",
Como este, hay otros label que tienen la primera letra en minúscula, debe estar capitalizado el texto

2023-06-19 22:33 UTC, Sebas3245 commented on src/components/Header/interface.jsx
> +            <Nav navigation={navigationConfig} logoutPath="/" />
Al ver los mockups en figma se evidencia que el título "Menu" no tiene tanta margen abajo como sucede con este componente:

Figma:

![image](https://github.com/selsa-inube/linpar/assets/55991750/f4048507-1a2d-42eb-a766-38b4f8c95f97)

Componente Nav de design-system:
![image](https://github.com/selsa-inube/linpar/assets/55991750/42bc9abe-aba1-4bc3-85ab-b69b2e2867c8)

Aparte que el color del título y los textos parece ser diferente, hay que consultar con Cesar Marin estos temas para saber si es así por algún motivo o si tendrían que ajustar ese componente.

2023-06-20 17:49 UTC, Sebas3245 commented on src/components/Header/interface.jsx
> +            <Nav navigation={navigationConfig} logoutPath="/" />
¿Al fin para esto se hará algún ajuste o ese debe ser el diseño del componente ahora? según lo hablado con Cesar Marin

2023-06-23 23:12 UTC, novadeveloper14 reviewed
la actualización de la librería design-system arreglo el issue.

2023-06-26 02:31 UTC, Sebas3245 approved these changes

2023-06-26 02:31 UTC, merged