feat(menu): migrate menu component to typeScript
selsa-inube/linpar pull request #239
Opened 2023-06-16 16:13 UTC by CristianRojas-47

2023-06-16 18:22 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-06-16 18:54 UTC, Sebas3245 requested changes

2023-06-16 18:54 UTC, Sebas3245 commented on src/components/navigation/Menu/index.tsx
> +          path={option.path as string}
Para no tener que hacer este "as string" cambiemos el if ()

de
```javascript
option.hasOwnProperty("path")
``` 

a

```javascript
option.path
```

2023-06-16 18:54 UTC, Sebas3245 commented on src/components/navigation/Menu/index.tsx
> +        <Stack direction="column">{RenderMenuItems({ options })}</Stack>
Porque RenderMenuItems se cambió a llamarse como a una función convencional?

Anteriormente estaba llamándose como a un componente debido a que este tenía la nomenclatura convencional de iniciar su primera letra en mayúscula, además de tener la extracción de propiedades de un parámetro llamado "props" y el retorno de un elemento JSX, si se va a realizar ese ajuste entonces sería ideal cambiar la primera letra de la función a minúscula y recibir directamente los parámetros y no extraerlos de props.

2023-06-16 18:54 UTC, Sebas3245 commented on src/types/index.d.ts
> +declare module "react-router-dom";
React router dom si cuenta con una libreria de "@types", habría que instalarla en lugar de hacer este "declare module", la guía de esto se encuentra en el documento del diseño

2023-06-16 18:54 UTC, Sebas3245 commented on src/components/navigation/Menu/index.tsx
> +interface OptionProps {
Mejor separemos esta interface en un archivo al mismo nivel de index.tsx llamado "types.ts" y desde ahí generamos la exportación, esto debido a que en el index.tsx solo se debería exportar la interface directa del componente y en el "types.ts" podemos exportar todos los tipos que podemos requerir desde otros lugares de la app

2023-06-16 18:54 UTC, Sebas3245 commented on src/components/navigation/Menu/index.tsx
> +        handleClick={option.handleClick as () => void}
Para no hacer este "as () => void", podemos crear otra condición en la cual se valide la existencia del handleClick: 

```javascript
if (option.handleClick)
``` 

y en esta encerrar el retorno de MenuOption y al final de la función añadir un return null;

2023-06-19 22:50 UTC, Sebas3245 commented on src/components/navigation/Menu/index.tsx
> +        <Stack direction="column">{RenderMenuItems({ options })}</Stack>
Aún falta resolver este comentario, la idea no sería dejarlo en una constante donde la función este con la primera letra en minúscula si no cambiar la función RenderMenuItems para que primera letra del nombre este en minúscula y recibir directamente los parámetros y no extraerlos de props.

2023-06-20 16:08 UTC, Sebas3245 approved these changes

2023-06-20 16:08 UTC, merged