jg/365/migrate-ItemNotFound-to-TypeScript
selsa-inube/linpar pull request #246
Opened 2023-06-16 21:33 UTC by novadeveloper14

2023-06-16 21:51 UTC, ANGIECATHERINEP approved these changes
La migración a typeScript se realizo correctamente

2023-06-16 22:04 UTC, Sebas3245 approved these changes

2023-06-16 22:05 UTC, Sebas3245 requested changes
Hay que resolver los conflictos en src/components/layout/ItemNotFound/index.jsx.

2023-06-19 22:25 UTC, Sebas3245 approved these changes

2023-06-19 22:25 UTC, merged