jg/286/insert-general-information-form-edit-user
selsa-inube/linpar pull request #248
Opened 2023-06-16 22:14 UTC by novadeveloper14

2023-06-16 22:54 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-06-19 22:46 UTC, Sebas3245 requested changes

2023-06-19 22:46 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  const user = getUserInformation();
Hay que evitar el uso de esta instancia "user", porque a la final si es lo mismo que estará en "editData.generalInformation.entries" no se justificaría crear dos instancias para el mismo valor ya que el efecto negativo de esto será mayor cuando tengamos que extraer los datos desde otro medio y se alimentaran ambas instancias, así mismo para crear la constante "userCardData" en "interface.jsx" podemos conseguir esa información de editData, para esto debe guiarse de complete-invitation ya que ahí se encuentra el mismo caso adaptado a lo que estoy mencionando.

2023-06-20 12:39 UTC, Sebas3245 approved these changes

2023-06-20 12:39 UTC, merged