Ap/236/modal confirmation changing tabs
selsa-inube/linpar pull request #278
Opened 2023-06-26 13:56 UTC by ANGIECATHERINEP

2023-06-26 19:42 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-06-26 23:56 UTC, Sebas3245 requested changes

2023-06-26 23:56 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +    continueTab: null,
Mejor inicialicemos a  continueTab como un string vacío "", para que el código nos hable sobre qué tipo de valor va ahí

2023-06-26 23:56 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +    if (currentFormHasChanges) {
Como a la final esta condición solo está actuando como pregunta para saber que valores asignar mas no está aplicando ninguna lógica de mutación de datos durante este, podríamos refactorizarlo para dejar un poco más compacto el código de la siguiente manera:

```javascript
const handleTabChange = (tabId) => {
  const modalUpdate = currentFormHasChanges
    ? { show: true, continueTab: tabId }
    : controlModal;

  setControlModal(modalUpdate);
  setSelectedTab(currentFormHasChanges ? selectedTab : tabId);
};
```

2023-06-26 23:56 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  const handleDataChange = (editData) => {
El nombre de este parámetro al leerlo nos estaría indicando que está llegando una estructura de datos, sin embargo, esto no es así ya que lo que llega es un booleano, por lo tanto, con el fin de que el código nos hable sobre la función por sí solo podríamos cambiar el nombre del parámetro a "hasChanges"

2023-06-26 23:56 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  const HandleContinueTab = () => {
Esta función convencional debería estar en camelCase

2023-06-26 23:56 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.jsx
> +  const validateDataReset = (resetData) => {
Estuve probando los tabs y los cambios comentando el contenido de esta función y no encontré la diferencia entre tenerla o no debido a que, si por ejemplo yo cancelo los cambios, él llega al handleDataChange y asigna el setCurrentFormHastChanges a false, sería bueno si el día de mañana nos conectamos si es posible para tener claro el funcionamiento de esta función

2023-06-26 23:56 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/interface.jsx
> +    <DecisionModal
Hay algo curioso con este Modal y es que si yo le doy en continuar el botón muestra el Spiner de carga, sin embargo, si bien en los casos anteriores esto aplicaba, en este caso creería que en cuanto a UX no pertenece este efecto ya que no se estaría realizando ningún Submit al decir que cambiamos de Tab sin guardar cambios, habría que consultar con Leonardo si este efecto si iría teniendo esto en cuenta

2023-06-27 17:29 UTC, Sebas3245 approved these changes

2023-06-27 17:30 UTC, merged