jg/422/migrate-login-page-to-typeScript
selsa-inube/linpar pull request #291
Opened 2023-06-28 20:35 UTC by novadeveloper14

2023-06-28 22:11 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-06-28 23:40 UTC, Sebas3245 requested changes
En general se esta estableciendo que cada componente de este desarrollo retorne JSX.Element

![image](https://github.com/selsa-inube/linpar/assets/55991750/46f77808-ef01-43b0-9847-42c056a9c882)

Sin embargo esto no es necesario ya que por si solo cuando una funcion retorna JSX se establece este como su tipo:

![image](https://github.com/selsa-inube/linpar/assets/55991750/3a22473e-9eb0-41da-9a71-ca311f17d792)

Hay que eliminar todas las declaraciones donde se está estableciendo que cada componente retorne: JSX.Element

2023-06-28 23:40 UTC, Sebas3245 commented on src/pages/login/index.tsx
> +function Login(): JSX.Element {
No es necesario definir que el retorno es un JSX.Element

2023-06-28 23:40 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/index.tsx
> +    ref: React.RefObject<HTMLInputElement>;
Podemos crear una interfaz en un archivo types.ts para definir los valores de este useState

2023-06-28 23:40 UTC, Sebas3245 commented on src/pages/login/errors/ErrorNotAvailable/index.tsx
>    return <ErrorPage />;
Acá el Linter está arrojando un error de props: 
![image](https://github.com/selsa-inube/linpar/assets/55991750/2136843a-4201-4619-ba1e-7da0f86bbb91)

2023-06-28 23:40 UTC, Sebas3245 commented on src/pages/login/errors/ErrorNotClient/index.tsx
>      <ErrorPage
Acá el Linter está arrojando un error de props: 
![image](https://github.com/selsa-inube/linpar/assets/55991750/2fbe451e-5481-4c37-a518-ee1f5b0adfe9)

2023-06-28 23:41 UTC, Sebas3245 commented on src/pages/login/errors/ErrorNotClient/index.tsx
>      <ErrorPage
Para solucionar esto podemos ir a ErrorPage y asignar como opcional "prop?: type" cada propiedad que así lo sea es decir las que tienen prop = "valor" en su declaración de instancia.

2023-06-29 11:53 UTC, Sebas3245 requested changes

2023-06-29 11:53 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/types.ts
> +interface ClientState {
Falta seguir la nomenclatura estándar de las interfaces dentro de types.ts que es iniciando el nombre con "I" es decir en este caso "IClientState"

2023-06-29 11:53 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/interface.tsx
> +  client: {
Acá se puede usar la interfaz IClientState en lguar de definir los tipos otra vez para client

2023-06-29 11:53 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/types.ts
> +  value: string | undefined;
Este valor debería ser tipo boolean ya que solo se está usando en interface.tsx para saber si deshabilita o no un button

2023-06-29 11:53 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/index.tsx
> +    ref: useRef<HTMLInputElement>(null),
El estado en React debería ser utilizado para almacenar valores primitivos o estructuras de datos simples, como números, cadenas de texto o matrices de objetos. No se recomienda almacenar referencias directamente en el estado. (useRef)

Una forma de solucionarlo es que en IClientState el ref pueda ser "| null" y acá inicializar ref con null

2023-07-04 19:05 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/index.tsx
> +      ref: client.ref,
Acá no debería ser event.target??
Ese client.ref estaría null

2023-07-04 19:05 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/types.ts
> +  value: string | undefined;
Sigo con la duda ya que solo se usa aca:

![image](https://github.com/selsa-inube/linpar/assets/55991750/19809d34-7702-4a9d-aef8-15341ca95711)

Si bien se está inicializando como string se está validando como boolean y aunque funcione no está siendo descriptivo el código, la pregunta es "handleClientChange" que le setea en su .value, un string o un boolean?

2023-07-04 19:07 UTC, Sebas3245 requested changes
Realizar los ajustes correspondientes y validar el funcionamiento.

2023-07-05 00:03 UTC, Sebas3245 approved these changes

2023-07-05 00:03 UTC, merged