feat(home): migrate Home component to typeScript
selsa-inube/linpar pull request #294
Opened 2023-06-28 22:08 UTC by ANGIECATHERINEP

2023-06-28 22:26 UTC, novadeveloper14 approved these changes
la migración se realizo correctamente.

2023-06-28 23:29 UTC, Sebas3245 requested changes

2023-06-28 23:29 UTC, Sebas3245 commented on src/pages/home/types.ts
> +interface Iapps {
Coloquemos esta interface como IApps siguiendo la nomenclatura de la primera letra en mayúscula como tenemos en las otras de este tipo

2023-06-29 00:47 UTC, Sebas3245 requested changes
Falta el archivo apps.config.jsx pasarlo a .ts, está en la siguiente ruta: 
src\pages\home\config

Creeria que a .ts como tal ya que no hay ningún retorno de JSX para colocarlo como .tsx

2023-06-29 01:11 UTC, ANGIECATHERINEP commented
el  archivo apps.config no es posible pasarlo a ts ya que el atributo icon de el arreglo de objetos appsConfig es tipo JSX.Element

2023-06-29 01:15 UTC, Sebas3245 approved these changes

2023-06-29 01:15 UTC, merged