Ap/346/improve assisted styles
selsa-inube/linpar pull request #300
Opened 2023-06-30 19:45 UTC by ANGIECATHERINEP

2023-06-30 21:59 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-06-30 22:46 UTC, Sebas3245 requested changes

2023-06-30 22:46 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.jsx
> +let marginSteps = "";
La variable marginSteps se declara fuera de la función AssistedUI y se utiliza para mantener el estado entre renderizaciones. Esto puede causar problemas de compartición de estado y dificultar el seguimiento de los cambios. En React, se recomienda utilizar el estado local (useState) para manejar el estado interno, sin embargo para definir lo del margin a la izquierda o derecha seria mejor utilizar lo del firstStep y isVerification, haciendo el que el StyledSteps se envuelva en otro Styled que tenga el ancho y centre los steps y teniendo eso en cuenta ahora se haga lo contrario si los steps que se están renderizando tienen  el primer paso y son 5 pasos por vista el  numero 5 debería tener un marginRight y si es el de verificación se debería buscar el primer paso de ese grupo de vista y a ese asignarle el marginLeft

2023-06-30 22:46 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.jsx
>    function renderStep(step, index) {
La función renderStep tiene múltiples caminos de ejecución, pero solo devuelve un valor en algunos casos. En caso de que no se cumplan las condiciones, la función no devuelve nada (undefined). Es una buena práctica asegurarse de que una función siempre devuelva un valor, incluso si es null o false. Esto mejora la legibilidad y evita errores inesperados.

2023-06-30 22:46 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.jsx
> +  const validateStepsPerView = MAX_STEPS_PER_VIEW > steps.length;
La variable validateStepsPerView se calcula en cada renderizado de AssistedUI, lo cual puede ser ineficiente. Además, la comparación MAX_STEPS_PER_VIEW > steps.length puede dar como resultado el mismo valor en cada renderizado si MAX_STEPS_PER_VIEW y steps.length no cambian. Sería más eficiente calcular validateStepsPerView dentro de renderStep()

2023-07-05 00:12 UTC, Sebas3245 approved these changes
Seria bueno

2023-07-05 00:12 UTC, merged