fix(editUser): adjust labels of edit user and complete registration
selsa-inube/linpar pull request #301
Opened 2023-07-04 15:55 UTC by CristianRojas-47

2023-07-04 21:40 UTC, novadeveloper14 approved these changes
el arreglo se realizo correctamente.

2023-07-04 23:58 UTC, Sebas3245 requested changes
En la tarjeta en Jira se hizo mención de que lo ideal sería utilizar la propiedad "labels" que provee ahora el SubjectCard, esto con el fin de no quemar en español y con la primera letra en mayúscula los atributos del objeto ya que a nivel de código se ve mal y desentona con el resto del código.

2023-07-05 19:40 UTC, Sebas3245 requested changes

2023-07-05 19:40 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.jsx
> +    titleName: "Invitación",
Cambiemos este a "Fecha de invitación"

2023-07-05 19:53 UTC, Sebas3245 approved these changes

2023-07-05 19:53 UTC, Sebas3245 commented
solved #297

2023-07-05 19:53 UTC, merged