jg/418/migrate-Assisted-to-TypeScript
selsa-inube/linpar pull request #305
Opened 2023-07-06 00:03 UTC by novadeveloper14

2023-07-06 20:34 UTC, ANGIECATHERINEP requested changes

2023-07-06 20:34 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/StepBar/types.ts
> +interface IStepBarProps {
La interface IStepBarProps deberías crearla en el archivo index.tsx del componente, según el comentario anterior

2023-07-06 20:34 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/StepBar/types.ts
> +interface IStepProps {
La interface IStepProps deberías crearla en el archivo styles.ts del componente, ya que no es necesario crear el archivo types debido a que este lo utilizamos para interfaces que son reutilizables o para las interfaces que definen un objeto o arreglo (estos arreglos u objetos van en la definición de algún atributo de una interface) ejemplo: 
![ejemplo](https://github.com/selsa-inube/linpar/assets/88405711/5c687259-cfcb-4f05-82a3-ced2922c91a1)
 (se viene manejando de esa manera en los demás componentes)

2023-07-06 20:34 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/StepIndicator/types.ts
> +  stepNumber: number;
Igual para estas interfaces

2023-07-06 20:34 UTC, ANGIECATHERINEP commented on src/components/feedback/Assisted/types.ts
> +interface IAssistedProps {
de la misma manera para las interfaces IAssistedProps (en index.tsx)  y  IAssistedUIProps (en interface.tsx)

2023-07-07 13:14 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-07-07 13:48 UTC, Sebas3245 requested changes

2023-07-07 13:48 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepBar/index.tsx
> +interface IStepBarProps {
Segun el estandar que estamos implementando en cuanto a nomenclatura en el nombre las interfaces/tipos el sufijo "Props" se implementa justo al final del nombre de la interface si esta es para definir las propiedades de un componente y el prefijo "I" al inicio del nombre de la interface si esta es para definir una estructura ya sea de estilos o de un objeto que contiene muchas propiedades o que es exportable, pero no puede tener ambos, esto hay que ajustarlo en la mayor parte de las interfaces de este desarrollo ya que se presenta lo mismo.

Para estas migraciones a typescript que son un poco largas y complejas es bueno pegarle otra revisada al RFC de la guía de migración:
[RFC-81 - Migration](https://senlinea.sharepoint.com/:w:/s/inube/EZJmcrirO8BOrfEl5ZKtAg4BEYgTymilB64C1GpIR9KAfg?e=nRGogd)

2023-07-07 13:48 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepBar/styles.ts
> +const StyledStep = styled.div<IStepProps>`
Estas interfaces de los styled-components deben tener el mismo nombre del componente de estilo con el prefijo "I":

[RFC-81 - Styles](https://senlinea.sharepoint.com/:w:/s/inube/EZJmcrirO8BOrfEl5ZKtAg4BEYgTymilB64C1GpIR9KAfg?e=nRGogd)

2023-07-07 13:48 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.tsx
> +  currentStepInfo: IStep | undefined;
Si vamos a manejar una propiedad como opcional (es decir que puede estar indefinida o que su valor llegue nulo) se debe hacer con el caracter "?", Ej:. "currentStepInfo?: IStep"

[RFC-81 - Optional parameters](https://senlinea.sharepoint.com/:w:/s/inube/EZJmcrirO8BOrfEl5ZKtAg4BEYgTymilB64C1GpIR9KAfg?e=nRGogd)

2023-07-07 13:48 UTC, Sebas3245 commented on src/components/feedback/Assisted/interface.tsx
> +  currentStep: string;
El currentStep es un entero segun los datos de la configuracion en el objeto de ejemplo stepsRegisterUserConfig

2023-07-07 13:48 UTC, Sebas3245 commented on src/components/feedback/Assisted/types.ts
> +  isVerification: boolean;
Esta propiedad debería ser opcional ya que no todos los objetos del arreglo la tendrán

2023-07-07 19:11 UTC, Sebas3245 requested changes

2023-07-07 19:11 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepBar/styles.ts
> +interface StyledLine extends IStyledStep {}
Deberia ser "IStyledLine" 

[RFC-81 - Styles](https://senlinea.sharepoint.com/:w:/s/inube/EZJmcrirO8BOrfEl5ZKtAg4BEYgTymilB64C1GpIR9KAfg?e=nRGogd)

2023-07-07 19:11 UTC, Sebas3245 commented on src/components/feedback/Assisted/StepBar/styles.ts
> +function getLineColor(props: IStyledStep) {
Tanto getLineColor como getLineDisplay solo se usan en StyledLine por lo tanto deberian recibir la interfaz de IStyledLine

2023-07-07 19:11 UTC, Sebas3245 commented on src/components/feedback/Assisted/types.ts
> +  id: string;
El id es un entero segun los datos de la configuracion en el objeto de ejemplo stepsRegisterUserConfig

2023-07-07 20:45 UTC, Sebas3245 requested changes

2023-07-07 20:45 UTC, Sebas3245 commented on src/components/feedback/Assisted/index.tsx
> +      (step) => Number(step.id) === currentStep
Como step.id es un number no hay la necesidad de realizar la conversión Number(value).

Esto sucede en otros 3 casos en este archivo.

2023-07-07 22:26 UTC, Sebas3245 approved these changes

2023-07-07 22:26 UTC, merged