fix(generalInformation): adjust general informations buttons and hasC…
selsa-inube/linpar pull request #306
Opened 2023-07-06 17:24 UTC by CristianRojas-47

…hanges function

2023-07-06 17:41 UTC, novadeveloper14 approved these changes
El arreglo se realizo correctamente.

2023-07-06 18:13 UTC, Sebas3245 requested changes
Cuando en edit user le doy guardar y todo salió bien los botones deberían deshabilitarse para no permitir guardar otra vez los mismos datos que se acaban de guardar, aún falta que funcione ese comportamiento correctamente

2023-07-10 19:02 UTC, Sebas3245 approved these changes

2023-07-10 19:02 UTC, merged

2023-07-10 19:02 UTC, Sebas3245 commented
solved #299