sl/396/control-actions-view
selsa-inube/linpar pull request #309
Opened 2023-07-07 22:37 UTC by Sebas3245

2023-07-08 00:49 UTC, novadeveloper14 requested changes
1. Solucionar el tema de complete invitation 
2. verificar el correcto funcionamiento de la implementación en la story Default: **layouts/privileges/outlets/users**

2023-07-08 00:49 UTC, novadeveloper14 commented on src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.jsx
> +        <StyledLink
Cuando se usa el action de open en invitations, el action de complete invitation aunque este desactivado, permite hacer la redirección.

2023-07-10 19:36 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.jsx
> +        <StyledLink
Se creo una issue en design-system al respecto

2023-07-10 23:01 UTC, novadeveloper14 approved these changes
La implementación se realizo correctamente.

2023-07-11 01:11 UTC, merged

2023-07-11 01:12 UTC, Sebas3245 commented
solved #219