jg/482/migrate-complete-invitation-page-to-TypeScript
selsa-inube/linpar pull request #329
Opened 2023-07-14 14:24 UTC by novadeveloper14

2023-07-14 15:44 UTC, ANGIECATHERINEP requested changes

2023-07-14 15:44 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/complete-invitation/types.ts
> +  branches: { entries: any };
se debería cambiar el tipo de dato "any", ya que no se puede dejar nada con este tipo, por esto debes crear las interfaces que correspondan y generalizar las que se puedan,  también hay que tener en cuenta que esas mismas interfaces las utilizara el componente EditUser

2023-07-14 21:29 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-07-14 21:57 UTC, Sebas3245 requested changes

2023-07-14 21:57 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
> +  const handleSubmit = (values: any) => {
Debemos evitar lo maximo posible el uso del "any", en este caso podemos utilizar union types para representar esa situación de la siguiente manera:

```typescript
const handleSubmit = (
    values: IGeneralInformationEntry[] | IAssignmentFormEntry[]
  )
```

2023-07-14 21:57 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
>      const stepKey = Object.keys(stepsRegisterUserConfig).find(
Para no tener que utilizar "as keyof typeof" podemos refactorizar el valor de stepKey de la siguiente manera:

```typescript
const stepKey = Object.entries(stepsRegisterUserConfig).find(
      ([, config]) => config.id === currentStep
    )?.[0];
```

2023-07-14 21:57 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/interface.tsx
> +  handleSubmit: (values: any) => void;
Igual que en el comentario anterior usar union types y no el "any"

2023-07-14 21:57 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/interface.tsx
> +                subjectData={invitationCardData || {}}
eEta expresión "|| {}" creará un nuevo objeto vacío cada vez que invitationCardData sea false. Si invitationCardData es un objeto existente y mutable, esto puede causar efectos no deseados. Por ejemplo, si se esta pasando invitationCardData como una prop a un componente de React y se utiliza subjectData={invitationCardData || {}}, cada vez que invitationCardData sea falsy, se creará un nuevo objeto vacío y se pasará al componente. Esto puede provocar que el componente se vuelva a renderizar innecesariamente, incluso si invitationCardData no ha cambiado realmente, para corregir esto se puede agregar && invitationCardData al lado del operador currentInformation && que valida la existencia de este segmento del componente

2023-07-14 21:57 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/types/types.ts
> +interface IBranches {
Como todos estos formularios tendran las mismas propiedades podriamos crear una interfaz comun "IAssignmentFormEntry"

2023-07-14 21:57 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/types/types.ts
> +interface IGeneralInformation {
Cambiemos el nombre de esta interfaz a: "IGeneralInformationEntry"

2023-07-14 22:01 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/types/types.ts
> +  generalInformation: { entries?: IGeneralInformation };
Este entries no debe ser opcional, su valor debe estar definido así este vacío, ya habría que validar dentro de su seteo el valor de llegada, pero no puede ser opcional

2023-07-17 12:46 UTC, Sebas3245 requested changes
1. Realizar los ajustes del review
2. Como se creó un directorio types (el cual me parece que si es ideal para este directorio que se puede crecer tanto en ese sentido) me parece que hay que integrar a ese directorio el archivo types.ts que existe actualmente, pero no me refiero a dejar todos esos types en un solo archivo, podríamos cambiar el nombre del types.ts que usted creo dentro de types a "forms.types.ts" y agregar el types.ts que esta a nivel de users como "actions.types.ts"

2023-07-17 12:46 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
> +  const handleSubmit = (values: IFormsInvitation) => {
Asignar values como tipo IFormsInvitation está mal porque iniciando por el hecho de que esa interfaz tiene todos los forms con su objeto de entries y en esta funcion en la linea 49 se deja claro que se esta recibiendo únicamente los values de un entries en específico no toda la estructura general de los forms, por otro lado aunque le este funcionando esto se debe a que los forms aun no están migrados a typescript y estos en el interface le pasan un "any" internamente al handleSubmit y por eso la función no arroja error de tipado, pero cuando se migren los forms si encontrara el error, una forma de hacer debug de esto es hacer lo siguiente en algún form del interface.tsx:

```typescript
{currentStep === stepsRegisterUserConfig.branches.id && (
              <BranchesForm
                currentBranches={invitationData.branches.entries}
                handleSubmit={(values: IAssignmentFormEntry) => handleSubmit(values)}
              />
            )}
``` 

Y eso arrojara error de tipo al asignar values, para solucionar estos e debe usar union types como se comentó en el primer comentario de la revisión.

Adicionalmente como recomendación se debe tener siempre en cuenta el "que puede pasar" con componentes (propios) que se están invocando y aún no están en typescript, para evitar luego tener que hacer otra refactorización en la medida de lo posible.

2023-07-17 23:16 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
> +  const handleSubmit = (values: IFormsInvitation) => {
Aún falta realizar correctamente este ajuste, IFormsInvitation nunca va a llegar en los forms.

2023-07-18 12:32 UTC, Sebas3245 requested changes

2023-07-18 12:32 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
> +      throw new Error();
Retonar un error en este caso no me parece adecuado ya que el  verbo getInvitationInformation no debería esperar eso, en este caso podríamos utilizar solo "if (!invitation) return"

2023-07-18 12:32 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/interface.tsx
> +const CompleteInvitationUI = (props: CompleteInvitationUIProps) => {
Acá porque se pasó a arrow function? tengo entendido que el estándar que estamos manejando dentro del proyecto es que para los componentes si usamos una function convencional, esto por el tema del scope, sin embargo, si hay alguna razón en específico comentarla en este hilo

2023-07-18 12:32 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
> +      throw new Error();
También podría ser un return de una estructura de IGeneralInformationEntry con los valores vacios

2023-07-18 14:19 UTC, merged