jg/484/migrate-invite-page-to-TypeScript
selsa-inube/linpar pull request #331
Opened 2023-07-14 15:40 UTC by novadeveloper14

2023-07-14 20:00 UTC, CristianRojas-47 requested changes
Se debería generar un archivo types.tsx para aquellas interfaces que pueden ser reutilizadas en otros componentes, como creo que sería el caso de IMessageConfig y IFormValues.

2023-07-14 21:55 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-07-14 22:15 UTC, Sebas3245 requested changes

2023-07-14 22:15 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/types.ts
> +interface IFormValues {
Cambiemos el nombre a "IInviteFormValues"

2023-07-14 22:15 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/interface.tsx
> +interface IMessageInvitationSentConfig {
Para no tener que crearse esta interfaz puede crearse un enumerador, un enum es una forma de definir un conjunto de valores constantes con nombre. Proporciona una forma legible y semántica de representar opciones o estados específicos, Ej:. 

```typescript
enum EMessageType{
    SUCCESS = "success",
    FAILED = "failed",
  }
``` 

Y lo puede implemetar de la siguiente manera:

```typescript
let messageType: EMessageType= EMessageType.SUCCESS;
  
  if (formInvalid) {
    messageType = EMessageType.FAILED;
  }
``` 

Este enum al ser tan general ya que aplica para diferentes partes de la aplicacion lo puede guardar en un archivo messages.types.ts dentro del directorio "types" que se encuentra en "src"

2023-07-17 12:48 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/interface.tsx
> +interface IMessageInvitationSentConfig {
Falta lo ultimo de este comentario.

2023-07-17 15:28 UTC, Sebas3245 approved these changes

2023-07-17 15:28 UTC, merged