feat(editUser): migrate editUser to typescript
selsa-inube/linpar pull request #351
Opened 2023-07-20 00:16 UTC by CristianRojas-47

2023-07-21 13:58 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-07-21 19:05 UTC, Sebas3245 requested changes
Hay errores tambien al pre-compilar el typescript 

1. Al haber cambiado las interfaces que tambien esta usando complete invitation como "IGeneralInformationEntry"
2. withSubmitButtons en todos los forms deberia ser una propeidad opcional

2023-07-21 19:06 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/index.tsx
>      generalInformation: { entries: getUserInformation() },
getUserInformation deberia retornar una estructura de IGeneralInformationEntry con los valores vacios si no encuentra el usuario, esto con el fin de que no devuelva undefined

2023-07-24 22:10 UTC, Sebas3245 requested changes

2023-07-24 22:10 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/edit-user/interface.tsx
> +  } = editData || { generalInformation: { entries: emptyUserData } };
No creo que sea necesaria esta declaración de "|| { generalInformation: { entries: emptyUserData } }" ni e emptyUserData teniendo en cuenta que abajo ya se está validando la existencia de currentInformation

2023-07-24 23:00 UTC, Sebas3245 approved these changes

2023-07-24 23:00 UTC, merged