jg/466/connect login pages using mocked endpoints
selsa-inube/linpar pull request #352
Opened 2023-07-21 05:55 UTC by novadeveloper14

2023-07-21 16:11 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-07-21 20:42 UTC, Sebas3245 requested changes

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/CheckingCredentials/index.tsx
> +interface IUser {
Esta interfaz deberia estar en un archivo types.ts

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/CheckingCredentials/index.tsx
> +  const getUser = async (): Promise<IUser | null> => {
Esta función podría estar por fuera del componente CheckingCredentials y eso aplica para todas las funciones que usemos para hacer fetch y solo necesitemos de ellas el retorno de X dato mientras que el setState si estará dentro del componente, en este caso solo sería dejarla por fuera y que reciba el user_id como string validando que ese parámetro exista antes de pasárselo  a la función

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/index.tsx
> +  const getUserClientsData = useCallback(async () => {
Lo mismo que en el caso anterior podemos dejar esta función del fetch por fuera y que el setState sea para el scope que llame a la función getUserClientsData, creo que con esto ya no sería necesario el useCallBack

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/index.tsx
> +    event.preventDefault();
Para no tener que hacer este event.preventDefault(); podriamos pasar el handleSubmit en el interface al metodo handleClick del Button "Continuar" en lugar de al form y quitar el type="submit" y dejar el type="button"

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/interface.tsx
> +      <Text typo="bodyMedium">{`No se encontraron resultados para "${search}".`}</Text>
No es necesario agregar los corchetes que representan un fragmento de javascript ni las backticks en ambos Texts

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/interface.tsx
> +  const showNoResults = filteredClients.length === 0;
Esta constante solo se usa en una parte del código, no es necesaria, la validación se puede hacer directamente en el JSX

2023-07-21 20:42 UTC, Sebas3245 commented on src/pages/login/outlets/Clients/interface.tsx
> +  const showSearchField = clients.length > 10;
Esta constante solo se usa en una parte del código, no es necesaria, la validación se puede hacer directamente en el JSX

2023-07-24 12:32 UTC, Sebas3245 commented on src/pages/login/outlets/CheckingCredentials/index.tsx
> +  const getUser = async (): Promise<IUser | null> => {
Aún falta lo último "que reciba el user_id como string validando que ese parámetro exista antes de pasárselo a la función", esto para que no reciba el user_id como parámetro opcional ya que no tendría coherencia porque la utilidad total de la función se perdería

2023-07-24 12:36 UTC, Sebas3245 requested changes
Realizar ajustes

2023-07-25 12:37 UTC, Sebas3245 approved these changes

2023-07-25 12:37 UTC, merged