jg/533/border-radius-on-assisted-background
selsa-inube/linpar pull request #357
Opened 2023-07-21 18:05 UTC by novadeveloper14

2023-07-21 20:05 UTC, ANGIECATHERINEP requested changes
Aun falta que el fondo gris ocupe desde el botón de prev hasta el botón de next, según requerimiento

2023-07-21 23:39 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-07-24 12:25 UTC, Sebas3245 requested changes

2023-07-24 12:25 UTC, Sebas3245 commented on src/components/feedback/Assisted/styles.ts
> +const StyledDesktopAssisted = styled.div`
Estuve revisando y a nivel del objetivo no vi cual era la diferencia en dejar:
gap: 8px;
border-radius: 8px;
background-color: ${colors.ref.palette.neutral.n20};
  
En StyledDesktopContainer ya que al final van a tener el mismo contenido, lo otro es que creando un StyledDesktopAssisted los pasos no ocupan el 100% del contenedor y en los mockups se ve que debe ocupar el 100%, podríamos no crear ese contenedor adicional y hacerlo en StyledDesktopContainer

2023-07-24 16:20 UTC, Sebas3245 requested changes
App: ![image](https://github.com/selsa-inube/linpar/assets/55991750/163e1d8a-1889-4fe6-858c-818f063c820d)
Figma: 
![image](https://github.com/selsa-inube/linpar/assets/55991750/5701203d-9134-4373-95e7-c33c5378e546)

No está ocupando el 100% del contenedor

2023-07-24 19:11 UTC, Sebas3245 approved these changes

2023-07-24 19:12 UTC, merged

2023-07-24 19:12 UTC, Sebas3245 commented
solved #347