Ap/485/migrate tabs to type script
selsa-inube/linpar pull request #359
Opened 2023-07-21 18:50 UTC by ANGIECATHERINEP

2023-07-24 18:59 UTC, novadeveloper14 approved these changes
La implementación se realizo correctamente.

2023-07-24 22:37 UTC, Sebas3245 requested changes
Se evidencian los siguientes errores de compilación de typescript:

![image](https://github.com/selsa-inube/linpar/assets/55991750/cd7b202e-9a2a-45ed-bd70-1f23ba613c2f)

![image](https://github.com/selsa-inube/linpar/assets/55991750/1016ea4b-10b1-44ad-a683-6575497c2cd2)

Este último se debe a que invitationDate se puso como opcional
![image](https://github.com/selsa-inube/linpar/assets/55991750/d7af5dd3-53b1-4200-aa97-4c2d06dcfe0d)

Para verificar todos los archivos de typescript se puede usar el comando "tsc" en una terminal de vscode, hay que tener en cuenta que previamente hay que tener instalado "npm i -g typescript", y las líneas rojas nos indicaran donde esta el error puntual, arriba de cada línea roja hay un path en color azul al que podemos acceder con ctrl+click:

![image](https://github.com/selsa-inube/linpar/assets/55991750/1b67934a-8d2a-453e-b537-2d8e121ea869)

2023-07-24 22:37 UTC, Sebas3245 commented on src/components/feedback/SectionMessage/index.tsx
> +  icon: JSX.Element | string;
Debería ser solo JSX.Element

2023-07-24 22:37 UTC, Sebas3245 commented on src/components/feedback/SectionMessage/interface.tsx
> +  icon: JSX.Element | string;
Debería ser solo JSX.Element

2023-07-24 22:37 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.tsx
> +          to={`complete-invitation/${invitation.id}`}
No podemos eliminar la validacion de status "Pending" ya que la idea es que no deje hacer el enrutamiento

2023-07-24 22:37 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/styles.ts
> +interface StyledLinkProps {
Debería ser IStyledLink ya que el sufijo "Props" es solo para interfaces de componentes funcionales

2023-07-24 22:37 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/index.tsx
> +  handleResendInvitation: (invitation?: IGeneralInformationEntry[]) => void;
El parámetro invitación no es necesario

2023-07-24 22:37 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/index.tsx
> +  const [message, setMessage] = useState<IInitialMessage>(initialMessageState);
Como initialMessageState ya tiene el tipo IInitialMessage definido no es necesario indicar que el estado es de ese tipo IInitialMessage

2023-07-24 22:37 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/index.tsx
> +  const handleShowMessage = (props: IInitialMessage) => {
Es preferible que una función convencional siga recibiendo el listado de parámetros en lugar de un "props" ya que esta convención es propia de componentes funcionales

2023-07-25 15:43 UTC, Sebas3245 requested changes

2023-07-25 15:43 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.tsx
> +              : "privileges/users"
Dejemos este else como un string vacio en lugar de "privileges/users"

2023-07-25 17:46 UTC, Sebas3245 approved these changes

2023-07-25 17:46 UTC, merged