feat(users): navigate to specific tab in page
selsa-inube/linpar pull request #360
Opened 2023-07-21 22:49 UTC by ANGIECATHERINEP

2023-07-21 22:53 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-07-24 12:41 UTC, Sebas3245 requested changes

2023-07-24 12:41 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/index.tsx
> +  }, [isSelected]);
Es muy necesario que en el array de dependencias este isSelected? lo digo porque en si no estamos usando ese valor dentro del efecto

2023-07-24 12:41 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/index.tsx
> +      setLoading(false);
Todo desde setLoading(false) para abajo debería estar en un setTimeout,  ya que en si serán dos timeout:
1. Hasta que el formulario se envié 
2. Hasta que se haga la redirección

Ya que pasar setLoading(true); y de una vez setLoading(false); nunca mostrara el loading en los botones

2023-07-24 22:18 UTC, Sebas3245 requested changes

2023-07-24 22:18 UTC, Sebas3245 commented on src/pages/privileges/outlets/users/invite/index.tsx
> +        }, 11000);
Podemos dejar este timeout en 5000, realmente 11000 es bastante y no se percibe que tendrá ese efecto

2023-07-24 22:59 UTC, Sebas3245 approved these changes

2023-07-24 22:59 UTC, merged