add example and controls in surface primary tabs
selsa-inube/linpar pull request #542
Opened 2024-01-18 23:51 UTC by LinconOssa

the requested surface changes are made

2024-01-19 22:05 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +import { useState } from "react";
Solved

2024-01-19 22:05 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +  const [surfaceTokens, setSurfaceTokens] = useState(
Solved

2024-01-19 22:05 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +      JSON.stringify(surfaceTokens.color.surface)
Solved

2024-01-19 22:07 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +            <SendInformationMessage appearance={formType!} />
According to what was discussed in the meeting we only implemented navlink

2024-01-19 22:07 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  surfaceTokens: typeof inube;
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  handleChangeTokens: any;
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  surfaceConfig: any;
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +                  textWithColorToken={config.example}
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/config/surface.config.tsx
> +import { EAppearance } from "@src/types/colors.types";
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/config/surface.config.tsx
> +      "Las superficies de tipo primario se utilizan en componentes que están relacionados a acciones principales o comunican relación a la marca.",
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/config/surface.config.tsx
> +    title: "Actualizacion para los tokens de texto ha sido exitosa",
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +    let updatedSurfaceTokens = { ...surfaceTokens.color.surface };
Solved

2024-01-19 22:08 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +        ...surfaceTokens.color,
Solved

2024-01-19 22:09 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +            tokenUpdate: surfaceTokens.color.surface,
Solved

2024-01-19 22:09 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +      ...surfaceTokens,
Solved

2024-01-19 22:09 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +        ...surfaceTokens.color,
Solved

2024-01-19 22:09 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +      palette={surfaceTokens.color.palette}
Solved

2024-01-19 22:09 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +      surfaceTokens={surfaceTokens}
Solved

2024-01-19 22:10 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +      palette={surfaceTokens.color.palette}
Solved

2024-01-19 22:10 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  palette: typeof inube;
Solved

2024-01-19 22:11 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +        <ThemeProvider theme={surfaceTokens}>
Solved

2024-01-19 22:11 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +                  category={key}
Asi lo define el componente FieldsetColorCard

2024-01-19 22:12 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/index.tsx
>  import { colorTabsConfig } from "./config/colorTabs.config";
Solved

2024-01-19 22:12 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
>    showMenu: boolean;
Solved

2024-01-19 22:12 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
>    const { "(max-width: 580px)": smallScreen, "(max-width: 1073px)": typeTabs } =
It is necessary to show what type of tab according to the screen, what type of tab will be rendered

2024-01-19 22:12 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +  const colorTabs = Object.keys(colorTabsConfig);
Solved

2024-01-19 22:12 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
>        {renderMessage(message, handleCloseMessage)}
Solved

2024-01-19 22:13 UTC, LinconOssa commented on src/routes/people.tsx
> +          element={<Surfaces token={token} handleSubmit={handleSubmit} />}
It is necessary to have the source of the information

2024-01-22 11:56 UTC, carin91 requested changes

2024-01-22 11:56 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/RenderSurfaceContentForm.stories.tsx
> +      defaultValue: { summary: inube },
The defaultValue is breaking the storybook loading. place a default option of "inube" instead of inube

2024-01-22 11:56 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  surfaceTokens: typeof inube;
This is pending, you are writing the inputs in 3 places. (1) The <RenderSurfaceContentFormUI/> in index.tsx, (2) The interface RenderSurfaceContentFormUIProps defintion in interface.tsx and (3) the destructuring in <RenderSurfaceContentFormUI/> in interface.tsx, al of them have a different order.

(1) 
![image](https://github.com/selsa-inube/linpar/assets/123512032/d7f7f4fc-7e82-440d-8ffc-6992527f7739)

(2)
![image](https://github.com/selsa-inube/linpar/assets/123512032/e4fd6801-7d44-447c-854f-5a6140a779a9)

(3)
![image](https://github.com/selsa-inube/linpar/assets/123512032/4c6a706e-bcca-46cf-b6ff-0cefcb09777d)

2024-01-22 11:56 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  surfaceConfig: any;
The formType is a String or an Appereace? i suggest to change the line 49 to "formType: Appearance | string"

2024-01-22 11:56 UTC, carin91 commented on src/pages/people/outlets/surfaces/config/surfaceTabs.config.tsx
> +const surfaceTabsConfig = {
Reevaluate the extension of this file, is it not a *.ts file?

2024-01-22 13:35 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  surfaceTokens: typeof inube;
![image](https://github.com/selsa-inube/linpar/assets/103295353/02cd9d99-a63b-4677-966e-5d6345ad1c70)
Solved

2024-01-22 13:41 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/RenderSurfaceContentForm.stories.tsx
> +      defaultValue: { summary: inube },
![image](https://github.com/selsa-inube/linpar/assets/103295353/45a06a07-4d15-4020-8119-31f39e033523)
Solved

2024-01-22 15:24 UTC, cmarin001 approved these changes
meet the requirements

2024-01-22 15:25 UTC, merged