Fix: Optimizing the <SendingInformation/> Component for Tablet Responsiveness
selsa-inube/linpar pull request #547
Opened 2024-01-22 12:45 UTC by carin91

This PR is attempting to solve issues 607, 609 and 610.

For the 607 issue the width and min-width properties of the StyledSectionMessage were changed.
For the 609 issue the props of the <StyledSectionMessage/> were adjusted.
For the 610 issue the unnecessary  comments were deleted.

2024-01-22 15:19 UTC, LinconOssa requested changes

2024-01-22 15:19 UTC, LinconOssa commented on src/components/feedback/SendingInformation/styles.ts
>    height: auto;
You need to use min-width: max-content; height y: auto;

2024-01-22 15:49 UTC, carin91 commented on src/components/feedback/SendingInformation/styles.ts
>    height: auto;
Attended with no change.
1) height: auto; is not related to the PR. It should be commented as an issue.
2) min-width: max-content; is required to guarantee to not changed the width of the component under the sized of its children. 

with the min-width property:
![image](https://github.com/selsa-inube/linpar/assets/123512032/56c57209-5ed8-4701-af12-0fedd4af7dea)
without the min-width property:
![image](https://github.com/selsa-inube/linpar/assets/123512032/782684b5-46ec-40a8-a1e4-f95f9ecee3ed)

2024-01-22 15:58 UTC, LinconOssa approved these changes
meets requirements

2024-01-23 16:11 UTC, cmarin001 reviewed
For optimal mobile screen resolution, the layout should resemble the following example: 
![image](https://github.com/selsa-inube/linpar/assets/45011420/88dad612-f75c-4002-b266-7b9da390847d)

However, currently, it appears as shown in this image: 
![image](https://github.com/selsa-inube/linpar/assets/45011420/e7544538-2f95-4bdb-adb7-722a19c2da0a)

As evident from the comparison, there is a misalignment of the close icon in relation to the design specifications provided in the Figma mockups.

2024-01-23 19:00 UTC, carin91 commented
I think there is a misunderstanding in the review, this is because (1) i included a new feature in the SendingInformationMessage for the <Lines/> and assigned this value in the storybook (2) The SendingInformationMessage uses theme and the storybook uses the -inube- theme, so, it looks different. To see what you want to see i decided to merge this component with main so, you can see what you expected to.

![image](https://github.com/selsa-inube/linpar/assets/123512032/fa617e91-b953-4118-a94c-d0d0f0222feb)

![image](https://github.com/selsa-inube/linpar/assets/123512032/29c9814f-460c-4712-950b-e684647dff7b)

I want you to notice that the component in surfaces and lines looks exactly the same, you need to assign a value to the new prop to visualize it as in the wireframes.

2024-01-23 20:31 UTC, cmarin001 reviewed
The critique pertains not to the color or theme, but to the layout, as observed in the example provided. When configuring the component for responsive design, it becomes evident that there is an issue. The current rendering fails to align with the component specifications as detailed in the Figma design.


This is what I expect to see 
![image](https://github.com/selsa-inube/linpar/assets/45011420/5224282c-34ee-422f-a571-11090705f0ea)

however this is what's currently I see
![image](https://github.com/selsa-inube/linpar/assets/45011420/8a953729-21a5-43d0-9675-8bb65af11d2a)

2024-01-23 22:15 UTC, cmarin001 reviewed
There is a layout error in this component, specifically concerning the close button. Currently, it displays with the same appearance as the component, but it should feature a dark appearance as per the Figma design specifications

![image](https://github.com/selsa-inube/linpar/assets/45011420/db910bf6-3e22-47e3-86de-4559c1919384)

![image](https://github.com/selsa-inube/linpar/assets/45011420/8e46b7dc-b19b-4d83-9a45-62a75a22f495)

here is what I expect to see 
![image](https://github.com/selsa-inube/linpar/assets/45011420/205d4f24-5864-48c5-9989-571819922321)

2024-01-23 22:20 UTC, cmarin001 commented on src/components/feedback/SendingInformation/index.tsx
>                  <Button
Per the Figma design specifications, the spacing for the buttons should be 'compact' when configured for mobile screens. However, at present, this consideration is not being accounted for

![image](https://github.com/selsa-inube/linpar/assets/45011420/2efb9c42-d9c1-45ad-a860-3e2793212cb3)

2024-01-23 23:05 UTC, carin91 commented on src/components/feedback/SendingInformation/index.tsx
>                  <Button
Cristal clear, i adjusted several conditions to guarantee the similitude with the wireframes.

2024-01-24 14:49 UTC, merged