Create /AppContext directory in context/ to store there current files
selsa-inube/linpar pull request #571
Opened 2024-01-30 00:16 UTC by LinconOssa

The AppContext directory is created to store index.tsx and types.ts and everything still works the same

2024-01-31 11:42 UTC, carin91 requested changes

2024-01-31 13:52 UTC, LinconOssa commented on src/pages/home/interface.tsx
> +import { AppContext } from "../../context/AppContext";
![image](https://github.com/selsa-inube/linpar/assets/103295353/86d1953d-552d-412d-86c9-a99fc2cd14f3)
Changed

2024-01-31 13:52 UTC, LinconOssa commented on src/pages/home/Home.stories.tsx
> +import AppContextProvider from "../../context/AppContext/index";
![image](https://github.com/selsa-inube/linpar/assets/103295353/3c87d63b-3646-4a09-aed5-ee3e7b9c4ad5)
Changed

2024-01-31 13:52 UTC, LinconOssa commented on src/App.tsx
> +import AppContextProvider from "./context/AppContext";
![image](https://github.com/selsa-inube/linpar/assets/103295353/20b2e849-c8fa-4b90-b417-47a707aadeaa)
Changed

2024-01-31 13:52 UTC, LinconOssa commented on src/context/AppContext/index.tsx
> +import linparLogo from "../../assets/images/linpar.png";
![image](https://github.com/selsa-inube/linpar/assets/103295353/386ee5b4-03f0-42e8-8b3a-c4fad6f2eabf)
I changed it to @assets

2024-02-01 15:59 UTC, carin91 approved these changes

2024-02-01 19:17 UTC, cmarin001 approved these changes
meet the requirements

2024-02-01 19:18 UTC, merged