Refactor positions to delete position context
selsa-inube/linpar pull request #794
Opened 2024-05-17 01:53 UTC by ANGIECATHERINEP

Refactor positions to delete position context

2024-05-17 17:57 UTC, LinconOssa approved these changes
Meets the requirements.

2024-05-20 12:48 UTC, carin91 requested changes

2024-05-20 12:48 UTC, carin91 commented on src/pages/privileges/outlets/positions/edit-position/index.tsx
> +  useEffect(() => {
why do you load linix-positions in edit-position?, you are loading linix-positions twice on the same page... This could be very expensive in time and machine operations.

The linix-positions are save in the "positions" state of the Positions component. Refactor to use this information, passing as prop the position to edit.

(...) I found this error in roles and linix-use-case, it must be changed.

2024-05-21 01:48 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/positions/edit-position/index.tsx
> +  useEffect(() => {
I was reviewing your comment and what happens is that in the configuration of the actions in edit cargo it has a Link tag and as such the edit component is located in routes so I investigated but I have not found a way to pass that data as a prop in this Link tag
![image](https://github.com/selsa-inube/isetting/assets/88405711/67efe991-edbb-4ead-92c9-805871dfcb5b)

2024-07-16 23:50 UTC, carin91 approved these changes

2024-07-16 23:50 UTC, merged