Consumption web options
selsa-inube/linpar pull request #810
Opened 2024-06-11 23:40 UTC by LinconOssa

Consumption is made for web options

2024-06-14 16:28 UTC, Andresbl123 commented on src/services/webOptions/index.tsx
> +      const options: RequestInit = {
Se puede sacar esta función fuera del `for`, ya que aquí se esta creando en cada iteración del bucle, lo cual no es optimo, esto se podría sacar a la línea 11

2024-06-14 16:28 UTC, Andresbl123 commented on src/services/webOptions/index.tsx
> +      const controller = new AbortController();
estas variables no es necesario que estén dentro del `try` se pueden sacar .

2024-06-14 16:28 UTC, Andresbl123 commented on src/services/webOptions/index.tsx
> +        signal: controller.signal,
Según el cometario donde se pude sacar esto fuera del `for` dará un error,  y esto se debe al controlador de aborto, y este solo crear y reutilizar un controlador de aborto solo cuando sea necesario, por lo cual dentro del `for` se puede crear una copia : `for(){// demás código;  const copiaOption = {...options, signal: controller.signal,} }`

2024-06-14 16:28 UTC, Andresbl123 commented on src/services/webOptions/index.tsx
> +      const data = await res.json();
esto puede ir despues del bloque del `if` de la línea 38

2024-06-14 16:38 UTC, Andresbl123 commented on src/services/webOptions/index.tsx
> +    } catch (error) {
se podría mejorar el manejo de errores, ya que por ejemplo, aquí no se esta haciendo nada con error, a pesar que en la línea 38 se esta creando el error, validar eje: `Todos los intentos fallaron. No se pudieron obtener los créditos del usuario. Último error: ${error.message}`

2024-06-14 18:21 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +      const controller = new AbortController();
ready

2024-06-14 18:21 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +      const options: RequestInit = {
ready

2024-06-14 18:21 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +        signal: controller.signal,
ready

2024-06-14 18:21 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +      const data = await res.json();
ready

2024-06-14 18:21 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +    } catch (error) {
There is no need, we already have a clear example for the error when there is no data shown on the page, such as the downloadable formats.

2024-06-14 19:34 UTC, Andresbl123 approved these changes
Cumple requerimiento

2024-06-26 09:08 UTC, carin91 requested changes

2024-06-26 09:08 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
> +          setLoading(false);
This is not working properly, the setLoading is set to false when both promises are fulfilled. Refactor to use promiseAll

2024-06-26 09:08 UTC, carin91 commented on src/services/webOptions/index.tsx
> +    } catch (error: any) {
avoid the any type

2024-06-26 09:08 UTC, carin91 commented on src/services/webOptions/index.tsx
> +          `Todos los intentos fallaron. No se pudieron obtener los créditos del usuario. Último error: ${error.message}`
This is out of context, change the error description.

2024-06-26 17:20 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
> +          setLoading(false);
Promise.all is a solid choice here because it optimizes performance by making multiple asynchronous calls in parallel, provides clear control over loading state, and ensures consistency of updated data in your React component.

2024-06-26 17:20 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +    } catch (error: any) {
Resolved

2024-06-26 17:20 UTC, LinconOssa commented on src/services/webOptions/index.tsx
> +          `Todos los intentos fallaron. No se pudieron obtener los créditos del usuario. Último error: ${error.message}`
Resolved

2024-07-03 01:48 UTC, merged