Load the information to complete the add linix use case
selsa-inube/linpar pull request #812
Opened 2024-06-20 00:50 UTC by LinconOssa

The consumption is made and the postman remains the pending error that was discussed in the Meeting![image](https://github.com/selsa-inube/isetting/assets/103295353/3db93aab-8591-4fd2-b503-9e3df77c7937)

2024-06-26 00:46 UTC, novadeveloper14 requested changes

2024-06-26 00:46 UTC, novadeveloper14 commented on src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
if for example you put a letter "a" in the search engine. Many records appear at the same time and this is bad because it makes the application slower by loading so much data from one moment to the next. so I propose that you talk to Camilo about the inclusion in this modal of this functionality which is a button that appears if there are more than 5 records and if you click on it it will load 5 more records and thus does not show all of them at once.

![image](https://github.com/selsa-inube/linpar/assets/87447257/82deee93-41d4-4727-bdb8-75c63a7a2aee)

Example: 

![image](https://github.com/selsa-inube/linpar/assets/87447257/ef782fa7-8d12-439a-ae17-17f5459960b2)

2024-06-26 00:46 UTC, novadeveloper14 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
When you do enter on your keyboard in this input, the application redirects to the beginning and the information is losing, please solve since the filtering is being done when doing onChange

![image](https://github.com/selsa-inube/linpar/assets/87447257/48c7ad04-6e1a-44ad-8700-35430424233d)

2024-06-26 00:46 UTC, novadeveloper14 commented on src/pages/privileges/outlets/linixUseCase/index.tsx
I created a use case but it was in the middle of the table on page 2 so I don't know how the table is being organized. In my opinion, the most recent record that has been created should be first, but I talked to Camilo to see how they can come to an agreement.


![image](https://github.com/selsa-inube/linpar/assets/87447257/b756047f-263f-4ab3-9c5f-3d212b76bf64)

2024-06-26 00:54 UTC, novadeveloper14 requested changes
a

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
> +import { getWebOptionsFormats } from "@src/services/webOptions";
The change was made

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
The change was made

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
What you say is correct, but Camilo and I had a meeting with Pedro and he told us that they removed those texts, that's why there is only the green button and no text.

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/index.tsx
The change was made
![image](https://github.com/selsa-inube/linpar/assets/103295353/0fb0e2f2-0860-47c9-a7f3-707180370926)

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/VerificationForm/index.tsx
The change was made

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
An issue will be created for this

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
The change was made

2024-06-26 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/index.tsx
An issue will be created for this

2024-06-27 00:35 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
The change was made

2024-06-27 07:00 UTC, novadeveloper14 approved these changes

2024-07-09 08:55 UTC, carin91 approved these changes

2024-07-09 08:55 UTC, merged