Implement the delete role
selsa-inube/linpar pull request #818
Opened 2024-07-05 00:12 UTC by LinconOssa

The implementation of Delete is done

2024-07-05 17:18 UTC, ANGIECATHERINEP requested changes

2024-07-05 17:18 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +        <Stack direction="column" padding={smallScreen ? "s200" : "s400 s800"}>
change the padding value to px

2024-07-05 17:18 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/roles/delete-role/index.tsx
> +
delete these comments

2024-07-05 17:18 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/roles/index.tsx
> +  // }, [idDeleted]);
delete these comments

2024-07-05 17:18 UTC, ANGIECATHERINEP commented on src/services/roles/useCasesByRole/mappers.ts
> +  reportsClientServerFormat: Record<string, string | number | object>
rename prop

2024-07-05 17:18 UTC, ANGIECATHERINEP commented on src/services/roles/useCasesByRole/mappers.ts
> +  reportsClientServerFormat: Record<string, string | number | object>[]
rename prop

2024-07-05 17:52 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/delete-role/index.tsx
> +
Resolved

2024-07-05 17:52 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/index.tsx
> +  // }, [idDeleted]);
Resolved

2024-07-05 17:52 UTC, LinconOssa commented on src/services/roles/useCasesByRole/mappers.ts
> +  reportsClientServerFormat: Record<string, string | number | object>
Resolved

2024-07-05 17:52 UTC, LinconOssa commented on src/services/roles/useCasesByRole/mappers.ts
> +  reportsClientServerFormat: Record<string, string | number | object>[]
Resolved

2024-07-05 18:08 UTC, ANGIECATHERINEP approved these changes

2024-07-09 09:32 UTC, carin91 approved these changes

2024-07-09 09:32 UTC, merged