jg/21/mockup-menu-component
selsa-inube/linpar pull request #82
Opened 2023-02-01 05:59 UTC by novadeveloper14

2023-02-02 16:36 UTC, ANGIECATHERINEP requested changes
el componente esta bien desarrollado, ajustar lo comentado en el código.

2023-02-02 16:36 UTC, ANGIECATHERINEP commented on src/components/Menu/styles.js
> +  height: 970px;
El height no es necesario, ya que la altura se ajusta en el componente <AppPage />

2023-02-02 18:17 UTC, novadeveloper14 commented on src/components/Menu/styles.js
> +  height: 970px;
Listo ya esta el cambio realizado.

2023-02-02 20:14 UTC, ANGIECATHERINEP approved these changes

2023-02-06 15:00 UTC, wfercanas commented on src/components/Menu/index.jsx
> +              className={index === 0 ? "active" : ""}
No estamos usando las clases de CSS para aplicar estilos dinámicos. Para que los estilos cambien estamos usando las props y los styled-components.

Aquí está creando una prop llamada className (y que podría llamarse de cualquier otra forma). Luego `<IconButtonMenu>` recibe la prop y se la pasa al `<StyledButton>` (ahí sí se convierte ya no en una prop sino en una clase de CSS).

**Tarea**: revise todos los estilos que aplicó usando la clase de CSS y modifiquelos para que el componente reaccione según las props que recibe. Es decir, no usar el `<StyledMenu>` para que sus hijos reaccionen vía selectores tipo `& .active`, sino que el menú le pase props a los `<NavLink>` y que éstos al recibir esas props sepan cómo pintarse.

2023-02-06 15:01 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +function IconButtonMenu(props) {
Saquemos este componente de aquí y llevemoslo al index.jsx del menú.

2023-02-07 16:48 UTC, ANGIECATHERINEP requested changes
Falta realizar el pull de la rama main

2023-02-07 16:48 UTC, ANGIECATHERINEP commented on src/components/Menu/styles.js
> +  font-weight: ${(props) => (props.active ? "550" : "400")};
pienso que es no necesario colocar paréntesis en la validación de las props.active, ya que en las otras lineas no las colocaste

2023-02-07 16:48 UTC, ANGIECATHERINEP commented on src/components/Menu/styles.js
> +  padding: ${(props) =>
Recomendaría que los atributos que ya están definidos queden en la parte superior; y los que dependen de props quedaran después de estos, para que así sea más legible el código

2023-02-07 17:00 UTC, novadeveloper14 commented on src/components/Menu/styles.js
> +  font-weight: ${(props) => (props.active ? "550" : "400")};
lo que pasa es que al subirlo a el repositorio se modifico, seria hacer que todas tengan esta estructura o que me recomiendas?

2023-02-07 19:21 UTC, ANGIECATHERINEP approved these changes
los cambios han sido realizados

2023-02-08 15:59 UTC, wfercanas requested changes

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/Menu.stories.js
> +  title: "components/Menu",
Cree un decorator que:
1. Incluya un div que agregue una grilla de 2 filas y 2 columnas. La idea es simular el layout en el que tendría que aparecer el `<Menu />`.
2. Dentro de esa grilla tener un `<div>` que envuelva a `<Story />` y que se encargue de definir en qué celda de la grilla va el `<Menu />`.
3. Los 2 contenedores anteriores deben ser creados usando styled-components. Para ello se debe crear un archivo llamado **stories.styles.js** y así no los mezclamos con los styled-components del componente como tal.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/Menu.stories.js
> +};
Además del decorator, es necesario remover el padding que trae el `<body>` de storybook por defecto. Para ello, en el objeto story agrege lo siguiente:

```js
const story = {
  // ...content
  parameters: {
    layout: "fullscreen"
  }
}
```

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/Menu.stories.js
> +};
Para más información de qué hace esta propiedad, vea la documentación: https://storybook.js.org/docs/react/configure/story-layout

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/Menu.stories.js
> +
Agreguemos una historia para el `<MenuLink />`. El título que sea ese mismo: "MenuLink"

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/Menu.stories.js
> +  title: "components/Menu",
Asegúrese de que el Menú con estos cambios ocupe todo el espacio vertical de la segunda fila y primer columna de la grilla.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/index.jsx
> +function NavLink(props) {
Cambié de opinión con respecto a este nombre, dejemos mejor `<MenuLink />` para que sea evidente su relación con el `<Menu />`

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/index.jsx
> +    type = "button",
Esta prop quitemosla. Este `<MenuLink />` no va a ser un `<button>` sino un `<Link />` importado de 'react-router-dom'.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/index.jsx
> +    icon2,
Es correcto que este componente reciba el primer ícono por props, ya que hay que decirle a este Link qué ícono usa la app y cómo se llama la app para poder mostrar ese combo en el Menú.

Sin embargo, el segundo ícono ya no es información externa que deba ser obtenida, sino que ya este componente tiene como implementación una flecha que indica en dónde está el usuario. Por esa razón, este ícono no es algo que deba pedirle a los demás, sino un conocimiento que debe tener este componente.

**Conclusión**: no pedir este ícono por props.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/index.jsx
> +    active,
Cambiar esta prop por "selected". Para más información de este elemento ver: https://www.figma.com/file/XqKc1IZsj89aMIsJczTgb7/Components?node-id=2068%3A6726&t=G0VIm5OAAe3YBbqo-0

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/index.jsx
> +          {links.map((link, index) => (
`<StyledNavList>` es una lista `ul`, hay que colocar por dentro del map que se retorna un `li`. En ese `li` aproveche y coloque la prop `key`, que hay que pasarla cada vez que se hace un map.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/index.jsx
> +          {links.map((link, index) => (
No es necesario que ese `li`sea un styled-component.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/styles.js
> +const StyledLink = styled.button`
La idea aquí es usar un <Link /> de react-router-dom. Entonces, es necesario:

1. Importar aquí {Link} from 'react-router-dom'
2. Estilizarlo usando styled(Link)``

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/styles.js
> +  border-bottom: 0;
Con el Styled(Link) creo que estas propiedades de border deben sobrar.

2023-02-08 15:59 UTC, wfercanas commented on src/components/Menu/styles.js
> +  min-width: 100%;
Es mejor dejar `width` que `min-width` en este caso. Le estaría permitiendo eventualmente al link que se desborde del ancho.

2023-02-08 16:45 UTC, wfercanas requested changes

2023-02-08 16:45 UTC, wfercanas commented on src/components/Menu/styles.js
> +  border-right: 1px solid ${colors.ref.palette.lightNeutral.ln500};
Cambiar estos `lightNeutral` por la nueva estructura de colores que ya está en **main**

2023-02-10 15:37 UTC, wfercanas requested changes
Además de los cambios solicitados en el código, hacer estos cambios:
1. Crear la carpeta navigation dentro de **src/components**
2. En esa carpeta navigation, crear las carpetas Menu y MenuLink
3. En cada carpeta crear el index.jsx y styles.js de cada componente
4. Crear la carpeta **stories/** al mismo nivel del index.jsx
5. En esa carpeta de **stories/** crear los archivos *.stories.js
6. Si las historias necesitan de styled-components, crear en **stories/** el archivo stories.styles.js

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/stories/Menu/stories.styles.js
> +const StyledContainer = styled.div`
Aunque yo aumente este contenedor a `height: 100vh` (como debería estar), el Menú no está tomando todo el espacio vertical que le corresponde.

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/stories/Menu/Menu.stories.js
> +export const Default = withGrid(Template.bind({}));
Hagamos 2 historias aquí:
1. El menú sólo (Default)
2. El menú dentro de la grilla (Layout).

En la historia llamada Layout, puede importar el `<Header />` para ver ambas cosas en su lugar.

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/styles.js
> +  border-right: 1px solid ${colors.ref.palette.neutral.n60};
Hicimos unos cambios en el componente y ahora este border es un n40.

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/styles.js
> +  border-top: 1px solid ${colors.ref.palette.neutral.n60};
Hicimos unos cambios en el componente y ahora este border es un n40.

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/styles.js
> +  width: 216px;
Dejemos este width como porcentaje. Aquí en desktop puede que esté bien con 216px, pero cuando pasemos al menú que ocupa todo el ancho de la pantalla, este width se puede quedar chiquito.

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/styles.js
> +const StyledMenu = styled.nav`
Hicimos unos cambios en el background y ahora este nav tiene de fondo un n10.

2023-02-10 15:37 UTC, wfercanas commented on src/components/Menu/styles.js
> +      : colors.ref.palette.neutral.n0};
Por los cambios que hicimos en el fondo, esta tarjeta se ve como n10 cuando no está selected. Ahora... como el fondo del nav ya tiene ese color, aquí podríamos no definirle un bgColor o definirle un n0a que es 100% transparente.

2023-02-13 14:53 UTC, wfercanas requested changes

2023-02-13 14:53 UTC, wfercanas commented on src/components/navigation/MenuLink/styles.js
> +    font-weight: 500;
Utilice los tokens de referencia de typography, no el número literal: `typography.ref.typeface.weight.medium`

2023-02-13 14:53 UTC, wfercanas commented on src/components/navigation/MenuLink/stories/MenuLink.stories.js
> +export const Default = Template.bind({});
Dejemos la historia Default para el caso donde selected es false.
Cree otra historia que se llame Selected para ese caso.

2023-02-13 14:53 UTC, wfercanas commented on src/components/navigation/Menu/styles.js
> +  max-width: 100%;
Déjelo como `width`, le da más control sobre el ancho.

2023-02-13 14:53 UTC, wfercanas commented on src/components/navigation/Menu/styles.js
> +  grid-template-columns: repeat(auto-fit, minmax(1fr));
Esta propiedad sobra.

2023-02-13 14:53 UTC, wfercanas commented on src/components/navigation/Menu/styles.js
> +  gap: 5px;
Coloquemos un gap de 4px. Todos los espaciados en el sistema de diseño lo estamos haciendo con múltiplos de 4px.

2023-02-13 14:53 UTC, wfercanas commented on src/components/navigation/Menu/styles.js
> +  margin: 8px 17px;
Dejemos 16px en lugar de 17px. Si en los mockups está diferente dígale a Leonardo para que corrija.

2023-02-13 20:23 UTC, wfercanas approved these changes

2023-02-13 20:24 UTC, merged