implement the edit
selsa-inube/linpar pull request #823
Opened 2024-07-18 00:14 UTC by LinconOssa

2024-07-26 04:06 UTC, carin91 requested changes
The data loaded on the general information is not charging on the firs rendering.
![image](https://github.com/user-attachments/assets/fa2f3dfe-27d7-4c3b-b5c7-bc8dbe6c37ea)
Verify the state life cycle of this component

2024-07-26 04:06 UTC, carin91 commented on src/pages/privileges/outlets/roles/components/GeneralInformationForm/index.tsx
> +    // const handleSubmit = async () => {
delete every comment

2024-07-26 04:06 UTC, carin91 commented on src/pages/privileges/outlets/roles/components/GeneralInformationForm/interface.tsx
> +            handleSubmit={() => {}}
Refactor the general information form to delete its handle button and submit

2024-07-26 04:06 UTC, carin91 commented on src/pages/privileges/outlets/roles/components/InitializerForm/index.tsx
> +  handleSubmit: (renderForm: IAssignmentFormEntry[]) => void;
Delete the handle submit in the initializer form

2024-07-26 22:23 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/components/AncillaryAccountsForm/index.tsx
> +      // handleSubmit={handleSubmit}
Resolved

2024-07-26 22:23 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/components/GeneralInformationForm/index.tsx
> +    // const handleSubmit = async () => {
resolved

2024-07-26 22:23 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/components/GeneralInformationForm/interface.tsx
> +            handleSubmit={() => {}}
Resolved

2024-07-26 22:52 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/components/AncillaryAccountsForm/index.tsx
> +  const [isLoading] = useState(false);
Resolved

2024-07-26 22:52 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/components/InitializerForm/index.tsx
> +  handleSubmit: (renderForm: IAssignmentFormEntry[]) => void;
-The handleSubmit is needed to provide a centralized and flexible point where all the necessary logic that needs to occur when the form is submitted or when its values ​​change can be handled. This includes additional validations, asynchronous calls, application state updates, and user notifications, among others.

I renamed it to

onFormValueChange:
• Indicates that the function is executed when there is a change in the form values.

-In short, onHasChanges is useful for maintaining communication between the form component and the component that contains it, allowing for greater flexibility and control over the state of the form and how changes are handled.

-these two are necessary

changeData

setChangedData

2024-07-30 10:51 UTC, carin91 approved these changes

2024-07-30 11:00 UTC, merged