User service is provided
selsa-inube/linpar pull request #824
Opened 2024-07-20 16:11 UTC by LinconOssa

2024-07-23 13:41 UTC, SelsaErojas requested changes
1. In the browser console there are some errors due to primary keys, check

![image](https://github.com/user-attachments/assets/33dfb371-81a6-4619-bc2f-3d2e6f3ad46e)

2. in the search option it does not work after the second sheet

2024-07-23 13:41 UTC, SelsaErojas commented on src/pages/privileges/outlets/users/tabs/users/index.tsx
>  } from "@pages/privileges/outlets/users/config/usersTable.config";
at line 3 you should use the components of inubekit

2024-07-23 13:41 UTC, SelsaErojas commented on src/pages/privileges/outlets/users/tabs/users/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
you should remove the comments

2024-07-23 15:08 UTC, LinconOssa commented on src/pages/privileges/outlets/users/tabs/users/index.tsx
>  } from "@pages/privileges/outlets/users/config/usersTable.config";
The change is made for useMediaQuery but for the table it will be done in a later task.

2024-07-23 15:08 UTC, LinconOssa commented on src/pages/privileges/outlets/users/tabs/users/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
The // eslint-disable-next-line react-hooks/exhaustive-deps comment is used to temporarily disable a specific ESLint rule, in this case react-hooks/exhaustive-deps, on the next line of code.

This ESLint rule is designed to ensure that all React hook dependencies (such as useEffect, useCallback, and useMemo) are correctly specified in the dependency list. Ignoring this rule may be necessary in situations where you are sure that the dependency list is correct, but ESLint keeps flagging an error that you consider incorrect or irrelevant.

2024-07-23 15:34 UTC, SelsaErojas approved these changes
functional

2024-07-24 18:12 UTC, Dlfp reviewed
Dejo aquí unos comentarios generales: 

1. Al verificar la consola del explorador se evidencian errores. A continuación una imagen. 
![image](https://github.com/user-attachments/assets/16f8d5ec-5a79-4c08-8e98-3b67db98f2e5)

2.  La idea es que los usuarios se desplieguen ordenados alfabeticamente por el nombre. Para lo cual se puede usar el query-param sort, al consumir el Get. A continuación los ejemplos que aparecen en la documentación: 
a. [GET] url/users?sort=desc.Age,FirstName
: Ordenará la consulta primero de forma descendente por edad y luego de forma ascendente por nombre.
b. [GET] url/users?sort=FirstName,asc.Age,
: Ordenará la consulta primero de forma ascendente por nombre y luego de forma ascendente por edad.

2024-07-24 21:49 UTC, LinconOssa commented on src/pages/privileges/outlets/users/tabs/users/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
resolved

2024-07-25 13:25 UTC, Dlfp approved these changes

2024-07-25 13:26 UTC, merged