Users adjust
selsa-inube/linpar pull request #830
Opened 2024-07-30 20:04 UTC by LinconOssa

The names for the config are adjusted and the service that was being consumed for Users is corrected.

2024-07-31 15:30 UTC, SelsaErojas requested changes
Adjust the title the code column
![image](https://github.com/user-attachments/assets/0f43dc5c-a573-4d5b-a290-d6e9c2fb793d)

2024-07-31 23:47 UTC, SelsaErojas approved these changes
functional

2024-08-01 20:27 UTC, Dlfp reviewed
Se hizo la prueba de modificación de roles y casos de uso y, en ninguno de los dos, se activó el botón Cancelar ... por favor verificar.

2024-08-01 20:27 UTC, Dlfp commented on src/services/roles/aplicationRoles/index.tsx
>    const fetchTimeout = 3000;
usar las variables de entorno antes mencionadas

2024-08-01 20:27 UTC, Dlfp commented on src/services/roles/businessRulesByRole/index.tsx
usar las variables de entorno antes mencioandas

2024-08-01 20:27 UTC, Dlfp commented on src/services/roles/businessRulesByRole/index.tsx
>      method: "GET",
La idea es que las reglas de negocio salgan ordenados alfabeticamente por nombre. Marcela Gonzalez está ajustando los servicios para incluir la clausula. Por favor coordinar con ella la entrega para poderlos verificar.

2024-08-01 20:27 UTC, Dlfp commented on src/services/roles/useCasesByRole/index.tsx
usar variables de entorno antes mencioandas

2024-08-01 20:27 UTC, Dlfp commented on src/services/webOptions/index.tsx
usar variables de entorno antes mencionadas

2024-08-01 20:27 UTC, Dlfp commented on src/services/roles/creditboardTasksByRole/index.tsx
>    const maxRetries = 5;
quitar el paso de tareas crediboard del asistido de roles. 
Segun  me dice Marcela Gonzalez, aun cuando elimine este paso, la inserción, modificación y borrado debe operar correctamente; aun cuando el backend no haya sido ajustado.

2024-08-01 22:30 UTC, LinconOssa commented on src/services/linixUseCase/clientServerButtonData/index.tsx
>    const maxRetries = 5;
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/linixUseCase/clientServerMenuOption/index.tsx
>    const fetchTimeout = 3000;
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/linixUseCase/reportsClientServer/index.tsx
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/linixUseCase/editLinixUseCase/index.tsx
>  const editLinixUseCase = async (
It will be fixed on the new card

2024-08-01 22:30 UTC, LinconOssa commented on src/services/linixUseCase/reportsWeb/index.tsx
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/roles/ tipoDeMovimientoPorRol/index.tsx
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/roles/aplicationRoles/index.tsx
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/roles/aplicationRoles/index.tsx
>    const fetchTimeout = 3000;
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/roles/businessRulesByRole/index.tsx
Resolved

2024-08-01 22:30 UTC, LinconOssa commented on src/services/roles/useCasesByRole/index.tsx
Resolved

2024-08-01 22:31 UTC, LinconOssa commented on src/services/webOptions/index.tsx
Resolved

2024-08-01 22:31 UTC, LinconOssa commented on src/services/roles/creditboardTasksByRole/index.tsx
>    const maxRetries = 5;
It will be fixed on the new card

2024-08-13 17:20 UTC, LinconOssa commented on src/services/linixUseCase/clientServerButtonData/index.tsx
>      method: "GET",
Resolved

2024-08-13 17:20 UTC, LinconOssa commented on src/services/roles/businessRulesByRole/index.tsx
>      method: "GET",
Resolved

2024-08-15 14:52 UTC, Dlfp approved these changes

2024-08-15 14:53 UTC, merged