Make the consumption for charges the delete button
selsa-inube/linpar pull request #833
Opened 2024-08-06 22:14 UTC by LinconOssa

The functionality of eliminating charges is made. This functionality only works with the following:
![image](https://github.com/user-attachments/assets/fd4c4e1e-4e8f-474e-b62d-d4ef55b21994)

Since the other fields in the postman don't let me either, it appears like this:
![image](https://github.com/user-attachments/assets/883db13d-bb25-43c4-9cec-6356e3664d0f)
![image](https://github.com/user-attachments/assets/1fc6dd8b-41a0-44c3-9b3f-f9405b6dd35f)

2024-08-08 17:37 UTC, SelsaErojas requested changes

2024-08-08 17:37 UTC, SelsaErojas commented on src/services/positions/deletePositions/index.tsx
> +      const errorMessage = `Error al eliminar el Caso de Uso. Status: ${
you should change the error message according to the funcionality

2024-08-08 17:37 UTC, SelsaErojas commented on src/services/positions/deletePositions/index.tsx
> +    console.error("Failed to delete Caso de Uso:", error);
you should change the error message according to the funcionality

2024-08-08 19:33 UTC, LinconOssa commented on src/services/positions/deletePositions/index.tsx
> +      const errorMessage = `Error al eliminar el Caso de Uso. Status: ${
Resolved

2024-08-08 19:33 UTC, LinconOssa commented on src/services/positions/deletePositions/index.tsx
> +    console.error("Failed to delete Caso de Uso:", error);
Resolved

2024-08-08 20:58 UTC, SelsaErojas approved these changes
Functional

2024-08-15 16:56 UTC, Dlfp approved these changes

2024-08-15 16:56 UTC, merged