Edit positions
selsa-inube/linpar pull request #835
Opened 2024-08-13 23:45 UTC by LinconOssa

The consumption of editing is done and it is tested that this branch works, the rest of adding and deleting does not work because the other branches have not been accepted, leaving last because this branch may have conflicts to resolve later.

2024-08-14 16:04 UTC, SelsaErojas requested changes
in the Roles editing tab, the options have the name "<string>", you should check that
![image](https://github.com/user-attachments/assets/ee2512b4-f243-46e0-89c8-e0b575ca6f14)

In this option
![image](https://github.com/user-attachments/assets/8cfd84d1-9a80-41d0-b784-c2f4c73a9fd7)

allows locate in the inputs when it should not be allowed
![image](https://github.com/user-attachments/assets/19fee70a-83ac-401f-80cb-2be18aa20028)

By the way when you click on this option an error appears in the console
![image](https://github.com/user-attachments/assets/7f198216-95fa-47de-8b39-b1f58f94149c)

2024-08-14 20:39 UTC, LinconOssa commented
The change will be made to a new card since the change is a bit big and many things have to be changed to inubekit

2024-08-15 16:58 UTC, SelsaErojas approved these changes
Functional

2024-08-20 16:02 UTC, Dlfp approved these changes

2024-08-20 16:02 UTC, merged