Invitation users
selsa-inube/linpar pull request #848
Opened 2024-09-03 23:27 UTC by LinconOssa

En esta tarea se realiza la tarjeta 970,  se hace la integración con development y se hace el servicio de la invitación pero el servicio esta caído  :
![image](https://github.com/user-attachments/assets/b0e3238d-e7a1-4489-90a9-b973f053c922)

2024-09-04 16:49 UTC, SelsaErojas requested changes
when trying to save data the following error occurs
![image](https://github.com/user-attachments/assets/b2c15eb0-7bfe-482b-894b-5525109aaa50)
you should show if the input the phone is incorrect like input email

When saving in the console the following error is shown
![image](https://github.com/user-attachments/assets/82452ffb-342d-4d00-b9ae-9b0163c3b084)

2024-09-04 16:49 UTC, SelsaErojas commented on src/services/invitations/postInvitations/index.tsx
> +        "X-User-Name": "LICON",
you should remove this line or change by the requiered

2024-09-04 17:48 UTC, LinconOssa commented on src/services/invitations/postInvitations/index.tsx
> +        "X-User-Name": "LICON",
Según lo hablado con Marcela esta acción no se puede quitar tocaría validar con la Ingeniera de que nombre seria mejor pata la Linea17

2024-09-04 18:13 UTC, SelsaErojas approved these changes
Functional

2024-09-05 17:05 UTC, LinconOssa commented on src/services/invitations/postInvitations/index.tsx
> +        "X-User-Name": "LICON",
![image](https://github.com/user-attachments/assets/c66bc0fb-c844-4ec0-9178-81c97e836cd2)
Se realiza el cambio para que este en el contexto

2024-09-05 20:56 UTC, Dlfp approved these changes

2024-09-05 20:56 UTC, merged