feat(pageTitle): creation pageTitle component
selsa-inube/linpar pull request #91
Opened 2023-02-07 21:23 UTC by CristianRojas-47

2023-02-08 16:18 UTC, ANGIECATHERINEP requested changes

2023-02-08 16:18 UTC, ANGIECATHERINEP commented on src/components/PageTitle/index.jsx
> +          <Heading level="1"> {title} </Heading>
Recomendaría eliminar el atributo level del componente <Heading />, ya que este ya está predeterminado con el numero 1 en las props de dicho componente

2023-02-08 19:53 UTC, wfercanas requested changes

2023-02-08 19:53 UTC, wfercanas commented on src/components/PageTitle/styles.js
> +  padding: 0 32px;
El componente no debe tener padding.

2023-02-08 19:53 UTC, wfercanas commented on src/components/PageTitle/styles.js
> +  max-width: 1400px;
Este componente no requiere un max-width. Si llega el caso en que la pantalla es muy ancha y hay que controlar ese ancho, de eso se encarga el layout, no el componente.

2023-02-08 19:53 UTC, wfercanas commented on src/components/PageTitle/index.jsx
> +        <Text> {description} </Text>
El texto de la descripción usa como color el token de sistema `color.sys.text.secondary`. Usar la prop `colorProp` de `<Text />` para esol

2023-02-08 23:30 UTC, ANGIECATHERINEP approved these changes
Los cambios realizados re hicieron correctamente

2023-02-09 15:48 UTC, wfercanas requested changes

2023-02-09 15:48 UTC, wfercanas commented on src/components/PageTitle/index.jsx
> +    <StyledGreetingContainer>
Este Styled se llama así porque fue hecho específicamente para el saludo al usuario en el `<Home />`. Como este ya es un componente genérico, podemos renombrarlo como `<StyledPageTitle />`

2023-02-09 15:48 UTC, wfercanas commented on src/components/PageTitle/styles.js
> +  margin: 40px auto 32px;
Este `margin` auto a izquierda y derecha no tiene ningún efecto porque el div por defecto es `display: block` y ocupa todo el ancho. 

Sin embargo, si por alguna razón el `width` de este componente se ve modificado, lo que va a pasar es que el título de la página se va a poner en el centro y no a la izquierda como debería estar.

**Corrección**: no dejar margin auto a izquierda y derecha.

2023-02-09 15:48 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +    color = "primary",
Dejar esta prop como `colorToken`

2023-02-09 16:32 UTC, ANGIECATHERINEP approved these changes
Los cambios solicitados se realizaron correctamente

2023-02-09 22:03 UTC, wfercanas approved these changes

2023-02-09 22:03 UTC, merged