Ap/42/app menu card component
selsa-inube/linpar pull request #94
Opened 2023-02-09 23:21 UTC by ANGIECATHERINEP

2023-02-10 14:16 UTC, CristianRojas-47 requested changes

2023-02-10 14:16 UTC, CristianRojas-47 commented on src/components/cards/AppMenuCard/styles.js
> +  height: 135px;
Las medidas del contenedor no se están conservando, el padding realizado se toma exteriormente generando un desborde.

2023-02-10 14:16 UTC, CristianRojas-47 commented on src/components/cards/AppMenuCard/index.jsx
> +        <Text align="center"> {description} </Text>
Recomiendo utilizar ( typoToken="bodySmall" ) para dar el size de la descripción.

2023-02-10 14:16 UTC, CristianRojas-47 commented on src/components/cards/AppMenuCard/index.jsx
> +        <Text align="center" typoToken="titleLarge">
No se encuentra opción para medida de 20px en typography, se tomó la medida más cercana lo cual me parece correcto.

2023-02-10 14:51 UTC, CristianRojas-47 approved these changes
El desarrollo del componente es correcto.

2023-02-10 17:01 UTC, wfercanas requested changes

2023-02-13 14:59 UTC, wfercanas approved these changes

2023-02-13 14:59 UTC, merged